// A bundle-scoped listing deep link must actually filter the list (#2418).
//
// The destination is generated by Waaseyaa\AdminSurface\AdminDestinationPaths
// (#2420). An unknown or unauthorized bundle must degrade to the unscoped
// listing rather than erroring or returning an empty table, so a stale link
// never dead-ends.
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mountSuspended } from '@nuxt/test-utils/runtime'
import { flushPromises } from '@vue/test-utils'

const { ref } = require('vue') as typeof import('vue')

const { listMock, removeMock, schemaRef } = vi.hoisted(() => {
  const { ref: hoistedRef } = require('vue') as typeof import('vue')
  return {
    listMock: vi.fn(),
    removeMock: vi.fn(),
    schemaRef: hoistedRef<Record<string, unknown> | null>(null),
  }
})

vi.mock('~/composables/useAdmin', () => ({
  useAdmin: () => ({ hasCapability: () => true, getEntity: () => null }),
}))

vi.mock('~/composables/useAdminConfig', () => ({
  useAdminConfig: () => ({ enableRealtime: false }),
}))

vi.mock('~/composables/useRealtime', () => ({
  useRealtime: () => ({
    messages: ref([]),
    connected: ref(false),
    error: ref(null),
    connect: vi.fn(),
    disconnect: vi.fn(),
    reconnect: vi.fn(),
  }),
}))

vi.mock('~/composables/useLanguage', () => ({
  useLanguage: () => ({ t: (key: string) => key, entityLabel: (_t: string, fb: string) => fb }),
}))

vi.mock('~/composables/useSchema', () => ({
  useSchema: () => ({
    schema: schemaRef,
    loading: ref(false),
    fetch: vi.fn().mockResolvedValue(undefined),
    sortedProperties: () => [['title', { 'x-widget': 'text', 'x-label': 'Title' }]],
  }),
}))

vi.mock('~/composables/useEntity', () => ({
  useEntity: () => ({ list: listMock, remove: removeMock }),
}))

const NuxtLinkStub = { props: ['to'], template: '<a :href="to"><slot /></a>' }

beforeEach(() => {
  listMock.mockReset()
  listMock.mockResolvedValue({ data: [], meta: { total: 0 } })
  removeMock.mockReset()
  schemaRef.value = {
    title: 'Content',
    'x-bundle-key': 'type',
    properties: {
      type: { type: 'string', enum: ['page', 'post', 'job_posting'], 'x-widget': 'select' },
      title: { type: 'string', 'x-widget': 'text', 'x-label': 'Title' },
    },
  }
})

async function mountList(initialBundle?: string) {
  const { default: SchemaList } = await import('~/components/schema/SchemaList.vue')
  const wrapper = await mountSuspended(SchemaList, {
    props: { entityType: 'node', initialBundle },
    global: { stubs: { NuxtLink: NuxtLinkStub } },
  })
  await flushPromises()
  return wrapper
}

function lastListQuery() {
  return listMock.mock.calls.at(-1)?.[1] ?? {}
}

describe('SchemaList bundle scope', () => {
  it('applies a requested bundle as a list filter', async () => {
    await mountList('post')

    expect(lastListQuery().filter).toMatchObject({
      type: { operator: 'EQUALS', value: 'post' },
    })
  })

  it('preselects the bundle control so the scope is visible and reversible', async () => {
    const wrapper = await mountList('job_posting')
    const select = wrapper.find('select')

    expect(select.exists()).toBe(true)
    expect((select.element as HTMLSelectElement).value).toBe('job_posting')
  })

  it('lists unscoped when no bundle is requested', async () => {
    await mountList()

    expect(lastListQuery().filter).toBeUndefined()
  })

  it('degrades to the unscoped listing for a bundle the schema does not advertise', async () => {
    await mountList('not_a_bundle')

    expect(lastListQuery().filter).toBeUndefined()
  })

  it('degrades to the unscoped listing when the entity type is not bundle-shaped', async () => {
    schemaRef.value = { title: 'User', properties: { title: { type: 'string', 'x-widget': 'text' } } }

    await mountList('post')

    expect(lastListQuery().filter).toBeUndefined()
  })
})
