// A create form must not chase a bundle the schema does not advertise (#2418).
//
// Bundle-scoped create destinations are generated by
// Waaseyaa\AdminSurface\AdminDestinationPaths (#2420), and a link can go stale
// or be hand-edited. An unknown value must degrade to the unscoped create form
// rather than issuing a scoped schema request that will be refused.
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mountSuspended, registerEndpoint } from '@nuxt/test-utils/runtime'
import { flushPromises } from '@vue/test-utils'
import { readBody } from 'h3'

const discoverySchema = {
  $schema: 'https://json-schema.org/draft-07/schema#',
  title: 'Content',
  description: 'Content schema',
  type: 'object',
  'x-entity-type': 'node',
  'x-translatable': false,
  'x-revisionable': true,
  'x-bundle-key': 'type',
  properties: {
    type: {
      type: 'string',
      enum: ['page', 'post'],
      'x-widget': 'select',
      'x-label': 'Bundle',
      'x-required': true,
      'x-weight': -100,
    },
    title: { type: 'string', 'x-widget': 'text', 'x-label': 'Title' },
  },
  required: ['type', 'title'],
}

const pageSchema = {
  ...discoverySchema,
  title: 'Page',
  properties: {
    ...discoverySchema.properties,
    page_summary: { type: 'string', 'x-widget': 'textarea', 'x-label': 'Page summary', 'x-weight': 10 },
  },
}

// An entity type whose schema advertises no bundle enum at all.
const unbundledSchema = {
  ...discoverySchema,
  'x-entity-type': 'node_no_enum',
  properties: {
    type: { type: 'string', 'x-widget': 'text', 'x-label': 'Bundle' },
    title: { type: 'string', 'x-widget': 'text', 'x-label': 'Title' },
  },
}

const scopedPayloads: Record<string, Array<Record<string, unknown>>> = {}

function recordEndpoint(entityType: string, base: object, scoped: object) {
  scopedPayloads[entityType] = []
  registerEndpoint(`/admin/_surface/${entityType}/action/schema`, {
    method: 'POST',
    handler: async (event) => {
      const payload = (await readBody(event)) ?? {}
      scopedPayloads[entityType]!.push(payload)
      return { ok: true, data: payload.bundle ? scoped : base }
    },
  })
}

recordEndpoint('node_known_bundle', discoverySchema, pageSchema)
recordEndpoint('node_unknown_bundle', discoverySchema, pageSchema)
recordEndpoint('node_no_enum', unbundledSchema, unbundledSchema)

async function mountForm(entityType: string, initialBundle: string) {
  const { default: SchemaForm } = await import('~/components/schema/SchemaForm.vue')
  const wrapper = await mountSuspended(SchemaForm, { props: { entityType, initialBundle } })
  await flushPromises()
  await vi.waitFor(() => expect(wrapper.find('.loading').exists()).toBe(false))
  return wrapper
}

describe('SchemaForm bundle scope', () => {
  beforeEach(() => {
    for (const key of Object.keys(scopedPayloads)) scopedPayloads[key] = []
  })

  it('scopes the form to a bundle the schema advertises', async () => {
    const wrapper = await mountForm('node_known_bundle', 'page')

    expect(scopedPayloads.node_known_bundle).toEqual([{}, { bundle: 'page' }])
    expect((wrapper.get('select').element as HTMLSelectElement).value).toBe('page')
    expect(wrapper.text()).toContain('Page summary')
  })

  it('ignores a bundle the schema does not advertise, without a scoped request', async () => {
    const wrapper = await mountForm('node_unknown_bundle', 'not_a_bundle')

    expect(scopedPayloads.node_unknown_bundle).toEqual([{}])
    expect(wrapper.text()).not.toContain('Page summary')
    expect((wrapper.get('select').element as HTMLSelectElement).value).toBe('')
  })

  it('still honours a requested bundle when the schema advertises no enum', async () => {
    await mountForm('node_no_enum', 'anything')

    expect(scopedPayloads.node_no_enum).toEqual([{}, { bundle: 'anything' }])
  })
})
