<?php

declare(strict_types=1);

namespace Waaseyaa\Audit\Tests\Unit\Writer;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Waaseyaa\Audit\Contract\AuditEventDescriptor;
use Waaseyaa\Audit\Contract\AuditWriterInterface;
use Waaseyaa\Audit\Enum\AuditEventKind;
use Waaseyaa\Audit\Schema\AuditEventSchemaHandler;
use Waaseyaa\Audit\Storage\AppendOnlyAuditDatabase;
use Waaseyaa\Audit\Writer\AuditEventWriter;
use Waaseyaa\Database\DBALDatabase;

#[CoversClass(AuditEventWriter::class)]
final class AuditEventWriterTest extends TestCase
{
    #[Test]
    public function it_appends_a_descriptor_to_the_audit_log(): void
    {
        $inner = DBALDatabase::createSqlite();
        new AuditEventSchemaHandler($inner)->ensureSchema();
        $writer = new AuditEventWriter(new AppendOnlyAuditDatabase($inner));

        $writer->record(new AuditEventDescriptor(
            kind: AuditEventKind::EntityWrite,
            accountUid: 1,
            subjectUri: '/entities/note/abc-123',
            outcome: 'allowed',
            severity: 'info',
        ));

        $rows = [];
        foreach ($inner->select('audit_event', 'ae')->fields('ae')->execute() as $row) {
            $rows[] = (array) $row;
        }

        $this->assertCount(1, $rows);
        $this->assertSame(AuditEventKind::EntityWrite->value, $rows[0]['event_kind']);
        $this->assertSame(1, (int) $rows[0]['account_uid']);
        $this->assertSame('/entities/note/abc-123', $rows[0]['subject_uri']);
        // Non-entity events coalesce null → '' (NOT NULL empty-sentinel design).
        $this->assertSame('', $rows[0]['entity_type_id']);
        $this->assertSame('', $rows[0]['entity_uuid']);
        // uuid is generated by the writer (RFC-4122).
        $this->assertNotSame('', (string) $rows[0]['uuid']);
    }

    #[Test]
    public function it_implements_audit_writer_interface(): void
    {
        $writer = new AuditEventWriter(new AppendOnlyAuditDatabase(DBALDatabase::createSqlite()));

        $this->assertInstanceOf(AuditWriterInterface::class, $writer);
    }
}
