<?php

declare(strict_types=1);

namespace Waaseyaa\Audit\Tests\Unit\Writer;

use Waaseyaa\Tests\Support\RuntimeSchemaMigrations;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Waaseyaa\Audit\Contract\AuditEventDescriptor;
use Waaseyaa\Audit\Contract\AuditWriterInterface;
use Waaseyaa\Audit\Enum\AuditEventKind;
use Waaseyaa\Audit\Schema\AuditEventSchemaHandler;
use Waaseyaa\Audit\Storage\AppendOnlyAuditDatabase;
use Waaseyaa\Audit\Writer\AuditEventWriter;
use Waaseyaa\Database\DBALDatabase;

#[CoversClass(AuditEventWriter::class)]
final class AuditEventWriterTest extends TestCase
{
    #[Test]
    public function it_appends_a_descriptor_to_the_audit_log(): void
    {
        $inner = DBALDatabase::createSqlite();
        RuntimeSchemaMigrations::audit($inner);
        $writer = new AuditEventWriter(new AppendOnlyAuditDatabase($inner));

        $writer->record(new AuditEventDescriptor(
            kind: AuditEventKind::EntityWrite,
            accountUid: 1,
            subjectUri: '/entities/note/abc-123',
            outcome: 'allowed',
            severity: 'info',
        ));

        $rows = [];
        foreach ($inner->select('audit_event', 'ae')->fields('ae')->execute() as $row) {
            $rows[] = (array) $row;
        }

        $this->assertCount(1, $rows);
        $this->assertSame(AuditEventKind::EntityWrite->value, $rows[0]['event_kind']);
        $this->assertSame(1, (int) $rows[0]['account_uid']);
        $this->assertSame('/entities/note/abc-123', $rows[0]['subject_uri']);
        // Non-entity events coalesce null → '' (NOT NULL empty-sentinel design).
        $this->assertSame('', $rows[0]['entity_type_id']);
        $this->assertSame('', $rows[0]['entity_uuid']);
        // uuid is generated by the writer (RFC-4122).
        $this->assertNotSame('', (string) $rows[0]['uuid']);
    }

    #[Test]
    public function it_implements_audit_writer_interface(): void
    {
        $writer = new AuditEventWriter(new AppendOnlyAuditDatabase(DBALDatabase::createSqlite()));

        $this->assertInstanceOf(AuditWriterInterface::class, $writer);
    }

    // ------------------------------------------------------------------
    // Dual-column actor mapping (FR-004, contract clauses 1–2):
    // actor_uid = descriptor actor verbatim (null preserved as SQL NULL);
    // account_uid = actor ?? 0 (legacy sentinel unchanged).
    // ------------------------------------------------------------------

    /**
     * @return array{DBALDatabase, AuditEventWriter}
     */
    private function writerOnFreshSchema(): array
    {
        $inner = DBALDatabase::createSqlite();
        RuntimeSchemaMigrations::audit($inner);

        return [$inner, new AuditEventWriter(new AppendOnlyAuditDatabase($inner))];
    }

    /**
     * @return array<string, mixed>
     */
    private function singleRow(DBALDatabase $inner): array
    {
        $rows = [];
        foreach ($inner->query('SELECT actor_uid, account_uid FROM audit_event') as $row) {
            $rows[] = (array) $row;
        }
        $this->assertCount(1, $rows);

        return $rows[0];
    }

    private function descriptorWithActor(?int $actor): AuditEventDescriptor
    {
        return new AuditEventDescriptor(
            kind: AuditEventKind::EntityWrite,
            accountUid: $actor,
            subjectUri: '/entities/note/abc-123',
            outcome: 'allowed',
            severity: 'info',
        );
    }

    #[Test]
    public function a_null_actor_is_written_as_sql_null_with_legacy_account_uid_zero(): void
    {
        [$inner, $writer] = $this->writerOnFreshSchema();

        $writer->record($this->descriptorWithActor(null));

        // The null-vs-0 distinctness witness, straight off the table: SAME
        // row, actor_uid IS NULL while account_uid = 0.
        $row = $this->singleRow($inner);
        $this->assertNull($row['actor_uid'], 'No acting context must persist as SQL NULL, not 0');
        $this->assertSame(0, (int) $row['account_uid']);
    }

    #[Test]
    public function an_anonymous_zero_actor_is_written_as_zero_in_both_columns(): void
    {
        [$inner, $writer] = $this->writerOnFreshSchema();

        $writer->record($this->descriptorWithActor(0));

        $row = $this->singleRow($inner);
        $this->assertSame(0, (int) $row['actor_uid'], 'Anonymous actor is a real 0 — distinct from NULL');
        $this->assertNotNull($row['actor_uid']);
        $this->assertSame(0, (int) $row['account_uid']);
    }

    #[Test]
    public function an_account_actor_is_written_verbatim_to_both_columns(): void
    {
        [$inner, $writer] = $this->writerOnFreshSchema();

        $writer->record($this->descriptorWithActor(7));

        $row = $this->singleRow($inner);
        $this->assertSame(7, (int) $row['actor_uid']);
        $this->assertSame(7, (int) $row['account_uid']);
    }

    #[Test]
    public function existing_int_passing_descriptor_constructions_still_compile_and_behave(): void
    {
        // Clause 3: the int → ?int widening is parameter-compatible — a plain
        // int keeps flowing through unchanged.
        $descriptor = new AuditEventDescriptor(
            kind: AuditEventKind::EntityWrite,
            accountUid: 1,
            subjectUri: '/entities/note/abc-123',
            outcome: 'allowed',
            severity: 'info',
        );

        $this->assertSame(1, $descriptor->accountUid);
    }
}
