<?php

declare(strict_types=1);

namespace App\Entity\Enum;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand.
 */
enum ArticleStage: string
{
    case Draft = 'draft';
    case Final = 'final';
}
