<?php

declare(strict_types=1);

// Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
// One row per blueprint relationship. Consumed by the generated application
// blueprint provider for referential integrity; do not edit by hand.
return [
    'article_author' => [
        'from_entity' => 'article',
        'from_field' => 'author',
        'to_entity' => 'person',
        'cardinality' => 1,
        'required' => true,
        'on_delete' => 'nullify',
    ],
];
