<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Access\EntityAccessHandler;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Every blueprint entity must deny an anonymous and a
 * permission-less authenticated principal on every operation: no policy grants
 * by default, so absence of a matching condition must never leak into an
 * accidental Allowed. Also asserts the three companion invariants decision (i)
 * assigns to this class: no emitted role is ever `administrator`, every
 * permission a role/transition/policy references is a declared
 * `ApplicationBlueprintPermissions` constant, and every entity with a
 * declared policy has a REFLECTABLE `#[PolicyAttribute]` class (the gap that
 * let a policy compile correctly yet never be discovered at boot — #2788
 * review F1).
 */
final class GovernanceDefaultDenyTest extends TestCase
{

    public function testArticleIsDeniedByDefault(): void
    {
        $handler = new EntityAccessHandler([]);
        $subject = new \App\Entity\Article(['id' => 1]);

        foreach ([AuthorizationPrincipalFactory::anonymous(), AuthorizationPrincipalFactory::authenticated(1)] as $account) {
            self::assertFalse($handler->check($subject, 'view', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'update', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'delete', $account)->isAllowed());
            self::assertFalse($handler->checkCreateAccess('article', 'article', $account)->isAllowed());
        }
    }
}
