<?php

declare(strict_types=1);

namespace Waaseyaa\Tests\Architecture;

use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Yaml\Yaml;

/**
 * Binds the Dependabot admin-dist rebuild's trust boundaries (#2704).
 *
 * The workflow runs three jobs, and the split between them is the security
 * property — not an accident of layout:
 *
 *   build     contents: read   generates the bundle; dependency code executes here
 *   validate  contents: read   re-runs acceptance independently, on a clean workspace
 *   publish   contents: write  commits the checked bundle; runs no interpreter
 *
 * `validate` ADDS independence; it does not relocate the only check.
 * bin/build-admin-dist already ends by running bin/check-admin-dist-fresh and
 * bin/admin-dist-acceptance verify against the tree it just produced, and
 * `build` still does exactly that. The problem is not that `build` fails to
 * check — it is that its check shares a disk with the bundler, so the result
 * cannot stand alone. `validate` re-runs the same acceptance check where the
 * outcome does not depend on that workspace.
 *
 * Two distinct failures are held closed here.
 *
 * The first is the one that broke: `publish` sets up no PHP by design, yet it
 * ran `php bin/admin-dist-acceptance verify`, so it executed the runner's
 * default interpreter. That script uses PHP 8.4+ "new without parentheses"
 * syntax, so it died with a parse error before the commit step and left a
 * stale packages/admin-surface/dist on every Dependabot admin bump. The fix is
 * not "set up PHP in publish" — that would run a third-party action inside the
 * write-capable boundary — so the pinned interpreter lives in an unprivileged
 * job instead.
 *
 * The second is why the independent gate is not in `build`.
 * `bin/build-admin-dist` installs with `npm ci --ignore-scripts`, so
 * install-time lifecycle hooks are NOT the
 * exposure; the exposure is `npm run generate`, where the bundler imports and
 * executes dependency modules in-process to produce the SPA. Dependency code
 * therefore executes in `build`'s workspace, and a verifier sitting on that
 * disk afterwards is potentially attacker-controlled — so `build`'s own verify
 * is a useful early failure but not self-standing evidence. `validate` obtains
 * the verifier separately, completes its toolchain before any generated byte
 * lands, and then treats the artifact strictly as data.
 *
 * Two things this file asserts are deliberately NOT framed as vulnerability
 * fixes, because they are not. The head-sha pin buys identity, not trust: it
 * makes the revision unambiguous and reproducible and keeps all three jobs on
 * one commit, which is what stops the bundle being judged against a different
 * revision's dist.markers.json. And the artifact digest strengthens a binding
 * rather than closing a hole — same-run download-by-name already resolves to
 * this run's artifact; the digest makes `publish`'s claim to hold the verified
 * bytes independent of resolution semantics, and assertable here.
 *
 * AUDITED, UNAFFECTED: .github/workflows/admin-dist.yml (the main-branch
 * rebuild) is not the same shape and does not need to be. It triggers on
 * `push` to main, so its input is code that is already merged rather than an
 * untrusted PR head, and its single `build-and-publish` job pins
 * shivammathur/setup-php @ 8.5 itself — so its `php bin/...` invocations never
 * fell back to a runner default and it never had the #2704 bug. The last test
 * here holds that pin in place. Extending the build/validate/publish split to
 * it is deliberately out of scope for #2704.
 */
#[CoversNothing]
final class AdminDistWorkflowInterpreterBoundaryTest extends TestCase
{
    private const WORKFLOW = '/.github/workflows/dependabot-admin-dist.yml';

    private const SETUP_PHP = 'shivammathur/setup-php';

    private const HEAD_SHA_REF = '${{ github.event.pull_request.head.sha }}';

    /**
     * Third-party actions the privileged `publish` job is permitted to use.
     * Everything else — setup-php included — must stay in an unprivileged job.
     */
    private const PUBLISH_ALLOWED_ACTIONS = [
        'actions/checkout',
        'actions/download-artifact',
    ];

    /** @var array<string, mixed> */
    private array $workflow;

    protected function setUp(): void
    {
        $parsed = Yaml::parseFile(dirname(__DIR__, 2) . self::WORKFLOW);
        self::assertIsArray($parsed);
        $this->workflow = $parsed;
    }

    #[Test]
    public function the_job_graph_gates_every_write_behind_two_unprivileged_jobs(): void
    {
        self::assertSame(['build', 'validate', 'publish'], array_keys($this->workflow['jobs']));

        self::assertSame(['contents' => 'read'], $this->workflow['jobs']['build']['permissions']);
        self::assertSame(['contents' => 'read'], $this->workflow['jobs']['validate']['permissions']);
        self::assertSame(
            ['contents' => 'write', 'actions' => 'write'],
            $this->workflow['jobs']['publish']['permissions'],
        );

        self::assertSame('build', $this->workflow['jobs']['validate']['needs'] ?? null);
        self::assertSame(
            ['build', 'validate'],
            $this->workflow['jobs']['publish']['needs'] ?? null,
            'publish must depend on validate, so a failed verification can never reach a write.',
        );

        // The write-capable job carries the actor and same-repository
        // condition itself rather than inheriting it through `needs` alone,
        // and it must NARROW that gating rather than replace it.
        $publishIf = $this->workflow['jobs']['publish']['if'] ?? null;
        self::assertIsString($publishIf, 'publish must carry its own Dependabot condition.');
        self::assertSame(
            $this->workflow['jobs']['build']['if'] ?? null,
            $publishIf,
            'publish must gate on the same actor and same-repository condition as build.',
        );
        self::assertStringContainsString("github.actor == 'dependabot[bot]'", $publishIf);
        self::assertStringContainsString(
            'github.event.pull_request.head.repo.full_name == github.repository',
            $publishIf,
        );

        // A job `if` is evaluated in addition to the implicit success() over
        // `needs` — but only while it contains no status function. always(),
        // failure() or cancelled() would override that and let a write follow
        // a failed or skipped verification.
        self::assertDoesNotMatchRegularExpression(
            '/\b(always|failure|cancelled)\s*\(/',
            $publishIf,
            'publish must not use a status function; that would neutralise the success() '
            . 'requirement over needs and let a write follow a failed verification.',
        );

        // Every job checks out the revision under review, not the default
        // pull_request_target base branch, and none of them keeps a token in
        // .git/config.
        foreach (['build', 'validate', 'publish'] as $job) {
            $steps = $this->steps($job);
            $checkout = $this->indexOfActionStep($steps, 'actions/checkout');
            self::assertNotNull($checkout, $job);
            self::assertSame(self::HEAD_SHA_REF, $steps[$checkout]['with']['ref'] ?? null, $job);
            self::assertFalse($steps[$checkout]['with']['persist-credentials'] ?? true, $job);
        }
    }

    #[Test]
    public function verification_runs_on_a_pinned_interpreter_in_a_job_that_never_ran_the_bundler(): void
    {
        $steps = $this->steps('validate');

        $verifyIndex = $this->indexOfRunStep($steps, 'bin/admin-dist-acceptance verify');
        self::assertNotNull(
            $verifyIndex,
            'The validate job must run `php bin/admin-dist-acceptance verify`.',
        );

        $setupPhpIndex = $this->indexOfActionStep($steps, self::SETUP_PHP);
        self::assertNotNull($setupPhpIndex, 'The verifying job must set up PHP.');
        self::assertSame(
            '8.5',
            $steps[$setupPhpIndex]['with']['php-version'] ?? null,
            'The verifying job must pin PHP 8.5 — the acceptance script needs 8.4+ syntax.',
        );
        self::assertLessThan($verifyIndex, $setupPhpIndex);

        // No bundler, no dependency code: this job must not set up Node or
        // shell out to npm/node/npx at all, or it reacquires the exposure it
        // exists to escape.
        self::assertNull(
            $this->indexOfActionStep($steps, 'actions/setup-node'),
            'The verifying job must not set up Node.',
        );
        foreach ($steps as $step) {
            if (!is_string($step['run'] ?? null)) {
                continue;
            }
            self::assertDoesNotMatchRegularExpression(
                '/(?<![\w\/-])(npm|npx|node)\b/',
                $step['run'],
                sprintf(
                    'Step "%s" runs the JavaScript toolchain inside the verifying job. Dependency '
                    . 'code must not execute where the verifier lives (#2704).',
                    $step['name'] ?? '(unnamed)',
                ),
            );
        }

        // Any Composer bootstrap here must refuse scripts and plugins, which
        // execute code, and must complete before untrusted bytes arrive.
        $installIndex = $this->indexOfRunStep($steps, 'composer install');
        self::assertNotNull($installIndex, 'bin/admin-dist-acceptance needs vendor/autoload.php.');
        self::assertStringContainsString('--no-scripts --no-plugins', (string) $steps[$installIndex]['run']);

        $checkoutIndex = $this->indexOfActionStep($steps, 'actions/checkout');
        $downloadIndex = $this->indexOfActionStep($steps, 'actions/download-artifact');
        self::assertNotNull($checkoutIndex);
        self::assertNotNull($downloadIndex);
        self::assertLessThan(
            $installIndex,
            $checkoutIndex,
            'The verifier must come from git before it is bootstrapped.',
        );
        self::assertLessThan(
            $downloadIndex,
            $installIndex,
            'The trusted toolchain must be complete before any generated byte lands on this disk.',
        );
        self::assertLessThan($verifyIndex, $downloadIndex);
    }

    #[Test]
    public function the_build_job_generates_and_uploads_exactly_what_the_gate_reads(): void
    {
        $steps = $this->steps('build');

        // build runs the canonical rebuild, which performs its own acceptance
        // checks internally (bin/build-admin-dist ends with
        // check-admin-dist-fresh + admin-dist-acceptance verify). Those are
        // retained. This asserts only that the workflow does not ALSO bolt a
        // separate acceptance step onto this job: the independent gate belongs
        // in `validate`, where its result does not depend on the workspace the
        // bundler ran in.
        self::assertNotNull($this->indexOfRunStep($steps, 'bin/build-admin-dist'));
        self::assertNull(
            $this->indexOfRunStep($steps, 'bin/admin-dist-acceptance'),
            'The independent acceptance gate belongs in validate, not as an extra step here (#2704).',
        );

        // What is uploaded is exactly what the verifier reads back.
        $uploadIndex = $this->indexOfActionStep($steps, 'actions/upload-artifact');
        self::assertNotNull($uploadIndex);
        self::assertSame(
            [
                'packages/admin-surface/dist',
                'packages/admin-surface/dist.signature',
                'packages/admin-surface/dist.manifest.json',
            ],
            $this->lines((string) ($steps[$uploadIndex]['with']['path'] ?? '')),
        );
        self::assertSame('error', $steps[$uploadIndex]['with']['if-no-files-found'] ?? null);
    }

    #[Test]
    public function the_artifact_is_confined_and_placed_before_it_is_verified(): void
    {
        // Ordering is the whole point: a verify that runs before the artifact
        // is confined and placed reads the committed dist from the checkout,
        // passes, and proves nothing about the bytes that will be published.
        $steps = $this->steps('validate');

        $placeIndex = $this->indexOfRunStep($steps, 'cp -a "$ARTIFACT_ROOT/dist"');
        $verifyIndex = $this->indexOfRunStep($steps, 'bin/admin-dist-acceptance verify');
        self::assertNotNull($placeIndex);
        self::assertNotNull($verifyIndex);
        self::assertLessThan(
            $verifyIndex,
            $placeIndex,
            'The generated bytes must be confined and placed BEFORE verification runs, or the '
            . 'gate inspects the committed dist instead of the rebuilt one.',
        );

        // And the confinement must precede the placement within that step.
        $script = (string) $steps[$placeIndex]['run'];
        $allowlistAt = strpos($script, "= 'dist dist.manifest.json dist.signature '");
        $copyAt = strpos($script, 'cp -a "$ARTIFACT_ROOT/dist"');
        self::assertIsInt($allowlistAt);
        self::assertIsInt($copyAt);
        self::assertLessThan($copyAt, $allowlistAt);
    }

    #[Test]
    public function verification_cannot_be_skipped_and_its_failure_cannot_be_ignored(): void
    {
        $steps = $this->steps('validate');
        $verifyIndex = $this->indexOfRunStep($steps, 'bin/admin-dist-acceptance verify');
        self::assertNotNull($verifyIndex);
        $verify = $steps[$verifyIndex];

        self::assertArrayNotHasKey(
            'continue-on-error',
            $verify,
            'continue-on-error would let the job succeed with a failed acceptance check.',
        );
        self::assertArrayNotHasKey(
            'if',
            $verify,
            'A condition on the verify step could skip verification and still satisfy publish.',
        );

        // Nothing inside the run block may swallow the exit status either.
        $script = (string) $verify['run'];
        self::assertDoesNotMatchRegularExpression(
            '/\|\||;\s*(true|:)\s*$|\bset\s+\+e\b|\bexit\s+0\b/m',
            $script,
            'The verify step must not swallow its exit status.',
        );

        // The job must also not be made optional from above.
        self::assertArrayNotHasKey('continue-on-error', $this->workflow['jobs']['validate']);
    }

    #[Test]
    public function the_write_capable_job_invokes_no_php_or_composer_and_no_extra_third_party_action(): void
    {
        foreach ($this->steps('publish') as $step) {
            $run = $step['run'] ?? null;
            if (is_string($run)) {
                self::assertDoesNotMatchRegularExpression(
                    '/(?<![\w\/-])(php|composer)\b/',
                    $run,
                    sprintf(
                        'Step "%s" invokes a PHP/Composer binary inside the write-capable boundary. '
                        . 'That job sets up no interpreter by design (#2704) — move the work to an '
                        . 'unprivileged job instead of adding setup-php here.',
                        $step['name'] ?? '(unnamed)',
                    ),
                );
            }

            $uses = $step['uses'] ?? null;
            if (!is_string($uses)) {
                continue;
            }
            $action = explode('@', $uses)[0];
            self::assertContains(
                $action,
                self::PUBLISH_ALLOWED_ACTIONS,
                sprintf(
                    'Action "%s" would execute third-party code inside the write-capable boundary. '
                    . 'The build/validate/publish separation is the security property this workflow '
                    . 'exists to keep (#2704).',
                    $action,
                ),
            );
        }
    }

    #[Test]
    public function publish_installs_the_same_artifact_validate_blessed(): void
    {
        // Name-based download within a run already resolves to this run's
        // artifact, so this is a strengthened binding rather than a fix for a
        // hole: the identity is carried out-of-band as a job output and
        // re-derived before any copy, which makes publish's claim to hold the
        // verified bytes independent of resolution semantics — and assertable.
        self::assertSame(
            '${{ steps.confine.outputs.artifact-digest }}',
            $this->workflow['jobs']['validate']['outputs']['artifact-digest'] ?? null,
        );

        $validateSteps = $this->steps('validate');
        $confineIndex = $this->indexOfRunStep($validateSteps, 'artifact-digest=');
        self::assertNotNull($confineIndex);
        self::assertSame('confine', $validateSteps[$confineIndex]['id'] ?? null);
        self::assertStringContainsString(
            'echo "artifact-digest=$ARTIFACT_DIGEST" >> "$GITHUB_OUTPUT"',
            (string) $validateSteps[$confineIndex]['run'],
        );

        $publishSteps = $this->steps('publish');
        $installIndex = $this->indexOfRunStep($publishSteps, 'cp -a "$ARTIFACT_ROOT/dist"');
        self::assertNotNull($installIndex);
        $install = $publishSteps[$installIndex];
        self::assertSame(
            '${{ needs.validate.outputs.artifact-digest }}',
            $install['env']['VALIDATED_DIGEST'] ?? null,
            'publish must consume the digest validate published, binding it to those exact bytes.',
        );
        self::assertStringContainsString(
            'if [ "$ARTIFACT_DIGEST" != "$VALIDATED_DIGEST" ]; then',
            (string) $install['run'],
        );
        // Fails closed: a missing output must abort rather than compare empty
        // against empty.
        self::assertStringContainsString('if [ -z "$VALIDATED_DIGEST" ]; then', (string) $install['run']);

        // Both jobs must derive the digest the same way, or the comparison is
        // theatre.
        $derivation = 'ARTIFACT_DIGEST="$(cd "$ARTIFACT_ROOT" && find . -type f -print0 '
            . '| LC_ALL=C sort -z | xargs -0 -r sha256sum | sha256sum | cut -d \' \' -f 1)"';
        self::assertStringContainsString($derivation, (string) $validateSteps[$confineIndex]['run']);
        self::assertStringContainsString($derivation, (string) $install['run']);
    }

    #[Test]
    public function every_consumer_confines_the_untrusted_artifact_to_the_three_intended_paths(): void
    {
        // The artifact is untrusted data on both consuming sides. Each must
        // refuse an unexpected entry name and any non-regular filesystem entry
        // BEFORE `cp -a` runs, or a hostile artifact could write outside the
        // three paths it is allowed to occupy.
        foreach (['validate', 'publish'] as $job) {
            $steps = $this->steps($job);
            $index = $this->indexOfRunStep($steps, 'cp -a "$ARTIFACT_ROOT/dist"');
            self::assertNotNull($index, $job);
            $script = (string) $steps[$index]['run'];

            self::assertStringContainsString("= 'dist dist.manifest.json dist.signature '", $script, $job);
            self::assertStringContainsString('! -type d ! -type f -print -quit', $script, $job);
            self::assertStringContainsString("grep -Eq '^[0-9a-f]{64}\$'", $script, $job);

            $allowlistAt = strpos($script, "= 'dist dist.manifest.json dist.signature '");
            $copyAt = strpos($script, 'cp -a "$ARTIFACT_ROOT/dist"');
            self::assertIsInt($allowlistAt);
            self::assertIsInt($copyAt);
            self::assertLessThan($copyAt, $allowlistAt, $job);
        }

        // Only publish writes anything back, and it still does.
        $publishSteps = $this->steps('publish');
        $commit = $this->indexOfRunStep($publishSteps, 'git commit -m');
        self::assertNotNull($commit, 'The privileged job must still commit the rebuilt dist.');
        self::assertNull(
            $this->indexOfRunStep($this->steps('validate'), 'git commit'),
            'The verifying job must not write anything back.',
        );
    }

    #[Test]
    public function the_main_branch_admin_dist_rebuild_pins_its_own_interpreter(): void
    {
        // Audited alongside #2704: admin-dist.yml has one job, and that job
        // pins setup-php @ 8.5, so its `php bin/...` invocations never fall
        // back to the runner default. It triggers on push to main rather than
        // on an untrusted PR head, so the three-job split is not what it
        // needs; the pin is.
        $parsed = Yaml::parseFile(dirname(__DIR__, 2) . '/.github/workflows/admin-dist.yml');
        self::assertIsArray($parsed);
        self::assertSame(['build-and-publish'], array_keys($parsed['jobs']));
        self::assertSame(['main'], $parsed['on']['push']['branches'] ?? null);

        $steps = $parsed['jobs']['build-and-publish']['steps'];
        $setupPhpIndex = $this->indexOfActionStep($steps, self::SETUP_PHP);
        self::assertNotNull($setupPhpIndex);
        self::assertSame('8.5', $steps[$setupPhpIndex]['with']['php-version'] ?? null);
    }

    /** @return list<string> */
    private function lines(string $block): array
    {
        return array_values(array_filter(
            array_map(trim(...), explode("\n", $block)),
            static fn(string $line): bool => $line !== '',
        ));
    }

    /** @return list<array<string, mixed>> */
    private function steps(string $job): array
    {
        $steps = $this->workflow['jobs'][$job]['steps'] ?? null;
        self::assertIsArray($steps, sprintf('Workflow job "%s" is missing.', $job));

        return array_values($steps);
    }

    /** @param list<array<string, mixed>> $steps */
    private function indexOfRunStep(array $steps, string $needle): ?int
    {
        foreach ($steps as $index => $step) {
            if (is_string($step['run'] ?? null) && str_contains($step['run'], $needle)) {
                return $index;
            }
        }

        return null;
    }

    /** @param list<array<string, mixed>> $steps */
    private function indexOfActionStep(array $steps, string $action): ?int
    {
        foreach ($steps as $index => $step) {
            if (is_string($step['uses'] ?? null) && str_starts_with($step['uses'], $action . '@')) {
                return $index;
            }
        }

        return null;
    }
}
