<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Command\Migration;

use Waaseyaa\Entity\EntityTypeInterface;

/**
 * Emits a PHP migration file for the sql-column storage backend.
 *
 * The emitted file is a `return new class extends Migration` anonymous class
 * (matching the project's existing migration convention) with `up()` and
 * `down()` methods. The `up()` step creates the new typed-column table and
 * backfills data from the legacy `_data` blob column. The `down()` step is
 * intentionally left as a no-op with a comment explaining why (SQLite
 * does not support DROP COLUMN on older versions; callers should handle
 * reversal manually for production databases).
 *
 * @api
 */
final class StorageMigrationTemplate
{
    /**
     * Render the migration file content for the given entity type and column map.
     *
     * @param EntityTypeInterface  $entityType  Entity type being migrated.
     * @param array<string, string> $columnMap  field name => SQL column type string.
     * @param string               $entityTable The SQL table name for the entity type.
     *
     * @api
     */
    public function render(
        EntityTypeInterface $entityType,
        array $columnMap,
        string $entityTable,
    ): string {
        $entityTypeId = $entityType->id();
        $timestamp = date('Y_m_d_His');

        // $entityTypeId/$entityTable are expected to already be machine names
        // (the make:content-type / make:entity-type boundary now enforces
        // that allowlist), but escape them anyway before they land in
        // generated PHP — a raw entity type id could otherwise terminate the
        // docblock comment below via `*/`, and a raw table name could break
        // out of the single-quoted literals used further down.
        $entityTypeIdComment = str_replace('*/', '* /', $entityTypeId);
        $escapedEntityTable = addslashes($entityTable);

        $columnLines = [];
        foreach ($columnMap as $field => $sqlType) {
            $escapedField = addslashes($field);
            $escapedType = addslashes($sqlType);
            $columnLines[] = '            $conn->executeStatement(sprintf(';
            $columnLines[] = "                'ALTER TABLE %s ADD COLUMN {$escapedField} {$escapedType}',";
            $columnLines[] = "                \$conn->quoteIdentifier('{$escapedEntityTable}'),";
            $columnLines[] = '            ));';
        }

        $addColumnsPhp = implode("\n", $columnLines);

        $backfillFieldsList = array_keys($columnMap);
        $backfillJson = json_encode($backfillFieldsList, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Doctrine\DBAL\Connection;
            use Waaseyaa\CLI\Command\Migration\BackfillHelper;
            use Waaseyaa\Foundation\Migration\Migration;
            use Waaseyaa\Foundation\Migration\SchemaBuilder;

            /**
             * Migrate `{$entityTypeIdComment}` entity from sql-blob to sql-column.
             *
             * Generated by make:storage-migration on {$timestamp}.
             *
             * @expectedReverseSeconds 30
             */
            return new class extends Migration {
                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    // Add new typed columns to the existing entity table.
            {$addColumnsPhp}

                    // Backfill data from the _data blob column into the new typed columns.
                    \$backfillFields = {$backfillJson};
                    BackfillHelper::backfill(\$conn, '{$escapedEntityTable}', \$backfillFields);
                }

                public function down(SchemaBuilder \$schema): void
                {
                    // Reversing sql-column migrations by dropping typed columns is destructive
                    // and not supported automatically. To revert, restore from a database backup
                    // or manually re-migrate the data back into the _data JSON blob.
                    // See docs/upgrades/ for the storage migration cookbook.
                }
            };
            PHP;
    }

    /**
     * Derive the target filename (without directory) for this migration.
     *
     * @api
     */
    public function filename(string $entityTypeId, string $target): string
    {
        $timestamp = date('Ymd_His');
        return "{$timestamp}_storage_migration_{$entityTypeId}_to_{$target}.php";
    }

}
