<?php

declare(strict_types=1);

// Migrated by bin/migrate-surface-map from docs/public-surface-map.php
// and docs/public-surface-map.md (FW-DELIVERY-SURFACE-01 / #2901). This
// file, not the generated docs/public-surface-map.*, is the editable
// authority — see docs/specs/public-surface-declarations.md.
return [
    'entries' => [
        ['fqcn' => 'Waaseyaa\\Entity\\ApiExposableEntityTypeInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Audit\\EntityAuditKey', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Audit\\LifecycleAuditKey', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Cast\\FromArrayEntityValueInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Community\\HasCommunityInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Community\\HasCommunityTrait', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\ConfigEntityBase', 'disposition' => 'public', 'purpose' => 'Base for configuration entities with string machine-name IDs and enable/disable lifecycle'],
        ['fqcn' => 'Waaseyaa\\Entity\\ConfigEntityInterface', 'disposition' => 'public', 'purpose' => 'Contract for configuration entities including status and enabled/disabled state'],
        ['fqcn' => 'Waaseyaa\\Entity\\ContentEntityBase', 'disposition' => 'public', 'purpose' => 'Fieldable entity base supporting dynamic field values and per-language translation'],
        ['fqcn' => 'Waaseyaa\\Entity\\ContentEntityInterface', 'disposition' => 'public', 'purpose' => 'Marker combining `EntityInterface` and `FieldableInterface` for content entities'],
        ['fqcn' => 'Waaseyaa\\Entity\\DateTime\\EntityClockInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\DateTime\\FixedEntityClock', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\DateTime\\TimestampFieldConvention', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\DateTime\\UtcEntityClock', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\DefinesEntityType', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityBase', 'disposition' => 'public', 'purpose' => 'Default implementations of `EntityInterface`; subclasses hardcode entity type ID and keys'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityInterface', 'disposition' => 'public', 'purpose' => 'Core contract for all entity types: identity, label, type ID, and value access'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntitySerializationBoundary', 'disposition' => 'public', 'purpose' => 'Explicit dormant/enforced PHP serialization boundary for value-bearing entities'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntitySerializationBoundaryConfig', 'disposition' => 'public', 'purpose' => 'Exact activation toggle for entity PHP serialization rejection'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityTypeForeignKeyDefinitionInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityTypeInterface', 'disposition' => 'public', 'purpose' => 'Describes an entity type: ID, label, class, keys, field definitions, and constraints'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityTypeManagerInterface', 'disposition' => 'public', 'purpose' => 'Registers entity types and provides storage instances for each'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityTypeStorageSchemaTransitionDefinitionInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityTypeStorageUniqueKeyDefinitionInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityValueReadGuardInterface', 'disposition' => 'internal', 'purpose' => 'Internal sealed-entity adapter for protected-field read decisions and decision-cache invalidation'],
        ['fqcn' => 'Waaseyaa\\Entity\\EntityValues', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Event\\EntityEvent', 'disposition' => 'public', 'purpose' => 'Lifecycle event base; non-`final` so `TranslationEvent` may extend it (M-006, WP08 — public-surface change documented in mission reconciliation note)'],
        ['fqcn' => 'Waaseyaa\\Entity\\Event\\EntityEventFactoryInterface', 'disposition' => 'public', 'purpose' => 'Creates `EntityEvent` instances with optional before/after snapshots'],
        ['fqcn' => 'Waaseyaa\\Entity\\Event\\EntityEvents', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Event\\TranslationEvent', 'disposition' => 'public', 'purpose' => 'Translation lifecycle event extending `EntityEvent`; carries entity, target langcode, and (for updates/deletes) prior values (M-006, WP08). Event-name constants: `PRE_TRANSLATION_INSERT`, `POST_TRANSLATION_INSERT`, `PRE_TRANSLATION_UPDATE`, `POST_TRANSLATION_UPDATE`, `PRE_TRANSLATION_DELETE`, `POST_TRANSLATION_DELETE`'],
        ['fqcn' => 'Waaseyaa\\Entity\\Exception\\EntityTranslationException', 'disposition' => 'public', 'purpose' => 'Translation persistence error with named-constructor factories `langcodeRequired`, `cannotRemoveDefault`, `translationAlreadyExists`, `translationNotFound` (M-006, WP01)'],
        ['fqcn' => 'Waaseyaa\\Entity\\Exception\\FieldAccessActivationBlocked', 'disposition' => 'public', 'purpose' => 'Checksum-backed hard failure when preflight blockers remain'],
        ['fqcn' => 'Waaseyaa\\Entity\\FieldReadLevel', 'disposition' => 'public', 'purpose' => 'Additive `public` / `protected` / `internal` definition metadata; dormant until the no-shim activation work package'],
        ['fqcn' => 'Waaseyaa\\Entity\\Field\\BundleStorageUniqueKeyRegistryInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Entity\\Field\\FieldDefinitionRegistryInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Field\\FieldReadLayoutGenerationSourceInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Entity\\FieldableInterface', 'disposition' => 'public', 'purpose' => 'Marks an entity as supporting named field access and definition retrieval'],
        ['fqcn' => 'Waaseyaa\\Entity\\Hydration\\FallbackChainResolver', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Hydration\\HydratableFromStorageInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Hydration\\HydrationContext', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Repository\\EntityRepositoryInterface', 'disposition' => 'public', 'purpose' => 'High-level CRUD API handling hydration, event dispatch, and language fallback. Adds `findTranslations(EntityInterface): array<string, EntityInterface>` (M-006, WP10)'],
        ['fqcn' => 'Waaseyaa\\Entity\\RevisionMetadata', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\RevisionableEntityInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\RevisionableEntityTrait', 'disposition' => 'public', 'purpose' => 'Default implementation of `RevisionableInterface` using `$values` and `$entityKeys`'],
        ['fqcn' => 'Waaseyaa\\Entity\\RevisionableInterface', 'disposition' => 'public', 'purpose' => 'Adds revision ID tracking and new-revision control to an entity'],
        ['fqcn' => 'Waaseyaa\\Entity\\Snapshot\\EntityValuesSnapshot', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\Storage\\EntityQueryInterface', 'disposition' => 'public', 'purpose' => 'Fluent query builder for filtering and loading entities by field conditions'],
        ['fqcn' => 'Waaseyaa\\Entity\\Storage\\EntityStorageInterface', 'disposition' => 'public', 'purpose' => 'Lower-level storage operations: load, save, delete, query'],
        ['fqcn' => 'Waaseyaa\\Entity\\Storage\\RevisionableStorageInterface', 'disposition' => 'public', 'purpose' => 'Extends entity storage with load, delete, and list operations for specific revisions'],
        ['fqcn' => 'Waaseyaa\\Entity\\Testing\\Translation\\TranslatableEntityContractTest', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\TranslatableEntityTrait', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Entity\\TranslatableInterface', 'disposition' => 'public', 'purpose' => 'Per-language translation access for a translatable entity (M-006 / ADR 017): `getTranslation`, `hasTranslation`, `addTranslation`, `removeTranslation`, `translations`, `defaultLangcode`, `activeLangcode`, `fieldLangcode`. `language()` retained as deprecated alias for `activeLangcode()`'],
        ['fqcn' => 'Waaseyaa\\Entity\\Validation\\RedactedInvalidValue', 'disposition' => 'internal', 'purpose' => 'Internal value-free sentinel used when validation reports a restricted invalid field'],
        ['fqcn' => 'Waaseyaa\\Entity\\Validation\\ValidationReadLedgerInterface', 'disposition' => 'internal', 'purpose' => 'Internal validation adapter that reserves an authorized restricted-field read before value access'],
        ['fqcn' => 'Waaseyaa\\Entity\\Validation\\ValidationReadReservationInterface', 'disposition' => 'internal', 'purpose' => 'Internal one-shot reservation that records validation-read success or failure without retaining the value'],
    ],
    'notes' => [
        '`EntityType::__construct(...translatable: bool = false, ...)` (constructor arg): Marks an entity type as translatable; load-bearing — enforced by boot validation (M-006, WP02)',
    ],
];
