<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Handler;

use Waaseyaa\Entity\EntityTypeInterface;
use Waaseyaa\EntityStorage\Exception\StorageMigrationException;
use Waaseyaa\Field\FieldDefinition;

/**
 * Generates the PHP source of an "add revisions" migration for a given entity type.
 *
 * Companion to {@see AddTranslationsMigrationGenerator}; together they implement the
 * two-axis (translation × revision) promotion paths from the M-004 mission contract.
 *
 * Detection matrix (FR-025, FR-027, FR-029 — see
 * `contracts/two-axis-migration.md` §2):
 *
 *   - Target is already revisionable + translatable → raise
 *     {@see StorageMigrationException::noOpPromotion}.
 *   - Target is already revisionable (single-axis) → raise
 *     {@see StorageMigrationException::noOpPromotion}.
 *   - Target is translatable-only → emit two-axis-from-translatable migration
 *     (adds `vid` to `{entity}` and `{entity}__translation`, creates
 *     `{entity}__revision` and `{entity}__translation__revision`, backfills
 *     initial revisions from current values).
 *   - Target is non-translatable + non-revisionable → emit single-axis
 *     revisionable migration (mirror of M-006's single-axis translation path).
 *
 * The generated migration is a single anonymous class with raw-SQL `up()` and
 * `down()` bodies. SQL is executed via {@see \Waaseyaa\Foundation\Migration\SchemaBuilder::getConnection()}
 * so that DBAL handles parameter binding and platform abstraction at apply time.
 *
 * @api
 *
 * @internal
 */
final class AddRevisionsMigrationGenerator
{
    /**
     * Orchestrate the `--add-revisions` flag (FR-025, FR-027, FR-029).
     *
     * @param list<string> $nonTranslatableColumns Schema-level non-translatable column names that
     *                                             move to the entity-revision table (single-axis
     *                                             and two-axis-from-translatable paths).
     * @param list<string> $translatableColumns    Schema-level translatable column names that move
     *                                             to the translation-revision table (two-axis-from-
     *                                             translatable path only; ignored otherwise).
     */
    public function generate(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        array $nonTranslatableColumns,
        array $translatableColumns = [],
    ): string {
        if ($entityType->isRevisionable()) {
            throw StorageMigrationException::noOpPromotion($entityType->id());
        }

        if ($entityType->isTranslatable()) {
            return $this->renderTwoAxisFromTranslatable(
                $entityType,
                $defaultLangcode,
                $nonTranslatableColumns,
                $translatableColumns,
            );
        }

        return $this->render($entityType, $nonTranslatableColumns);
    }

    /**
     * Render the PHP source for a non-translatable + non-revisionable → revisionable-only
     * promotion (single-axis path).
     *
     * Up migration:
     *   - CREATE TABLE `{entity}__revision` (vid PK, tid, audit cols, mirrored columns).
     *   - ALTER TABLE `{entity}` ADD COLUMN `vid INTEGER NOT NULL DEFAULT 0`.
     *   - Backfill: one initial revision per existing entity row.
     *   - UPDATE `{entity}` SET vid = matching `{entity}__revision.vid`.
     *
     * Down migration (DATA LOSS — all non-current revisions discarded):
     *   - DROP TABLE `{entity}__revision`.
     *   - ALTER TABLE `{entity}` DROP COLUMN `vid`.
     *
     * @param list<string> $revisionedColumns Schema-level columns to mirror onto the revision table.
     */
    public function render(EntityTypeInterface $entityType, array $revisionedColumns): string
    {
        $entityTable = $this->phpStringLiteral($entityType->id());
        $revisionTable = $this->phpStringLiteral($entityType->id() . '__revision');
        $cols = $this->phpArrayLiteral($revisionedColumns);
        // INDEX_NAME is a generated PHP string literal — escape it with the
        // same helper used for every other const, instead of interpolating the
        // raw id straight into the quotes.
        $indexNameLiteral = $this->phpStringLiteral($entityType->id() . '_rev_tid');
        // The entity type id also appears verbatim in the doc-comments below —
        // sanitize it so a `*/` in the id cannot terminate a comment early and
        // expose the remainder as executable PHP.
        $idComment = $this->commentSafe($entityType->id());

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Waaseyaa\\Foundation\\Migration\\Migration;
            use Waaseyaa\\Foundation\\Migration\\SchemaBuilder;

            /**
             * Promote `{$idComment}` to a revisionable entity type (single-axis path).
             *
             * Generated by `make:storage-migration {$idComment} --add-revisions`.
             *
             * Adds:
             *   - `{$idComment}__revision`  composite-PK revision history table
             *   - `{$idComment}.vid`        current-revision pointer column
             */
            return new class extends Migration
            {
                private const TABLE = {$entityTable};
                private const REVISION_TABLE = {$revisionTable};
                /** @var list<string> */
                private const REVISIONED_COLUMNS = {$cols};
                private const INDEX_NAME = {$indexNameLiteral};

                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    \$revCols = [
                        'vid INTEGER NOT NULL PRIMARY KEY',
                        'tid INTEGER NOT NULL',
                        'revision_created_at TEXT NOT NULL',
                        'revision_author INTEGER NULL',
                        'revision_log TEXT NULL',
                    ];
                    foreach (self::REVISIONED_COLUMNS as \$c) {
                        \$revCols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                    }

                    \$conn->executeStatement(sprintf(
                        'CREATE TABLE %s (%s)',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        implode(', ', \$revCols),
                    ));

                    \$conn->executeStatement(sprintf(
                        'CREATE INDEX %s ON %s (tid, vid DESC)',
                        self::INDEX_NAME,
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                    ));

                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s ADD COLUMN vid INTEGER NOT NULL DEFAULT 0',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));

                    // Backfill: each existing entity row gets an initial revision.
                    \$insertCols = ['vid', 'tid', 'revision_created_at', 'revision_author', 'revision_log'];
                    \$selectExprs = [
                        'row_number() OVER (ORDER BY id)',
                        'id',
                        \$conn->quote((new \\DateTimeImmutable('now', new \\DateTimeZone('UTC')))->format('Y-m-d\\TH:i:sP')),
                        'NULL',
                        \$conn->quote('Initial revision (migration backfill)'),
                    ];
                    foreach (self::REVISIONED_COLUMNS as \$c) {
                        \$insertCols[] = \$conn->quoteIdentifier(\$c);
                        \$selectExprs[] = \$conn->quoteIdentifier(\$c);
                    }

                    \$conn->executeStatement(sprintf(
                        'INSERT INTO %s (%s) SELECT %s FROM %s',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        implode(', ', \$insertCols),
                        implode(', ', \$selectExprs),
                        \$conn->quoteIdentifier(self::TABLE),
                    ));

                    \$conn->executeStatement(sprintf(
                        'UPDATE %s SET vid = (SELECT vid FROM %s r WHERE r.tid = %s.id)',
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                }

                /**
                 * DATA LOSS WARNING: This reversal drops the entire revision history.
                 * Only the entity row remains; all non-current revisions are discarded.
                 * Back up `{$idComment}__revision` before applying. (FR-028)
                 */
                public function down(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    \$conn->executeStatement(sprintf(
                        'DROP TABLE %s',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                    ));

                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s DROP COLUMN vid',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                }
            };

            PHP;
    }

    /**
     * Render the PHP source for a translatable-only → two-axis promotion (FR-027).
     *
     * Up migration:
     *   - CREATE TABLE `{entity}__revision` (vid PK, tid, audit cols, non-translatable cols).
     *   - CREATE TABLE `{entity}__translation__revision` (vid PK, tid, langcode, audit cols,
     *     translatable cols) + UNIQUE(tid, langcode, vid) + index on (tid, langcode, vid DESC).
     *   - ALTER TABLE `{entity}` ADD COLUMN vid; ALTER `{entity}__translation` ADD COLUMN vid.
     *   - Backfill: initial entity-revision per `{entity}` row; initial translation-revision per
     *     `{entity}__translation` row.
     *   - Drop the non-translatable columns from `{entity}` (they live on `{entity}__revision`).
     *   - Drop the translatable columns from `{entity}__translation` (they live on
     *     `{entity}__translation__revision`).
     *
     * Down migration (DATA LOSS — all non-current revisions dropped):
     *   - Re-add non-translatable columns on `{entity}`, backfill from `{entity}__revision`.
     *   - Re-add translatable columns on `{entity}__translation`, backfill from
     *     `{entity}__translation__revision`.
     *   - DROP TABLE `{entity}__translation__revision`; DROP TABLE `{entity}__revision`.
     *   - DROP COLUMN vid from `{entity}` and `{entity}__translation`.
     *
     * @param list<string> $nonTranslatableColumns Columns to move onto `{entity}__revision`.
     * @param list<string> $translatableColumns    Columns to move onto `{entity}__translation__revision`.
     */
    public function renderTwoAxisFromTranslatable(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        array $nonTranslatableColumns,
        array $translatableColumns,
    ): string {
        $entityTable = $this->phpStringLiteral($entityType->id());
        $translationTable = $this->phpStringLiteral($entityType->id() . '__translation');
        $revisionTable = $this->phpStringLiteral($entityType->id() . '__revision');
        $translationRevisionTable = $this->phpStringLiteral($entityType->id() . '__translation__revision');
        $defaultLc = $this->phpStringLiteral($defaultLangcode);
        $nonTxCols = $this->phpArrayLiteral($nonTranslatableColumns);
        $txCols = $this->phpArrayLiteral($translatableColumns);
        // Index-name consts are generated PHP string literals — escape them with
        // the same helper used for every other const above.
        $revIndexLiteral = $this->phpStringLiteral($entityType->id() . '_rev_tid');
        $txRevIndexLiteral = $this->phpStringLiteral($entityType->id() . '_tx_rev_lookup');
        // The entity type id appears verbatim in the doc-comments below —
        // sanitize it once so a `*/` cannot terminate a comment early.
        $idComment = $this->commentSafe($entityType->id());

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Waaseyaa\\Foundation\\Migration\\Migration;
            use Waaseyaa\\Foundation\\Migration\\SchemaBuilder;

            /**
             * Promote `{$idComment}` from translatable-only to two-axis
             * (translation × revision) storage.
             *
             * Default langcode (used for audit `revision_log`): {$defaultLangcode}
             *
             * Generated by `make:storage-migration {$idComment} --add-revisions`.
             *
             * Tables created:
             *   - `{$idComment}__revision`               entity-revision history
             *   - `{$idComment}__translation__revision`  composite-PK translation revisions
             *
             * Existing `{$idComment}` rows become initial entity revisions; existing
             * `{$idComment}__translation` rows become initial per-langcode translation
             * revisions before their column data is moved off the current-state tables.
             */
            return new class extends Migration
            {
                private const TABLE = {$entityTable};
                private const TRANSLATION_TABLE = {$translationTable};
                private const REVISION_TABLE = {$revisionTable};
                private const TRANSLATION_REVISION_TABLE = {$translationRevisionTable};
                private const DEFAULT_LANGCODE = {$defaultLc};
                /** @var list<string> */
                private const NON_TRANSLATABLE_COLUMNS = {$nonTxCols};
                /** @var list<string> */
                private const TRANSLATABLE_COLUMNS = {$txCols};
                private const REV_INDEX_NAME = {$revIndexLiteral};
                private const TX_REV_INDEX_NAME = {$txRevIndexLiteral};

                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    // Entity-revision table.
                    \$revCols = [
                        'vid INTEGER NOT NULL PRIMARY KEY',
                        'tid INTEGER NOT NULL',
                        'revision_created_at TEXT NOT NULL',
                        'revision_author INTEGER NULL',
                        'revision_log TEXT NULL',
                    ];
                    foreach (self::NON_TRANSLATABLE_COLUMNS as \$c) {
                        \$revCols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                    }
                    \$conn->executeStatement(sprintf(
                        'CREATE TABLE %s (%s)',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        implode(', ', \$revCols),
                    ));
                    \$conn->executeStatement(sprintf(
                        'CREATE INDEX %s ON %s (tid, vid DESC)',
                        self::REV_INDEX_NAME,
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                    ));

                    // Translation-revision table.
                    \$txRevCols = [
                        'vid INTEGER NOT NULL PRIMARY KEY',
                        'tid INTEGER NOT NULL',
                        'langcode VARCHAR(12) NOT NULL',
                        'revision_created_at TEXT NOT NULL',
                        'revision_author INTEGER NULL',
                        'revision_log TEXT NULL',
                    ];
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$txRevCols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                    }
                    \$txRevCols[] = 'UNIQUE (tid, langcode, vid)';
                    \$conn->executeStatement(sprintf(
                        'CREATE TABLE %s (%s)',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                        implode(', ', \$txRevCols),
                    ));
                    \$conn->executeStatement(sprintf(
                        'CREATE INDEX %s ON %s (tid, langcode, vid DESC)',
                        self::TX_REV_INDEX_NAME,
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                    ));

                    // Add vid pointer columns to current-state tables.
                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s ADD COLUMN vid INTEGER NOT NULL DEFAULT 0',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s ADD COLUMN vid INTEGER NOT NULL DEFAULT 0',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));

                    \$now = (new \\DateTimeImmutable('now', new \\DateTimeZone('UTC')))->format('Y-m-d\\TH:i:sP');
                    \$initialLog = 'Initial revision (migration backfill)';

                    // Backfill entity-revisions from current `{entity}` rows.
                    \$revInsertCols = ['vid', 'tid', 'revision_created_at', 'revision_author', 'revision_log'];
                    \$revSelectExprs = [
                        'row_number() OVER (ORDER BY id)',
                        'id',
                        \$conn->quote(\$now),
                        'NULL',
                        \$conn->quote(\$initialLog),
                    ];
                    foreach (self::NON_TRANSLATABLE_COLUMNS as \$c) {
                        \$revInsertCols[] = \$conn->quoteIdentifier(\$c);
                        \$revSelectExprs[] = \$conn->quoteIdentifier(\$c);
                    }
                    \$conn->executeStatement(sprintf(
                        'INSERT INTO %s (%s) SELECT %s FROM %s',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        implode(', ', \$revInsertCols),
                        implode(', ', \$revSelectExprs),
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                    \$conn->executeStatement(sprintf(
                        'UPDATE %s SET vid = (SELECT vid FROM %s r WHERE r.tid = %s.id)',
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                        \$conn->quoteIdentifier(self::TABLE),
                    ));

                    // Backfill translation-revisions from current `{entity}__translation` rows.
                    // vid IDs are offset by (max(entity-revisions.vid)) so namespaces don't collide.
                    \$txRevInsertCols = ['vid', 'tid', 'langcode', 'revision_created_at', 'revision_author', 'revision_log'];
                    \$txRevSelectExprs = [
                        sprintf('(SELECT COALESCE(MAX(vid), 0) FROM %s) + row_number() OVER (ORDER BY entity_id, langcode)', \$conn->quoteIdentifier(self::REVISION_TABLE)),
                        'entity_id',
                        'langcode',
                        \$conn->quote(\$now),
                        'NULL',
                        \$conn->quote(\$initialLog),
                    ];
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$txRevInsertCols[] = \$conn->quoteIdentifier(\$c);
                        \$txRevSelectExprs[] = \$conn->quoteIdentifier(\$c);
                    }
                    \$conn->executeStatement(sprintf(
                        'INSERT INTO %s (%s) SELECT %s FROM %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                        implode(', ', \$txRevInsertCols),
                        implode(', ', \$txRevSelectExprs),
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));
                    \$conn->executeStatement(sprintf(
                        'UPDATE %s SET vid = (SELECT vid FROM %s tr WHERE tr.tid = %s.entity_id AND tr.langcode = %s.langcode)',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));

                    // Drop non-translatable columns from `{entity}` (they live on `{entity}__revision`).
                    foreach (self::NON_TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP COLUMN %s',
                            \$conn->quoteIdentifier(self::TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }
                    // Drop translatable columns from `{entity}__translation`.
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP COLUMN %s',
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }
                }

                /**
                 * DATA LOSS WARNING: This reversal drops every non-current revision row across
                 * `{$idComment}__revision` and `{$idComment}__translation__revision`.
                 * Only the current entity row and current per-langcode translation row are
                 * preserved (rehydrated from the latest revision in each axis). Back up the
                 * revision tables before applying if revision history matters. (FR-028)
                 */
                public function down(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    // Re-add the non-translatable columns to `{entity}`.
                    foreach (self::NON_TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD COLUMN %s TEXT',
                            \$conn->quoteIdentifier(self::TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }
                    // Re-add the translatable columns to `{entity}__translation`.
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD COLUMN %s TEXT',
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }

                    // Backfill non-translatable columns from the current entity-revision.
                    foreach (self::NON_TRANSLATABLE_COLUMNS as \$c) {
                        \$q = \$conn->quoteIdentifier(\$c);
                        \$conn->executeStatement(sprintf(
                            'UPDATE %s SET %s = (SELECT %s FROM %s r WHERE r.tid = %s.id AND r.vid = %s.vid)',
                            \$conn->quoteIdentifier(self::TABLE),
                            \$q,
                            \$q,
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                            \$conn->quoteIdentifier(self::TABLE),
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                    // Backfill translatable columns from the current translation-revision.
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$q = \$conn->quoteIdentifier(\$c);
                        \$conn->executeStatement(sprintf(
                            'UPDATE %s SET %s = (SELECT %s FROM %s tr WHERE tr.tid = %s.entity_id AND tr.langcode = %s.langcode AND tr.vid = %s.vid)',
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                            \$q,
                            \$q,
                            \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                            \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                        ));
                    }

                    \$conn->executeStatement(sprintf(
                        'DROP TABLE %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                    ));
                    \$conn->executeStatement(sprintf(
                        'DROP TABLE %s',
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                    ));

                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s DROP COLUMN vid',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));
                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s DROP COLUMN vid',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                }
            };

            PHP;
    }

    /**
     * Walk an entity type's field definitions and return non-translatable column names.
     *
     * Used for two-axis-from-translatable generation: these columns move from the
     * current-state `{entity}` table onto `{entity}__revision`. Mirrors
     * {@see AddTranslationsMigrationGenerator::translatableColumns()}.
     *
     * @return list<string>
     */
    public function nonTranslatableColumns(EntityTypeInterface $entityType): array
    {
        $cols = [];
        foreach ($entityType->getFieldDefinitions() as $field) {
            if (!$field instanceof FieldDefinition) {
                continue;
            }
            if (!$field->isTranslatable()) {
                $cols[] = $field->getName();
            }
        }

        return $cols;
    }

    /**
     * Walk an entity type's field definitions and return translatable column names.
     *
     * Used for two-axis-from-translatable generation: these columns move from
     * `{entity}__translation` onto `{entity}__translation__revision`.
     *
     * @return list<string>
     */
    public function translatableColumns(EntityTypeInterface $entityType): array
    {
        $cols = [];
        foreach ($entityType->getFieldDefinitions() as $field) {
            if (!$field instanceof FieldDefinition) {
                continue;
            }
            if ($field->isTranslatable()) {
                $cols[] = $field->getName();
            }
        }

        return $cols;
    }

    private function phpStringLiteral(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }

    /**
     * Sanitize a value for interpolation into a generated `/** ... *\/`
     * doc-comment. A literal `*\/` in the value would otherwise terminate the
     * comment early and expose the remainder of the line as executable PHP on
     * autoload; inserting a space keeps the text readable while making the
     * sequence inert.
     */
    private function commentSafe(string $value): string
    {
        return str_replace('*/', '* /', $value);
    }

    /**
     * @param list<string> $values
     */
    private function phpArrayLiteral(array $values): string
    {
        if ($values === []) {
            return '[]';
        }
        $parts = array_map(fn(string $v): string => $this->phpStringLiteral($v), $values);

        return '[' . implode(', ', $parts) . ']';
    }
}
