<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Handler;

use Waaseyaa\Entity\EntityTypeInterface;
use Waaseyaa\Entity\LangcodeValidator;
use Waaseyaa\EntityStorage\Exception\StorageMigrationException;
use Waaseyaa\Field\FieldDefinition;

/**
 * Generates the PHP source of an "add translations" migration for a given
 * entity type and primary backend.
 *
 * The generated migration is a single anonymous class with raw-SQL `up()` and
 * `down()` bodies. SQL is executed via {@see \Waaseyaa\Foundation\Migration\SchemaBuilder::getConnection()}
 * so that DBAL handles parameter binding and platform abstraction at apply time.
 *
 * DDL shape (FR-050..FR-053, WP04 sql-blob + WP05 sql-column contracts):
 *
 *   sql-column path
 *     up():
 *       CREATE TABLE {table}_translations (entity_id, langcode, <translatable cols>, PK(entity_id, langcode), FK -> {table})
 *       INSERT INTO {table}_translations SELECT entity_id, '<lc>', <cols> FROM {table}
 *       ALTER TABLE {table} DROP COLUMN <translatable col>...
 *       ALTER TABLE {table} ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT '<lc>'
 *     down() (DATA LOSS):
 *       backfill primary cols from rows where langcode = default_langcode
 *       DROP TABLE {table}_translations
 *       ALTER TABLE {table} DROP COLUMN default_langcode
 *
 *   sql-blob path
 *     up():
 *       ALTER TABLE {table} ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT '<lc>'
 *       UPDATE {table} SET langcode = '<lc>' WHERE langcode IS NULL OR langcode = ''
 *       widen PK to (entity_id, langcode) (DBAL handles per-platform rebuild)
 *       partial UNIQUE INDEX on uuid WHERE langcode = default_langcode (with MySQL note)
 *     down() (DATA LOSS):
 *       narrow PK back to (entity_id)
 *       DROP INDEX
 *       ALTER TABLE {table} DROP COLUMN default_langcode
 *
 * @internal
 * @api
 */
final class AddTranslationsMigrationGenerator
{
    /**
     * Render the PHP source of the generated migration.
     *
     * @param 'sql-blob'|'sql-column' $backend
     * @param list<string>            $translatableColumns Schema-level column names (sql-column path).
     */
    public function render(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        string $backend,
        array $translatableColumns,
    ): string {
        LangcodeValidator::validate($defaultLangcode);

        $table = $this->phpStringLiteral($entityType->id());
        $translationsTable = $this->phpStringLiteral($entityType->id() . '_translations');
        $defaultLc = $this->phpStringLiteral($defaultLangcode);
        $cols = $this->phpArrayLiteral($translatableColumns);
        // The entity type id is expected to already be a machine name (the
        // make:content-type / make:entity-type boundary now enforces that
        // allowlist), but it also appears verbatim in doc-comments below —
        // sanitize it so a `*/` in the id can never terminate a comment
        // early and expose the remainder as executable PHP.
        $idComment = $this->commentSafe($entityType->id());

        // Defense in depth per FR-007: the PHP type system narrows $backend to
        // 'sql-blob'|'sql-column', making injection practically impossible. The
        // assert documents this intent and will fire in development/test environments
        // if the type contract is ever widened.
        \assert(
            in_array($backend, ['sql-blob', 'sql-column'], true),
            "backend must be 'sql-blob' or 'sql-column', got: {$backend}",
        );

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Waaseyaa\\Foundation\\Migration\\Migration;
            use Waaseyaa\\Foundation\\Migration\\SchemaBuilder;

            /**
             * Promote `{$idComment}` to a translatable entity type.
             *
             * Backend: {$backend}
             * Default langcode: {$defaultLangcode}
             *
             * Generated by `make:migration --add-translations={$idComment} --default-langcode={$defaultLangcode}`.
             */
            return new class extends Migration
            {
                private const TABLE = {$table};
                private const TRANSLATIONS_TABLE = {$translationsTable};
                private const DEFAULT_LANGCODE = {$defaultLc};
                /** @var list<string> */
                private const TRANSLATABLE_COLUMNS = {$cols};
                private const BACKEND = '{$backend}';

                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    if (self::BACKEND === 'sql-column') {
                        // Build the translations table column list.
                        \$cols = ['entity_id INTEGER NOT NULL', 'langcode VARCHAR(12) NOT NULL'];
                        foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                            \$cols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                        }
                        \$cols[] = 'PRIMARY KEY (entity_id, langcode)';

                        \$conn->executeStatement(sprintf(
                            'CREATE TABLE %s (%s, FOREIGN KEY (entity_id) REFERENCES %s(id) ON DELETE CASCADE)',
                            \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                            implode(', ', \$cols),
                            \$conn->quoteIdentifier(self::TABLE),
                        ));

                        if (self::TRANSLATABLE_COLUMNS !== []) {
                            \$qCols = array_map(static fn (string \$c): string => \$conn->quoteIdentifier(\$c), self::TRANSLATABLE_COLUMNS);
                            \$conn->executeStatement(sprintf(
                                'INSERT INTO %s (entity_id, langcode, %s) SELECT id, %s, %s FROM %s',
                                \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                                implode(', ', \$qCols),
                                \$conn->quote(self::DEFAULT_LANGCODE),
                                implode(', ', \$qCols),
                                \$conn->quoteIdentifier(self::TABLE),
                            ));

                            foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                                \$conn->executeStatement(sprintf(
                                    'ALTER TABLE %s DROP COLUMN %s',
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$conn->quoteIdentifier(\$c),
                                ));
                            }
                        }

                        \$conn->executeStatement(sprintf(
                            "ALTER TABLE %s ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT %s",
                            \$conn->quoteIdentifier(self::TABLE),
                            \$conn->quote(self::DEFAULT_LANGCODE),
                        ));

                        return;
                    }

                    // sql-blob path.
                    \$conn->executeStatement(sprintf(
                        "ALTER TABLE %s ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT %s",
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quote(self::DEFAULT_LANGCODE),
                    ));

                    \$conn->executeStatement(sprintf(
                        "UPDATE %s SET langcode = %s WHERE langcode IS NULL OR langcode = ''",
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quote(self::DEFAULT_LANGCODE),
                    ));

                    // Widen PK to (entity_id, langcode). DBAL schema diff is the safe path here;
                    // direct ALTER syntax differs per platform (SQLite rebuilds the table, MySQL
                    // accepts `DROP PRIMARY KEY, ADD PRIMARY KEY ...`, PostgreSQL uses constraint ops).
                    \$platform = \$conn->getDatabasePlatform()->getName();
                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP PRIMARY KEY, ADD PRIMARY KEY (entity_id, langcode)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } elseif (\$platform === 'postgresql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP CONSTRAINT %s_pkey',
                            \$conn->quoteIdentifier(self::TABLE),
                            self::TABLE,
                        ));
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD PRIMARY KEY (entity_id, langcode)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                    // SQLite: PRIMARY KEY widening is handled by SqlSchemaHandler::sync() on the next boot.

                    // Partial unique index on uuid WHERE langcode = default_langcode.
                    // NOTE: MySQL <8 has no partial indexes. Use full unique index on (uuid, langcode) as a fallback.
                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'CREATE UNIQUE INDEX %s_uuid_default ON %s(uuid, langcode)',
                            self::TABLE,
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } else {
                        \$conn->executeStatement(sprintf(
                            'CREATE UNIQUE INDEX %s_uuid_default ON %s(uuid) WHERE langcode = default_langcode',
                            self::TABLE,
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                }

                /**
                 * DATA LOSS WARNING: This reversal drops non-default-langcode translation rows.
                 * Backup before applying if multilingual content exists. Any field values whose
                 * langcode differs from the snapshotted default ({$defaultLangcode}) will be lost.
                 */
                public function down(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    if (self::BACKEND === 'sql-column') {
                        // Re-add the translatable columns as TEXT NULL.
                        foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                            \$conn->executeStatement(sprintf(
                                'ALTER TABLE %s ADD COLUMN %s TEXT',
                                \$conn->quoteIdentifier(self::TABLE),
                                \$conn->quoteIdentifier(\$c),
                            ));
                        }

                        // Backfill from translations where langcode = default_langcode.
                        if (self::TRANSLATABLE_COLUMNS !== []) {
                            foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                                \$q = \$conn->quoteIdentifier(\$c);
                                \$conn->executeStatement(sprintf(
                                    'UPDATE %s SET %s = (SELECT %s FROM %s t WHERE t.entity_id = %s.id AND t.langcode = %s)',
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$q,
                                    \$q,
                                    \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$conn->quote(self::DEFAULT_LANGCODE),
                                ));
                            }
                        }

                        \$conn->executeStatement(sprintf(
                            'DROP TABLE %s',
                            \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                        ));

                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP COLUMN default_langcode',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));

                        return;
                    }

                    // sql-blob path.
                    \$platform = \$conn->getDatabasePlatform()->getName();
                    \$conn->executeStatement(sprintf(
                        'DROP INDEX %s_uuid_default',
                        self::TABLE,
                    ));

                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP PRIMARY KEY, ADD PRIMARY KEY (entity_id)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } elseif (\$platform === 'postgresql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP CONSTRAINT %s_pkey',
                            \$conn->quoteIdentifier(self::TABLE),
                            self::TABLE,
                        ));
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD PRIMARY KEY (entity_id)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                    // SQLite: PK narrowing is handled by SqlSchemaHandler::sync() on the next boot.

                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s DROP COLUMN default_langcode',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                }
            };

            PHP;
    }

    /**
     * Orchestrate the `--add-translations` flag (FR-025, FR-026, FR-029).
     *
     * Detection matrix (per `contracts/two-axis-migration.md` §2):
     *   - target is already two-axis (revisionable + translatable) → raise
     *     `StorageMigrationException::noOpPromotion`.
     *   - target is already single-axis translatable (non-revisionable) → raise
     *     `StorageMigrationException::noOpPromotion`.
     *   - target is revisionable-only → emit two-axis-from-revisionable migration.
     *   - target is non-translatable + non-revisionable → emit M-006 single-axis
     *     translatable migration (unchanged regression path).
     *
     * @param 'sql-blob'|'sql-column' $backend
     * @param list<string>            $translatableColumns Schema-level column names (sql-column path).
     */
    public function generate(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        string $backend,
        array $translatableColumns,
    ): string {
        LangcodeValidator::validate($defaultLangcode);

        if ($entityType->isTranslatable()) {
            throw StorageMigrationException::noOpPromotion($entityType->id());
        }

        if ($entityType->isRevisionable()) {
            return $this->renderTwoAxisFromRevisionable(
                $entityType,
                $defaultLangcode,
                $translatableColumns,
            );
        }

        return $this->render($entityType, $defaultLangcode, $backend, $translatableColumns);
    }

    /**
     * Render the PHP source for a revisionable-only → two-axis promotion (FR-026).
     *
     * Up migration:
     *   - CREATE TABLE `{entity}__translation` (tid, langcode, vid) PK(tid, langcode).
     *   - CREATE TABLE `{entity}__translation__revision` (vid, tid, langcode, audit cols, translatable cols)
     *     PK(vid) + UNIQUE(tid, langcode, vid) + lookup index on (tid, langcode, vid DESC).
     *   - Backfill `{entity}__translation__revision` from each existing `{entity}__revision` row using
     *     the supplied default langcode.
     *   - Backfill `{entity}__translation` per-(entity, default_langcode) current-revision pointer.
     *   - Drop the translatable columns from `{entity}__revision` (they now live on the translation
     *     revision table).
     *
     * Down migration (DATA LOSS — non-default-langcode revisions are dropped):
     *   - Re-add the translatable columns to `{entity}__revision`.
     *   - Backfill those columns from `{entity}__translation__revision` rows whose langcode matches
     *     the per-entity `default_langcode` snapshot and whose vid equals the entity-level vid.
     *   - DROP TABLE `{entity}__translation__revision`.
     *   - DROP TABLE `{entity}__translation`.
     *
     * @param list<string> $translatableColumns Schema-level column names that move to the translation
     *                                          revision table.
     */
    public function renderTwoAxisFromRevisionable(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        array $translatableColumns,
    ): string {
        LangcodeValidator::validate($defaultLangcode);

        $entityTable = $this->phpStringLiteral($entityType->id());
        $translationTable = $this->phpStringLiteral($entityType->id() . '__translation');
        $translationRevisionTable = $this->phpStringLiteral($entityType->id() . '__translation__revision');
        $revisionTable = $this->phpStringLiteral($entityType->id() . '__revision');
        $defaultLc = $this->phpStringLiteral($defaultLangcode);
        $cols = $this->phpArrayLiteral($translatableColumns);
        // INDEX_NAME is a generated PHP string literal — escape it with the
        // same helper used for every other const above, instead of
        // interpolating the raw id straight into the quotes.
        $indexNameLiteral = $this->phpStringLiteral($entityType->id() . '_tx_rev_lookup');
        // See the comment in render() above: the doc-comments below embed the
        // raw entity type id repeatedly, so sanitize it once here too.
        $idComment = $this->commentSafe($entityType->id());

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Waaseyaa\\Foundation\\Migration\\Migration;
            use Waaseyaa\\Foundation\\Migration\\SchemaBuilder;

            /**
             * Promote `{$idComment}` from revisionable-only to two-axis
             * (translation × revision) storage.
             *
             * Default langcode (backfill seed): {$defaultLangcode}
             *
             * Generated by `make:storage-migration {$idComment} --add-translations`.
             *
             * Two-axis tables created:
             *   - `{$idComment}__translation`              (tid, langcode, vid) PK(tid, langcode)
             *   - `{$idComment}__translation__revision`    composite-PK translation revisions
             *
             * Existing `{$idComment}__revision` rows are backfilled as default-langcode
             * translation revisions before the translatable columns are dropped from
             * `{$idComment}__revision`.
             */
            return new class extends Migration
            {
                private const TABLE = {$entityTable};
                private const TRANSLATION_TABLE = {$translationTable};
                private const TRANSLATION_REVISION_TABLE = {$translationRevisionTable};
                private const REVISION_TABLE = {$revisionTable};
                private const DEFAULT_LANGCODE = {$defaultLc};
                /** @var list<string> */
                private const TRANSLATABLE_COLUMNS = {$cols};
                private const INDEX_NAME = {$indexNameLiteral};

                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    // Translation pointer table: per-(entity, langcode) current revision pointer.
                    \$conn->executeStatement(sprintf(
                        'CREATE TABLE %s (tid INTEGER NOT NULL, langcode VARCHAR(12) NOT NULL, vid INTEGER NOT NULL, PRIMARY KEY (tid, langcode))',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));

                    // Translation-revision table: composite-PK history per langcode.
                    \$revCols = [
                        'vid INTEGER NOT NULL PRIMARY KEY',
                        'tid INTEGER NOT NULL',
                        'langcode VARCHAR(12) NOT NULL',
                        'revision_created_at TEXT NOT NULL',
                        'revision_author INTEGER NULL',
                        'revision_log TEXT NULL',
                    ];
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$revCols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                    }
                    \$revCols[] = 'UNIQUE (tid, langcode, vid)';

                    \$conn->executeStatement(sprintf(
                        'CREATE TABLE %s (%s)',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                        implode(', ', \$revCols),
                    ));

                    \$conn->executeStatement(sprintf(
                        'CREATE INDEX %s ON %s (tid, langcode, vid DESC)',
                        self::INDEX_NAME,
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                    ));

                    // Backfill: each existing revision becomes a default-langcode translation revision.
                    \$selectCols = ['vid', 'tid'];
                    \$insertCols = ['vid', 'tid', 'langcode'];
                    \$selectExprs = ['vid', 'tid', \$conn->quote(self::DEFAULT_LANGCODE)];
                    foreach (['revision_created_at', 'revision_author', 'revision_log'] as \$audit) {
                        \$insertCols[] = \$audit;
                        \$selectExprs[] = \$conn->quoteIdentifier(\$audit);
                    }
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$insertCols[] = \$conn->quoteIdentifier(\$c);
                        \$selectExprs[] = \$conn->quoteIdentifier(\$c);
                    }

                    \$conn->executeStatement(sprintf(
                        'INSERT INTO %s (%s) SELECT %s FROM %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                        implode(', ', \$insertCols),
                        implode(', ', \$selectExprs),
                        \$conn->quoteIdentifier(self::REVISION_TABLE),
                    ));

                    // Backfill: per-(entity, default_langcode) current-revision pointer.
                    \$conn->executeStatement(sprintf(
                        'INSERT INTO %s (tid, langcode, vid) SELECT id, %s, vid FROM %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                        \$conn->quote(self::DEFAULT_LANGCODE),
                        \$conn->quoteIdentifier(self::TABLE),
                    ));

                    // Drop translatable columns from the entity-revision table (they live on
                    // the translation-revision table now).
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP COLUMN %s',
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }
                }

                /**
                 * DATA LOSS WARNING: This reversal drops every non-default-langcode revision row.
                 * Only default-langcode current-translation-revision values are copied back onto
                 * `{$idComment}__revision`. Multilingual edit history cannot be reconstructed
                 * in a revisionable-only schema. Back up `{$idComment}__translation__revision`
                 * before applying if multilingual content exists. (FR-028)
                 */
                public function down(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    // Re-add the translatable columns to the entity-revision table as TEXT NULL.
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD COLUMN %s TEXT',
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                            \$conn->quoteIdentifier(\$c),
                        ));
                    }

                    // Backfill from translation-revision rows that match (tid, default_langcode, vid).
                    foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                        \$q = \$conn->quoteIdentifier(\$c);
                        \$conn->executeStatement(sprintf(
                            'UPDATE %s SET %s = (SELECT %s FROM %s tr WHERE tr.tid = %s.tid AND tr.langcode = %s AND tr.vid = %s.vid)',
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                            \$q,
                            \$q,
                            \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                            \$conn->quote(self::DEFAULT_LANGCODE),
                            \$conn->quoteIdentifier(self::REVISION_TABLE),
                        ));
                    }

                    \$conn->executeStatement(sprintf(
                        'DROP TABLE %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_REVISION_TABLE),
                    ));

                    \$conn->executeStatement(sprintf(
                        'DROP TABLE %s',
                        \$conn->quoteIdentifier(self::TRANSLATION_TABLE),
                    ));
                }
            };

            PHP;
    }

    private function phpStringLiteral(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }

    /**
     * Sanitize a value for interpolation into a generated `/** ... *\/`
     * doc-comment. A literal `*\/` in the value would otherwise terminate
     * the comment early and expose the remainder of the line as executable
     * PHP on autoload; inserting a space keeps the text readable while
     * making the sequence inert.
     */
    private function commentSafe(string $value): string
    {
        return str_replace('*/', '* /', $value);
    }

    /**
     * @param list<string> $values
     */
    private function phpArrayLiteral(array $values): string
    {
        if ($values === []) {
            return '[]';
        }
        $parts = array_map(fn(string $v): string => $this->phpStringLiteral($v), $values);

        return '[' . implode(', ', $parts) . ']';
    }

    /**
     * Walk an entity type's field definitions and return the translatable column names.
     *
     * Used for sql-column generation. For sql-blob the column list is irrelevant
     * (translations live in the row's `_data` JSON blob plus the langcode key).
     *
     * @return list<string>
     */
    public function translatableColumns(EntityTypeInterface $entityType): array
    {
        $cols = [];
        foreach ($entityType->getFieldDefinitions() as $field) {
            if (!$field instanceof FieldDefinition) {
                continue;
            }
            if ($field->isTranslatable()) {
                $cols[] = $field->getName();
            }
        }

        return $cols;
    }
}
