<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Site\Blueprint\Emitter;

use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintPermission;
use Waaseyaa\SiteContract\Generation\Exception\GenerationErrorCode;
use Waaseyaa\SiteContract\Generation\Exception\GenerationRefusalException;
use Waaseyaa\SiteContract\Generation\Exception\GenerationViolation;
use Waaseyaa\SiteContract\Generation\GeneratedArtifact;
use Waaseyaa\SiteContract\SiteManifest;

/**
 * Emits `src/Access/ApplicationBlueprintPermissions.php` (#2788, FW-SITE-
 * BLUEPRINT-01E): one `PERMISSION_<UPPER_SNAKE>` constant per declared
 * blueprint permission, a `seed(): array<string, array{title, description}>`
 * matching the {@see \Waaseyaa\Access\PermissionHandler::registerPermission()}
 * shape, and a `register()` convenience mirroring
 * {@see \Waaseyaa\Access\Capability\AgentCapabilities::register()} exactly
 * — a manual, per-app call, not auto-wired by the generated governance
 * provider (G1: `PermissionHandlerInterface` has no `registerPermission()`
 * method and is not bound in the container by default, so there is nothing
 * for a generated provider to resolve and call automatically).
 *
 * Emits nothing when the blueprint declares zero permissions (e.g.
 * `minimal.yaml`).
 *
 * @api
 */
final class PermissionCatalogueEmitter implements BlueprintArtifactEmitterInterface
{
    private const string PATH = 'src/Access/ApplicationBlueprintPermissions.php';

    public function id(): string
    {
        return 'permission-catalogue';
    }

    public function emit(ApplicationBlueprint $blueprint, SiteManifest $manifest): BlueprintEmission
    {
        if ($blueprint->permissions === []) {
            return new BlueprintEmission([]);
        }

        $permissions = array_values($blueprint->permissions);
        usort($permissions, static fn(BlueprintPermission $left, BlueprintPermission $right): int => strcmp($left->id, $right->id));

        self::assertNoConstantNameCollision($permissions);

        $constants = implode('', array_map(self::renderConstant(...), $permissions));
        $seedEntries = rtrim(implode('', array_map(self::renderSeedEntry(...), $permissions)), "\n");

        $content = <<<PHP
            <?php

            declare(strict_types=1);

            namespace App\\Access;

            use Waaseyaa\\Access\\PermissionHandler;

            /**
             * Generated by Waaseyaa\\CLI\\Site\\Blueprint\\ApplicationBlueprintCompiler.
             * Do not edit by hand.
             */
            final class ApplicationBlueprintPermissions
            {
            {$constants}
                /**
                 * @return array<string, array{title: string, description: string}>
                 */
                public static function seed(): array
                {
                    return [
            {$seedEntries}
                    ];
                }

                public static function register(PermissionHandler \$handler): void
                {
                    foreach (self::seed() as \$id => \$descriptor) {
                        \$handler->registerPermission(\$id, \$descriptor['title'], \$descriptor['description']);
                    }
                }
            }

            PHP;

        return new BlueprintEmission([new GeneratedArtifact(self::PATH, $content)]);
    }

    private static function renderConstant(BlueprintPermission $permission): string
    {
        $name = self::constantName($permission->id);
        $value = self::singleQuoted($permission->id);

        return "    public const string PERMISSION_{$name} = {$value};\n";
    }

    private static function renderSeedEntry(BlueprintPermission $permission): string
    {
        $id = self::singleQuoted($permission->id);
        $title = self::singleQuoted($permission->title);

        return "            {$id} => ['title' => {$title}, 'description' => ''],\n";
    }

    /** @param list<BlueprintPermission> $permissions sorted by id */
    private static function assertNoConstantNameCollision(array $permissions): void
    {
        $seen = [];
        $violations = [];
        $index = 0;
        foreach ($permissions as $permission) {
            $name = self::constantName($permission->id);
            if (isset($seen[$name])) {
                $violations[] = new GenerationViolation(
                    GenerationErrorCode::MaliciousIdentifier,
                    "Blueprint permission \"{$permission->id}\" PascalCases to the same PERMISSION_{$name} constant as \"{$seen[$name]}\".",
                    pointer: "/application_blueprint/permissions/{$index}/id",
                );
            } else {
                $seen[$name] = $permission->id;
            }
            ++$index;
        }

        if ($violations !== []) {
            throw new GenerationRefusalException(self::class, $violations);
        }
    }

    private static function constantName(string $id): string
    {
        return strtoupper((string) preg_replace('/[^a-z0-9]+/i', '_', trim($id)));
    }

    private static function singleQuoted(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }
}
