<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Site\Blueprint\Emitter;

use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintEntity;
use Waaseyaa\SiteContract\Generation\ComposerProviderRegistration;
use Waaseyaa\SiteContract\Generation\GeneratedArtifact;
use Waaseyaa\SiteContract\SiteManifest;

/**
 * Emits `src/Provider/ApplicationBlueprintServiceProvider.php`: registers
 * every generated entity type via `EntityType::fromClass()` and wires the
 * relationship registry, plus one {@see ComposerProviderRegistration} for
 * that FQCN with no group (FW-SITE-BLUEPRINT-01D decisions (e), (f)).
 *
 * `group` is `null`: `EntityType` group is roster/presentation metadata with
 * no runtime authority, and `content` would assert editorial-content
 * semantics the blueprint never declares (decision (e)).
 *
 * @api
 */
final class ProviderRegistrationEmitter implements BlueprintArtifactEmitterInterface
{
    private const string FQCN = 'App\\Provider\\ApplicationBlueprintServiceProvider';

    public function id(): string
    {
        return 'provider-registration';
    }

    public function emit(ApplicationBlueprint $blueprint, SiteManifest $manifest): BlueprintEmission
    {
        $entities = array_values($blueprint->entities);
        usort($entities, static fn(BlueprintEntity $left, BlueprintEntity $right): int => strcmp($left->id, $right->id));

        $registrations = implode('', array_map(self::renderRegistration(...), $entities));

        $content = <<<PHP
            <?php

            declare(strict_types=1);

            namespace App\\Provider;

            use Waaseyaa\\Entity\\EntityType;
            use Waaseyaa\\Foundation\\ServiceProvider\\ServiceProvider;

            /**
             * Generated by Waaseyaa\\CLI\\Site\\Blueprint\\ApplicationBlueprintCompiler.
             * Registers every governed application blueprint entity type; do not edit by
             * hand. The relationship registry consumed for referential integrity lives at
             * config/waaseyaa-blueprint/relationships.php.
             */
            final class ApplicationBlueprintServiceProvider extends ServiceProvider
            {
                public function register(): void
                {
            {$registrations}
                }
            }

            PHP;

        return new BlueprintEmission(
            [new GeneratedArtifact('src/Provider/ApplicationBlueprintServiceProvider.php', $content)],
            [new ComposerProviderRegistration(self::FQCN)],
        );
    }

    private static function renderRegistration(BlueprintEntity $entity): string
    {
        $className = self::pascalCase($entity->id);
        $revisionable = $entity->revisionable ? 'true' : 'false';
        $translatable = $entity->translatable ? 'true' : 'false';

        return <<<PHP
                    \$this->entityType(EntityType::fromClass(
                        \\App\\Entity\\{$className}::class,
                        revisionable: {$revisionable},
                        translatable: {$translatable},
                    ));

            PHP;
    }

    private static function pascalCase(string $id): string
    {
        return str_replace('_', '', ucwords(str_replace('-', '_', $id), '_'));
    }
}
