<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Site\Blueprint\Emitter;

use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintRelationship;
use Waaseyaa\SiteContract\Generation\GeneratedArtifact;
use Waaseyaa\SiteContract\SiteManifest;

/**
 * Emits `config/waaseyaa-blueprint/relationships.php`: one deterministic
 * registry row per blueprint relationship — id, from entity and field, to
 * entity, cardinality, required and `on_delete` — consumed by the generated
 * provider for referential integrity (FW-SITE-BLUEPRINT-01D decision (f)).
 *
 * @api
 */
final class RelationshipEmitter implements BlueprintArtifactEmitterInterface
{
    public function id(): string
    {
        return 'relationship-registry';
    }

    public function emit(ApplicationBlueprint $blueprint, SiteManifest $manifest): BlueprintEmission
    {
        $relationships = array_values($blueprint->relationships);
        usort($relationships, static fn(BlueprintRelationship $left, BlueprintRelationship $right): int => strcmp($left->id, $right->id));

        $rows = array_map(static fn(BlueprintRelationship $relationship): string => self::renderRow($relationship), $relationships);

        $body = $rows === [] ? '' : "\n" . implode('', $rows);

        $content = <<<PHP
            <?php

            declare(strict_types=1);

            // Generated by Waaseyaa\\CLI\\Site\\Blueprint\\ApplicationBlueprintCompiler.
            // One row per blueprint relationship. Consumed by the generated application
            // blueprint provider for referential integrity; do not edit by hand.
            return [{$body}];

            PHP;

        return new BlueprintEmission([
            new GeneratedArtifact('config/waaseyaa-blueprint/relationships.php', $content),
        ]);
    }

    private static function renderRow(BlueprintRelationship $relationship): string
    {
        $id = addslashes($relationship->id);
        $fromEntity = addslashes($relationship->fromEntity);
        $fromField = addslashes($relationship->fromField);
        $toEntity = addslashes($relationship->toEntity);
        $required = $relationship->required ? 'true' : 'false';
        $onDelete = addslashes($relationship->onDelete->value);

        return <<<PHP
                '{$id}' => [
                    'from_entity' => '{$fromEntity}',
                    'from_field' => '{$fromField}',
                    'to_entity' => '{$toEntity}',
                    'cardinality' => {$relationship->cardinality},
                    'required' => {$required},
                    'on_delete' => '{$onDelete}',
                ],

            PHP;
    }
}
