<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Site\Blueprint\Emitter;

use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintRelationship;
use Waaseyaa\SiteContract\Generation\GeneratedArtifact;
use Waaseyaa\SiteContract\SiteManifest;

/**
 * Emits `config/waaseyaa-blueprint/relationships.php`: one deterministic
 * registry row per blueprint relationship — id, from entity and field, to
 * entity, cardinality, required and `on_delete` (FW-SITE-BLUEPRINT-01D
 * decision (f)).
 *
 * Nothing in this slice loads this registry (review round 2, R2-6): it is
 * emitted for a later consumer — a referential-integrity or
 * governance/policy emitter added by a future slice — not read by
 * {@see ProviderRegistrationEmitter}'s generated provider today.
 *
 * @api
 */
final class RelationshipEmitter implements BlueprintArtifactEmitterInterface
{
    public function id(): string
    {
        return 'relationship-registry';
    }

    public function emit(ApplicationBlueprint $blueprint, SiteManifest $manifest): BlueprintEmission
    {
        $relationships = array_values($blueprint->relationships);
        usort($relationships, static fn(BlueprintRelationship $left, BlueprintRelationship $right): int => strcmp($left->id, $right->id));

        $rows = array_map(static fn(BlueprintRelationship $relationship): string => self::renderRow($relationship), $relationships);

        $body = $rows === [] ? '' : "\n" . implode('', $rows);

        $content = <<<PHP
            <?php

            declare(strict_types=1);

            // Generated by Waaseyaa\\CLI\\Site\\Blueprint\\ApplicationBlueprintCompiler.
            // One row per blueprint relationship. Consumed by the generated application
            // blueprint provider for referential integrity; do not edit by hand.
            return [{$body}];

            PHP;

        return new BlueprintEmission([
            new GeneratedArtifact('config/waaseyaa-blueprint/relationships.php', $content),
        ]);
    }

    private static function renderRow(BlueprintRelationship $relationship): string
    {
        $id = self::singleQuoted($relationship->id);
        $fromEntity = self::singleQuoted($relationship->fromEntity);
        $fromField = self::singleQuoted($relationship->fromField);
        $toEntity = self::singleQuoted($relationship->toEntity);
        $required = $relationship->required ? 'true' : 'false';
        $onDelete = self::singleQuoted($relationship->onDelete->value);

        return <<<PHP
                {$id} => [
                    'from_entity' => {$fromEntity},
                    'from_field' => {$fromField},
                    'to_entity' => {$toEntity},
                    'cardinality' => {$relationship->cardinality},
                    'required' => {$required},
                    'on_delete' => {$onDelete},
                ],

            PHP;
    }

    /** Escapes only backslash and single quote so the result is safe to
     * interpolate between single quotes in generated PHP source — unlike
     * `addslashes()`, which also escapes double quotes that single-quoted
     * PHP strings never unescape, corrupting any value containing one.
     */
    private static function singleQuoted(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }
}
