<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Site\Blueprint\Emitter;

use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintWorkflow;
use Waaseyaa\SiteContract\Blueprint\BlueprintWorkflowBinding;
use Waaseyaa\SiteContract\Blueprint\BlueprintWorkflowState;
use Waaseyaa\SiteContract\Blueprint\BlueprintWorkflowTransition;
use Waaseyaa\SiteContract\Generation\GeneratedArtifact;
use Waaseyaa\SiteContract\SiteManifest;

/**
 * Emits one `src/Workflow/<PascalCase(workflow.id)>WorkflowDefinition.php`
 * per blueprint workflow, plus one aggregate `config/sync/workflows.
 * assignments.yml` binding every declared `<entity.id>.<entity.id> =>
 * <workflow.id>` pair across every workflow (#2788, FW-SITE-BLUEPRINT-01E).
 *
 * `DEFINITION` is the exact `Workflow::__construct()` hydration shape
 * ({@see \Waaseyaa\Workflows\Workflow}), matching
 * {@see \Waaseyaa\Workflows\DefaultWorkflows::EDITORIAL} byte-for-byte in
 * structure — `new Workflow(<Generated>WorkflowDefinition::DEFINITION)`
 * constructs a real, valid workflow. A blueprint workflow state has no
 * `default_revision` declaration of its own (unlike `DefaultWorkflows`,
 * which sets it independently of `published`), so this emitter derives
 * `default_revision := published` for every state — the framework's own
 * "published states are what a reader without special access should see"
 * default (`docs/specs/content-workflow.md`).
 *
 * Bundle-less binding: `WorkflowBindingResolver` keys assignments
 * `<entity_type>.<bundle>`, and a blueprint-generated entity is bundle-less
 * (`EntityBase::bundle()` falls back to the entity type id itself when no
 * bundle key is declared) — so every binding row is `<entity.id>.<entity.id>`.
 *
 * Emits nothing when the blueprint declares zero workflows (e.g.
 * `minimal.yaml`).
 *
 * @api
 */
final class WorkflowDefinitionEmitter implements BlueprintArtifactEmitterInterface
{
    private const string ASSIGNMENTS_PATH = 'config/sync/workflows.assignments.yml';

    public function id(): string
    {
        return 'workflow-definition';
    }

    public function emit(ApplicationBlueprint $blueprint, SiteManifest $manifest): BlueprintEmission
    {
        if ($blueprint->workflows === []) {
            return new BlueprintEmission([]);
        }

        $workflows = array_values($blueprint->workflows);
        usort($workflows, static fn(BlueprintWorkflow $left, BlueprintWorkflow $right): int => strcmp($left->id, $right->id));

        $artifacts = [];
        $bindingRows = [];
        foreach ($workflows as $workflow) {
            $className = self::pascalCase($workflow->id) . 'WorkflowDefinition';
            $artifacts[] = new GeneratedArtifact(
                'src/Workflow/' . $className . '.php',
                $this->renderDefinition($workflow, $className),
            );

            $bindings = $workflow->bindings;
            usort($bindings, static fn(BlueprintWorkflowBinding $left, BlueprintWorkflowBinding $right): int => strcmp($left->entity, $right->entity));
            foreach ($bindings as $binding) {
                $bindingRows["{$binding->entity}.{$binding->entity}"] = $workflow->id;
            }
        }
        ksort($bindingRows, SORT_STRING);

        $artifacts[] = new GeneratedArtifact(self::ASSIGNMENTS_PATH, $this->renderAssignments($bindingRows));
        usort($artifacts, static fn(GeneratedArtifact $left, GeneratedArtifact $right): int => strcmp($left->path, $right->path));

        return new BlueprintEmission($artifacts);
    }

    private function renderDefinition(BlueprintWorkflow $workflow, string $className): string
    {
        $states = array_values($workflow->states);
        usort($states, static fn(BlueprintWorkflowState $left, BlueprintWorkflowState $right): int => strcmp($left->id, $right->id));
        $transitions = array_values($workflow->transitions);
        usort($transitions, static fn(BlueprintWorkflowTransition $left, BlueprintWorkflowTransition $right): int => strcmp($left->id, $right->id));

        $stateRows = implode('', array_map($this->renderStateRow(...), $states));
        $transitionRows = implode('', array_map($this->renderTransitionRow(...), $transitions));

        $id = self::singleQuoted($workflow->id);
        $label = self::singleQuoted($workflow->label);
        $initialState = self::singleQuoted($workflow->initialState);

        return <<<PHP
            <?php

            declare(strict_types=1);

            namespace App\\Workflow;

            /**
             * Generated by Waaseyaa\\CLI\\Site\\Blueprint\\ApplicationBlueprintCompiler.
             * Do not edit by hand. Pass DEFINITION to `new Waaseyaa\\Workflows\\Workflow(...)`.
             */
            final class {$className}
            {
                /** @var array<string, mixed> */
                public const array DEFINITION = [
                    'id' => {$id},
                    'label' => {$label},
                    'initial_state' => {$initialState},
                    'states' => [
            {$stateRows}        ],
                    'transitions' => [
            {$transitionRows}        ],
                ];
            }

            PHP;
    }

    private function renderStateRow(BlueprintWorkflowState $state): string
    {
        $id = self::singleQuoted($state->id);
        $label = self::singleQuoted($state->label);
        $published = $state->published ? 'true' : 'false';

        return "            {$id} => ['label' => {$label}, 'published' => {$published}, 'default_revision' => {$published}],\n";
    }

    private function renderTransitionRow(BlueprintWorkflowTransition $transition): string
    {
        $id = self::singleQuoted($transition->id);
        $label = self::singleQuoted($transition->label);
        $from = $transition->from;
        sort($from, SORT_STRING);
        $fromArray = '[' . implode(', ', array_map(self::singleQuoted(...), $from)) . ']';
        $to = self::singleQuoted($transition->to);
        $permission = self::singleQuoted($transition->permission);

        return <<<PHP
                        {$id} => [
                            'label' => {$label},
                            'from' => {$fromArray},
                            'to' => {$to},
                            'permission' => {$permission},
                        ],

            PHP;
    }

    /** @param array<string, string> $bindingRows "entity.entity" => workflow id, sorted by key */
    private function renderAssignments(array $bindingRows): string
    {
        if ($bindingRows === []) {
            return "{}\n";
        }

        $lines = [];
        foreach ($bindingRows as $key => $workflowId) {
            $lines[] = "{$key}: {$workflowId}\n";
        }

        return implode('', $lines);
    }

    private static function singleQuoted(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }

    private static function pascalCase(string $id): string
    {
        return str_replace('_', '', ucwords(str_replace('-', '_', $id), '_'));
    }
}
