<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Access\EntityAccessHandler;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;
use Waaseyaa\User\RoleRepository;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand.
 */
final class EntityAccessChecksTest extends TestCase
{

    public function testAnonCannotUpdate(): void
    {
        $provider = new \App\Provider\ApplicationBlueprintGovernanceServiceProvider();
        $repository = RoleRepository::fromProviders([$provider]);
        $role = $repository->get('viewer');
        self::assertNotNull($role);
        $account = AuthorizationPrincipalFactory::authenticated(1, roles: [$role->id], permissions: $role->permissions);

        $handler = new EntityAccessHandler([new \App\Access\ArticlePolicy()]);
        $subject = new \App\Entity\Article(['id' => 1, 'stage' => 'draft', 'title' => 'Welcome', 'workflow_state' => 'draft']);
        $result = $handler->check($subject, 'update', $account);

        self::assertFalse($result->isAllowed());
    }

    public function testEditorCanUpdateDraft(): void
    {
        $provider = new \App\Provider\ApplicationBlueprintGovernanceServiceProvider();
        $repository = RoleRepository::fromProviders([$provider]);
        $role = $repository->get('editor');
        self::assertNotNull($role);
        $account = AuthorizationPrincipalFactory::authenticated(1, roles: [$role->id], permissions: $role->permissions);

        $handler = new EntityAccessHandler([new \App\Access\ArticlePolicy()]);
        $subject = new \App\Entity\Article(['id' => 1, 'stage' => 'draft', 'title' => 'Welcome', 'workflow_state' => 'draft']);
        $result = $handler->check($subject, 'update', $account);

        self::assertTrue($result->isAllowed());
    }
}
