<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Access\EntityAccessHandler;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;
use Waaseyaa\User\RoleRepository;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Every blueprint entity must deny an anonymous and a
 * permission-less authenticated principal on every operation: no policy grants
 * by default, so absence of a matching condition must never leak into an
 * accidental Allowed. Also asserts the three companion invariants decision (i)
 * assigns to this class: no emitted role is ever `administrator`, every
 * permission a role/transition/policy references is a declared
 * `ApplicationBlueprintPermissions` constant, and every entity with a
 * declared policy has a REFLECTABLE `#[PolicyAttribute]` class (the gap that
 * let a policy compile correctly yet never be discovered at boot — #2788
 * review F1).
 */
final class GovernanceDefaultDenyTest extends TestCase
{

    public function testArticleIsDeniedByDefault(): void
    {
        $handler = new EntityAccessHandler([new \App\Access\ArticlePolicy()]);
        $subject = new \App\Entity\Article(['id' => 1]);

        foreach ([AuthorizationPrincipalFactory::anonymous(), AuthorizationPrincipalFactory::authenticated(1)] as $account) {
            self::assertFalse($handler->check($subject, 'view', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'update', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'delete', $account)->isAllowed());
            self::assertFalse($handler->checkCreateAccess('article', 'article', $account)->isAllowed());
        }
    }

    public function testPersonIsDeniedByDefault(): void
    {
        $handler = new EntityAccessHandler([]);
        $subject = new \App\Entity\Person(['id' => 1]);

        foreach ([AuthorizationPrincipalFactory::anonymous(), AuthorizationPrincipalFactory::authenticated(1)] as $account) {
            self::assertFalse($handler->check($subject, 'view', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'update', $account)->isAllowed());
            self::assertFalse($handler->check($subject, 'delete', $account)->isAllowed());
            self::assertFalse($handler->checkCreateAccess('person', 'person', $account)->isAllowed());
        }
    }

    public function testNoEmittedRoleIsAdministrator(): void
    {
        $provider = new \App\Provider\ApplicationBlueprintGovernanceServiceProvider();
        $repository = RoleRepository::fromProviders([$provider]);
        self::assertNull(
            $repository->get('administrator'),
            "A blueprint-generated role must never be named 'administrator' (Waaseyaa\\User\\User::hasPermission()'s bypass-all-permissions role).",
        );
    }

    public function testEveryReferencedPermissionIsACatalogueConstant(): void
    {
        $catalogue = array_values(new \ReflectionClass(\App\Access\ApplicationBlueprintPermissions::class)->getConstants());
        foreach (['edit article', 'use editorial transition publish', 'view article'] as $permission) {
            self::assertContains($permission, $catalogue, "Permission '{$permission}' referenced by a role, transition, or policy is not a declared ApplicationBlueprintPermissions constant.");
        }
    }

    public function testEveryEntityWithAPolicyHasADiscoverablePolicyAttribute(): void
    {
        foreach ([\App\Access\ArticlePolicy::class] as $policyClass) {
            $attributes = new \ReflectionClass($policyClass)->getAttributes(\Waaseyaa\Access\Gate\PolicyAttribute::class);
            self::assertNotSame([], $attributes, "{$policyClass} must carry #[PolicyAttribute] to be discovered at boot.");
        }
    }
}
