<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Access\AccountInterface;
use Waaseyaa\Access\EntityAccessHandler;
use Waaseyaa\Api\JsonApiController;
use Waaseyaa\Api\ResourceSerializer;
use Waaseyaa\Entity\EntityType;
use Waaseyaa\Entity\EntityTypeInterface;
use Waaseyaa\Entity\EntityTypeManager;
use Waaseyaa\Entity\Repository\EntityRepositoryInterface;
use Waaseyaa\EntityStorage\Connection\SingleConnectionResolver;
use Waaseyaa\EntityStorage\Driver\RevisionableStorageDriver;
use Waaseyaa\EntityStorage\Driver\SqlStorageDriver;
use Waaseyaa\EntityStorage\SqlSchemaHandler;
use Waaseyaa\EntityStorage\Testing\EntityMutationAuthoritySchema;
use Waaseyaa\EntityStorage\Testing\V2EntityRepositoryFactory;
use Waaseyaa\Foundation\Event\SymfonyEventDispatcherAdapter;
use Waaseyaa\Testing\Database\TemporarySqliteDatabase;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Drives every blueprint entity through the real
 * JsonApiController (store/index/show/update/destroy) composed with a real
 * EntityAccessHandler over the generated policy, asserting the exact status
 * and document shape for a denied principal, and for an allowed principal
 * wherever the blueprint declares a policy for that operation. Reads that are
 * denied answer the canonical not-found shape, never an existence oracle.
 */
final class JsonApiGovernanceChecksTest extends TestCase
{

    public function testArticleCreateIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(7));
        $document = $controller->store('article', ['data' => ['type' => 'article', 'attributes' => ['title' => 'Created', 'author' => 7]]]);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    public function testArticleCreateIsAllowedByArticleCreate(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['edit article']));
        $document = $controller->store('article', ['data' => ['type' => 'article', 'attributes' => ['title' => 'Created', 'author' => 42]]]);

        self::assertSame(201, $document->statusCode);
        self::assertSame('Created', $document->toArray()['data']['attributes']['title']);
    }

    public function testArticleListIsEmptyWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->index('article');

        self::assertSame(200, $document->statusCode);
        self::assertSame([], $document->toArray()['data']);
        self::assertSame(0, $document->toArray()['meta']['total']);
    }

    public function testArticleListIsAllowedByArticleView(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['view article']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->index('article');

        self::assertSame(200, $document->statusCode);
        self::assertCount(1, $document->toArray()['data']);
        self::assertSame(1, $document->toArray()['meta']['total']);
        self::assertSame('Welcome', $document->toArray()['data'][0]['attributes']['title']);
    }

    public function testArticleShowIsConcealedWithoutAGrant(): void
    {
        foreach ([AuthorizationPrincipalFactory::authenticated(7), AuthorizationPrincipalFactory::anonymous()] as $account) {
            [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], $account);
            $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
            $document = $controller->show('article', 1);

            // A denied read answers the canonical not-found shape, never an existence oracle.
            self::assertSame(404, $document->statusCode);
            self::assertSame('404', $document->toArray()['errors'][0]['status']);
            self::assertSame('ENTITY_NOT_FOUND', $document->toArray()['errors'][0]['code']);
        }
    }

    public function testArticleShowIsAllowedByArticleView(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['view article']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->show('article', 1);

        self::assertSame(200, $document->statusCode);
        $attributes = $document->toArray()['data']['attributes'];
        self::assertSame('Welcome', $attributes['title']);
        self::assertArrayNotHasKey('author', $attributes, 'authorization inputs never enter the ordinary projection');
        self::assertArrayNotHasKey('workflow_state', $attributes, 'authorization inputs never enter the ordinary projection');
    }

    public function testArticleUpdateIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->update('article', 1, ['data' => ['type' => 'article', 'attributes' => ['title' => 'Updated']]]);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    public function testArticleUpdateIsAllowedByArticlePublishState(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['use editorial transition publish']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->update('article', 1, ['data' => ['type' => 'article', 'attributes' => ['title' => 'Updated']]]);

        self::assertSame(200, $document->statusCode);
        self::assertSame('Updated', $document->toArray()['data']['attributes']['title']);

        // Review gap 3: the entity-level grant must not reassign the owner it was decided on.
        self::assertSame(403, $controller->update('article', 1, ['data' => ['type' => 'article', 'attributes' => ['author' => 999]]])->statusCode);
        // The workflow selector is engine-owned; only a transition moves it.
        self::assertSame(403, $controller->update('article', 1, ['data' => ['type' => 'article', 'attributes' => ['workflow_state' => 'published']]])->statusCode);
    }

    public function testArticleUpdateIsDeniedOutsideTheListedWorkflowStates(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['use editorial transition publish']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'published']);
        $document = $controller->update('article', 1, ['data' => ['type' => 'article', 'attributes' => ['title' => 'Updated']]]);

        self::assertSame(403, $document->statusCode);
    }

    public function testArticleDeleteIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->destroy('article', 1);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    public function testArticleDeleteIsAllowedByArticleDeleteOwn(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(42, permissions: ['edit article']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->destroy('article', 1);

        self::assertSame(204, $document->statusCode);
        self::assertNull($repository->find(1));
    }

    public function testArticleDeleteIsDeniedToANonOwnerHoldingThePermission(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Article::class, 'article', true, [new \App\Access\ArticlePolicy()], AuthorizationPrincipalFactory::authenticated(7, permissions: ['edit article']));
        $this->seedSubject($repository, ['id' => 1, 'title' => 'Welcome', 'author' => 42, 'workflow_state' => 'draft']);
        $document = $controller->destroy('article', 1);

        self::assertSame(403, $document->statusCode);
    }

    public function testPersonCreateIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Person::class, 'person', false, [], AuthorizationPrincipalFactory::authenticated(7));
        $document = $controller->store('person', ['data' => ['type' => 'person', 'attributes' => ['name' => 'Created']]]);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    public function testPersonListIsEmptyWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Person::class, 'person', false, [], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'name' => 'Welcome']);
        $document = $controller->index('person');

        self::assertSame(200, $document->statusCode);
        self::assertSame([], $document->toArray()['data']);
        self::assertSame(0, $document->toArray()['meta']['total']);
    }

    public function testPersonShowIsConcealedWithoutAGrant(): void
    {
        foreach ([AuthorizationPrincipalFactory::authenticated(7), AuthorizationPrincipalFactory::anonymous()] as $account) {
            [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Person::class, 'person', false, [], $account);
            $this->seedSubject($repository, ['id' => 1, 'name' => 'Welcome']);
            $document = $controller->show('person', 1);

            // A denied read answers the canonical not-found shape, never an existence oracle.
            self::assertSame(404, $document->statusCode);
            self::assertSame('404', $document->toArray()['errors'][0]['status']);
            self::assertSame('ENTITY_NOT_FOUND', $document->toArray()['errors'][0]['code']);
        }
    }

    public function testPersonUpdateIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Person::class, 'person', false, [], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'name' => 'Welcome']);
        $document = $controller->update('person', 1, ['data' => ['type' => 'person', 'attributes' => ['name' => 'Updated']]]);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    public function testPersonDeleteIsDeniedWithoutAGrant(): void
    {
        [$controller, $repository, $database] = $this->bootJsonApi(\App\Entity\Person::class, 'person', false, [], AuthorizationPrincipalFactory::authenticated(7));
        $this->seedSubject($repository, ['id' => 1, 'name' => 'Welcome']);
        $document = $controller->destroy('person', 1);

        self::assertSame(403, $document->statusCode);
        self::assertSame('403', $document->toArray()['errors'][0]['status']);
    }

    /**
     * The returned TemporarySqliteDatabase MUST be kept alive by the caller for
     * as long as the controller is used: its destructor deletes the backing
     * SQLite file.
     *
     * @param list<\Waaseyaa\Access\AccessPolicyInterface> $policies
     * @return array{0: JsonApiController, 1: EntityRepositoryInterface, 2: TemporarySqliteDatabase}
     */
    private function bootJsonApi(string $entityClass, string $entityId, bool $revisionable, array $policies, AccountInterface $account): array
    {
        $dispatcher = new SymfonyEventDispatcherAdapter();
        $database = new TemporarySqliteDatabase();
        $resolver = new SingleConnectionResolver($database->database());
        EntityMutationAuthoritySchema::ensure($database->database());
        $handler = new EntityAccessHandler($policies);

        $definition = EntityType::fromClass($entityClass, revisionable: $revisionable);
        $schemaHandler = new SqlSchemaHandler($definition, $database->database());
        $schemaHandler->ensureTable();
        $revisionDriver = null;
        if ($revisionable) {
            $schemaHandler->ensureRevisionTable();
            $revisionDriver = new RevisionableStorageDriver($resolver, $definition);
        }
        $repository = V2EntityRepositoryFactory::createFromSqlStorageDriver(
            $definition,
            new SqlStorageDriver($resolver, $definition->getKeys()['id']),
            $dispatcher,
            $revisionDriver,
            $database->database(),
            accessHandler: $handler,
        );
        $entityTypeManager = new EntityTypeManager(
            $dispatcher,
            repositoryFactory: static fn(string $typeId, EntityTypeInterface $def): EntityRepositoryInterface => $repository,
        );
        $entityTypeManager->registerEntityType($definition);

        $controller = new JsonApiController($entityTypeManager, new ResourceSerializer($entityTypeManager), $handler, $account);

        return [$controller, $repository, $database];
    }

    /** @param array<string, mixed> $values */
    private function seedSubject(EntityRepositoryInterface $repository, array $values): void
    {
        $entity = $repository->create($values);
        $entity->enforceIsNew();
        $repository->save($entity, validate: false);
    }
}
