<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;
use Waaseyaa\User\RoleRepository;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand.
 */
final class RolePermissionChecksTest extends TestCase
{

    public function testEditorPublishes(): void
    {
        $provider = new \App\Provider\ApplicationBlueprintGovernanceServiceProvider();
        $repository = RoleRepository::fromProviders([$provider]);
        $role = $repository->get('editor');
        self::assertNotNull($role);

        $account = AuthorizationPrincipalFactory::authenticated(1, roles: [$role->id], permissions: $role->permissions);

        self::assertTrue($account->hasPermission('use editorial transition publish'));
    }
}
