<?php

declare(strict_types=1);

namespace App\Tests\Blueprint;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Config\ConfigFactory;
use Waaseyaa\Config\Storage\MemoryStorage;
use Waaseyaa\Entity\EntityType;
use Waaseyaa\Entity\EntityTypeManager;
use Waaseyaa\Entity\EntityTypeInterface;
use Waaseyaa\Entity\Repository\EntityRepositoryInterface;
use Waaseyaa\EntityStorage\Connection\SingleConnectionResolver;
use Waaseyaa\EntityStorage\Driver\RevisionableStorageDriver;
use Waaseyaa\EntityStorage\Driver\SqlStorageDriver;
use Waaseyaa\EntityStorage\SqlSchemaHandler;
use Waaseyaa\EntityStorage\Testing\EntityMutationAuthoritySchema;
use Waaseyaa\EntityStorage\Testing\V2EntityRepositoryFactory;
use Waaseyaa\Foundation\Event\SymfonyEventDispatcherAdapter;
use Waaseyaa\Testing\Database\TemporarySqliteDatabase;
use Waaseyaa\Testing\Factory\AuthorizationPrincipalFactory;
use Waaseyaa\User\RoleRepository;
use Waaseyaa\Workflows\Binding\WorkflowBindingResolver;
use Waaseyaa\Workflows\Read\WorkflowEntitySnapshotReader;
use Waaseyaa\Workflows\Transition\TransitionDeniedException;
use Waaseyaa\Workflows\Transition\TransitionService;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Wires a real TransitionService against a
 * TemporarySqliteDatabase-backed EntityRepository, mirroring
 * Waaseyaa\Workflows\Tests\Integration\DepartmentRoutingFlowTest's
 * hand-wired, provider-free construction.
 */
final class WorkflowTransitionChecksTest extends TestCase
{

    public function testViewerCannotPublish(): void
    {
        $provider = new \App\Provider\ApplicationBlueprintGovernanceServiceProvider();
        $repository = RoleRepository::fromProviders([$provider]);
        $role = $repository->get('viewer');
        self::assertNotNull($role);
        $account = AuthorizationPrincipalFactory::authenticated(1, roles: [$role->id], permissions: $role->permissions);

        [$transitionService, $entityRepository, $temporaryDatabase] = $this->bootTransitionService(
            \App\Entity\Article::class,
            'article',
            'editorial',
            \App\Workflow\EditorialWorkflowDefinition::DEFINITION,
        );
        $entity = $entityRepository->create(['id' => 1]);
        $entity->enforceIsNew();
        $entityRepository->save($entity, validate: false);

        try {
            $transitionService->transition($entity, 'publish', $account);
            self::fail('Expected a TransitionDeniedException.');
        } catch (TransitionDeniedException $exception) {
            self::assertSame(TransitionDeniedException::REASON_PERMISSION, $exception->reason);
        }
    }

    /**
     * The returned TemporarySqliteDatabase MUST be kept alive by the caller for
     * as long as the repository is used: its destructor deletes the backing
     * SQLite file, and nothing else in this array holds a reference to it.
     *
     * @return array{0: TransitionService, 1: EntityRepositoryInterface, 2: TemporarySqliteDatabase}
     */
    private function bootTransitionService(string $entityClass, string $entityId, string $workflowId, array $workflowDefinition): array
    {
        $dispatcher = new SymfonyEventDispatcherAdapter();
        $database = new TemporarySqliteDatabase();
        $resolver = new SingleConnectionResolver($database->database());
        EntityMutationAuthoritySchema::ensure($database->database());

        $definition = EntityType::fromClass($entityClass, revisionable: true);
        $schemaHandler = new SqlSchemaHandler($definition, $database->database());
        $schemaHandler->ensureTable();
        $schemaHandler->ensureRevisionTable();
        $repository = V2EntityRepositoryFactory::createFromSqlStorageDriver(
            $definition,
            new SqlStorageDriver($resolver, $definition->getKeys()['id']),
            $dispatcher,
            new RevisionableStorageDriver($resolver, $definition),
            $database->database(),
        );

        // Mirrors WorkflowServiceProvider::register()'s 'workflow' EntityType
        // declaration (docs/specs/content-workflow.md): the bound content
        // entity's own workflow-state condition is checked purely in-memory
        // (AuthorizationInputReader), but WorkflowBindingResolver itself always
        // loads the bound Workflow config entity through a real repository.
        $workflowType = new EntityType(
            id: 'workflow',
            label: 'Workflow',
            class: \Waaseyaa\Workflows\Workflow::class,
            keys: ['id' => 'id', 'label' => 'label'],
            _fieldDefinitions: [
                'id' => ['type' => 'string', 'read' => \Waaseyaa\Entity\FieldReadLevel::Public],
                'label' => ['type' => 'string', 'read' => \Waaseyaa\Entity\FieldReadLevel::Public],
                'initial_state' => ['type' => 'string', 'stored' => \Waaseyaa\Field\FieldStorage::Data, 'read' => \Waaseyaa\Entity\FieldReadLevel::Public],
                'states' => ['type' => 'json', 'stored' => \Waaseyaa\Field\FieldStorage::Data, 'read' => \Waaseyaa\Entity\FieldReadLevel::Public],
                'transitions' => ['type' => 'json', 'stored' => \Waaseyaa\Field\FieldStorage::Data, 'read' => \Waaseyaa\Entity\FieldReadLevel::Public],
            ],
        );
        $workflowSchemaHandler = new SqlSchemaHandler($workflowType, $database->database());
        $workflowSchemaHandler->ensureTable();
        $workflowRepository = V2EntityRepositoryFactory::createFromSqlStorageDriver(
            $workflowType,
            new SqlStorageDriver($resolver, 'id'),
            $dispatcher,
            null,
            $database->database(),
        );
        $workflow = $workflowRepository->create($workflowDefinition);
        $workflow->enforceIsNew();
        $workflowRepository->save($workflow, validate: false);

        $repositories = [$entityId => $repository, 'workflow' => $workflowRepository];
        $entityTypeManager = new EntityTypeManager(
            $dispatcher,
            repositoryFactory: static fn(string $typeId, EntityTypeInterface $def): EntityRepositoryInterface => $repositories[$typeId],
        );
        $entityTypeManager->registerEntityType($definition);
        $entityTypeManager->registerEntityType($workflowType);

        $configStorage = new MemoryStorage();
        $configStorage->write('workflows.assignments', ["{$entityId}.{$entityId}" => $workflowId]);
        $configFactory = new ConfigFactory($configStorage, $dispatcher);

        $bindings = new WorkflowBindingResolver($configFactory, $entityTypeManager);
        $transitionService = new TransitionService(
            bindings: $bindings,
            entityTypeManager: $entityTypeManager,
            workflowValues: new WorkflowEntitySnapshotReader(),
        );

        return [$transitionService, $repository, $database];
    }
}
