<?php

declare(strict_types=1);

// Migrated by bin/migrate-surface-map from docs/public-surface-map.php
// and docs/public-surface-map.md (FW-DELIVERY-SURFACE-01 / #2901). This
// file, not the generated docs/public-surface-map.*, is the editable
// authority — see docs/specs/public-surface-declarations.md.
return [
    'entries' => [
        ['fqcn' => 'Waaseyaa\\EntityStorage\\AggregateMutationRepositoryInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\BackendResolver', 'disposition' => 'public', 'purpose' => 'Resolves which backend handles a given `FieldDefinition` (M-001, WP02)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\BackendRegistrar', 'disposition' => 'public', 'purpose' => 'Registers field storage backends by id for an entity type (M-001, WP01)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\BackendRegistrarFactory', 'disposition' => 'public', 'purpose' => 'Creates a `BackendRegistrar` bound to a specific entity type (M-001, WP01)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageBackendGateway', 'disposition' => 'public', 'purpose' => 'Registrar-owned V2 facade that reserves strict audit and never exposes the implementation (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageBackendV2Interface', 'disposition' => 'public', 'purpose' => 'Active fingerprinted privileged backend SPI; accepts only registrar-issued roles and opaque inputs (#2064 WP4)', 'ref' => '#2064'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayAttempt', 'disposition' => 'public', 'purpose' => 'Value-free strict-audit descriptor reserved before invocation (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayAuditReceipt', 'disposition' => 'public', 'purpose' => 'Opaque receipt for strict attempt finalization (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayFailure', 'disposition' => 'public', 'purpose' => 'Value-free failure record including whether backend invocation began (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayInput', 'disposition' => 'public', 'purpose' => 'Opaque non-serializable boundary-bound backend input handle (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayInvocation', 'disposition' => 'public', 'purpose' => 'Backend-only invocation exposed after successful role/boundary validation (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayOperation', 'disposition' => 'public', 'purpose' => 'Closed read/write/delete/query-support invocation vocabulary (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayOutput', 'disposition' => 'public', 'purpose' => 'Opaque non-serializable boundary-bound backend result handle (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\FieldStorageGatewayRole', 'disposition' => 'public', 'purpose' => 'Opaque registrar-issued role required to unwrap inputs and construct results (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\HasFieldStorageBackendsV2Interface', 'disposition' => 'public', 'purpose' => 'Provider capability for reviewed V2 field-storage implementations (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\IsFrameworkBackendProviderV2Interface', 'disposition' => 'public', 'purpose' => 'Marker allowing framework-owned V2 providers to claim reserved backend ids (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\ReservedBackendIds', 'disposition' => 'public', 'purpose' => 'String constants for built-in backend ids: `SQL_BLOB`, `SQL_COLUMN`, `VECTOR` (M-001, WP01)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\SqlBlobBackend', 'disposition' => 'public', 'purpose' => 'Stores field values in a JSON `_data` blob column; `supportsQuery()` always false (M-001, WP03)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\SqlColumnBackend', 'disposition' => 'public', 'purpose' => 'Stores each field in a dedicated SQL column; `supportsQuery()` true for non-vector types (M-001, WP05)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\SqlColumnQueryTranslator', 'disposition' => 'public', 'purpose' => 'Translates field-level query predicates to SQL for `SqlColumnBackend` (M-001, WP05)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\SqlColumnSchemaBuilder', 'disposition' => 'public', 'purpose' => 'Builds SQL column schema for `SqlColumnBackend` (M-001, WP05)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\StrictFieldStorageGatewayAuditInterface', 'disposition' => 'public', 'purpose' => 'Synchronous reserve/success/failure audit required for V2 gateway activation (#2064 WP3)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Backend\\TypeMapping', 'disposition' => 'public', 'purpose' => 'Maps `FieldDefinition` type strings to DBAL column types (M-001, WP05)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Connection\\ConnectionResolverInterface', 'disposition' => 'public', 'purpose' => 'Resolves named database connections; multi-tenancy seam for entity storage'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\ContextualEntityLoaderInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\CoordinatorLifecycleDispatcher', 'disposition' => 'public', 'purpose' => 'Dispatches lifecycle events from the coordinator (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\EntityStorageDriverInterface', 'disposition' => 'public', 'purpose' => 'Low-level persistence SPI: raw row I/O without hydration or event dispatch. Adds `findTranslations(EntityInterface): array<string, EntityInterface>` (M-006, WP10)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\EntityStorageDriverV2Interface', 'disposition' => 'public', 'purpose' => 'Additive boundary-bound opaque-row storage SPI: reads return `StorageRow`/`StorageRowSet` and writes accept `StorageSnapshot`; unrelated boundary tokens cannot unwrap them, and V1 remains behavior-compatible during dormant stages'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\InMemoryStorageDriverV2', 'disposition' => 'public', 'purpose' => 'Opaque V2 adapter over the first-party in-memory ordinary storage backend'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\LangcodePeerStorageDriverV2Interface', 'disposition' => 'public', 'purpose' => 'Optional opaque-snapshot capability for tenancy-safe `(entity id, langcode)` peer writes without collapsing sibling languages'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\RevisionableStorageDriver', 'disposition' => 'public', 'purpose' => 'Driver-level two-axis save/load orchestration: composes `RevisionTableBuilder` + `TranslationSchemaHandler` and honours `SaveContext::withTranslations()` for atomic multi-language revision writes (M-004, WP03 + WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\RevisionableStorageDriverV2', 'disposition' => 'public', 'purpose' => 'Opaque V2 adapter used by the repository for the first-party revision/langcode storage backend'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\RevisionableStorageDriverV2Interface', 'disposition' => 'public', 'purpose' => 'Additive opaque revision SPI mirroring current revision and langcode operations while replacing raw read/write arrays with boundary-bound rows and snapshots'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Driver\\SqlStorageDriverV2', 'disposition' => 'public', 'purpose' => 'Opaque V2 adapter over the first-party SQL ordinary storage backend'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\EntityStorageCoordinator', 'disposition' => 'public', 'purpose' => 'Fan-out engine dispatching read/write/delete to all registered backends (M-001, WP02)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\AbortOperationException', 'disposition' => 'public', 'purpose' => 'Thrown from `BeforeSave`/`BeforeDelete` listener to abort the operation (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\AfterDeleteEvent', 'disposition' => 'public', 'purpose' => 'Dispatched after all backends confirm delete (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\AfterSaveEvent', 'disposition' => 'public', 'purpose' => 'Dispatched after all backends commit; not dispatched on partial failure (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\BeforeDeleteEvent', 'disposition' => 'public', 'purpose' => 'Dispatched before any backend delete (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\BeforeSaveEvent', 'disposition' => 'public', 'purpose' => 'Dispatched before any backend write; listeners may abort via `AbortOperationException` (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\EntityLifecycleEventInterface', 'disposition' => 'public', 'purpose' => 'Marker for all four coordinator lifecycle events (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Event\\EntityMutationAuthorityBackfilledEvent', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\BundleAmbiguousFieldException', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\BundleUniqueKeyConflictException', 'disposition' => 'public', 'purpose' => 'Stable repository conflict for a database-enforced bundle key (`BUNDLE_UNIQUE_KEY_CONFLICT`) (#2603)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\BundleUniqueKeyMigrationException', 'disposition' => 'public', 'purpose' => 'Stable schema-sync refusal when existing bundle rows duplicate a declared key (`bundle_unique_key_duplicates`) (#2603)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\PartialSaveException', 'disposition' => 'public', 'purpose' => 'Thrown on backend fan-out failure, including first-backend failure with an empty committed set; carries `$errorCode` (M-001, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\StorageMigrationException', 'disposition' => 'public', 'purpose' => 'Typed exception for storage-migration / two-axis schema failures during kernel boot, schema sync, or migration generator runs. Stable `errorCode` strings: `no_op_promotion`, `unsupported_two_axis_field` (M-004, WP04)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\UnknownBackendException', 'disposition' => 'public', 'purpose' => 'Thrown when a field references an unregistered backend id (M-001, WP02)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\UnknownFieldException', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\UnsupportedListingException', 'disposition' => 'public', 'purpose' => 'Thrown when listing is unsupported by the active backend (M-001, WP06)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Exception\\UnsupportedQueryException', 'disposition' => 'public', 'purpose' => 'Thrown when a query operator is unsupported by the active backend (M-001, WP01)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Hydration\\EntityInstantiator', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\LegacyMutationAuthorityBackfillRepositoryInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Listing\\TwoAxisFilterResolver', 'disposition' => 'public', 'purpose' => 'Resolves listing filters against two-axis storage: joins `<entity>__revision` to `<entity>__translation__revision` and applies langcode + revision-window selection (M-004, WP07)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Query\\DefinitionValidator', 'disposition' => 'public', 'purpose' => 'Validates `FieldDefinition` objects at registration time; throws `UnsupportedQueryException` (M-001, WP06)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Query\\EntityQuery', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\RevisionPruningPolicy', 'disposition' => 'public', 'purpose' => 'Immutable value object describing how many revisions to keep (M-001, WP08)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\RevisionPruningReport', 'disposition' => 'public', 'purpose' => 'Result of a pruning run: counts of deleted and retained revisions (M-001, WP08)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Revision\\RevisionPruningPolicy', 'disposition' => 'public', 'purpose' => 'Two-axis pruning policy value object; keeps the M-001 `RevisionPruningPolicy` surface intact while extending semantics to per-langcode revision counts (M-004, WP05)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\SaveContext', 'disposition' => 'public', 'purpose' => 'Immutable value object passed to save operations; carries revision flags and translation langcode. `withLangcode(string $langcode): self` returns an immutable copy targeting a translation write (M-001, WP04 + M-006, WP07)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Schema\\EntityStorageSchemaTransitionInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Schema\\RevisionTableBuilder', 'disposition' => 'public', 'purpose' => 'Creates the `{entity_type}_revision` schema table (M-001, WP07)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Schema\\TranslationSchemaHandler', 'disposition' => 'public', 'purpose' => 'Emits the `<entity>__translation__revision` table for two-axis entities; pairs with `RevisionTableBuilder::buildTwoAxis()` (M-004, WP02)'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Tenancy\\CommunityTranslationPeerRepairReport', 'disposition' => 'public', 'purpose' => 'Machine-readable examined, eligible, repaired, skipped, and dry-run counts from translation-peer repair'],
        ['fqcn' => 'Waaseyaa\\EntityStorage\\Tenancy\\CommunityTranslationPeerRepairer', 'disposition' => 'public', 'purpose' => 'Explicit fail-closed repair for legacy translation peers with empty community discriminators'],
    ],
    'notes' => [
        '`EntityRepository::findTranslations(EntityInterface): array<string, EntityInterface>` (method): Returns every translation of the given entity, keyed by langcode, default-langcode first; single SQL query (M-006, WP10)',
        '`SaveContext::withTranslations(array $langcodes): self` (method): Immutable copy carrying a `[langcode => values]` map for atomic multi-language revision writes; rejected if empty. Pairs with `withLangcode()` for single-language writes (M-004, WP03)',
        '`EntityTranslationException::historicalRevisionWrite(int $vid, string $langcode): self` (factory): Raised when a write targets a historical (non-tip) revision in a two-axis entity; stable `errorCode` `historical_revision_write` (M-004, WP04)',
    ],
];
