<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Tests\Unit\Handler;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Waaseyaa\CLI\Command\HandlerArgument;
use Waaseyaa\CLI\Command\HandlerArgumentMode;
use Waaseyaa\CLI\Command\HandlerCommand;
use Waaseyaa\CLI\Command\HandlerOption;
use Waaseyaa\CLI\Command\HandlerOptionMode;
use Waaseyaa\CLI\Handler\MakeContentTypeHandler;
use Waaseyaa\CLI\Site\Blueprint\Emitter\EntityClassEmitter;
use Waaseyaa\CLI\Site\Blueprint\Emitter\RelationshipEmitter;
use Waaseyaa\CLI\Site\Scaffold\ContentTypeScaffoldCompiler;
use Waaseyaa\CLI\Testing\CliTester;
use Waaseyaa\Field\AbstractFieldType;
use Waaseyaa\Field\Attribute\FieldType;
use Waaseyaa\Field\FieldScaffoldProjection;
use Waaseyaa\Field\FieldTypeManager;
use Waaseyaa\Field\FieldValueKind;
use Waaseyaa\Field\FieldValueKindProviderInterface;
use Waaseyaa\SiteContract\Blueprint\ApplicationBlueprint;
use Waaseyaa\SiteContract\Blueprint\BlueprintEntity;
use Waaseyaa\SiteContract\Blueprint\BlueprintEntityKeys;
use Waaseyaa\SiteContract\Blueprint\BlueprintField;
use Waaseyaa\SiteContract\Blueprint\BlueprintFieldType;
use Waaseyaa\SiteContract\Blueprint\BlueprintOnDelete;
use Waaseyaa\SiteContract\Blueprint\BlueprintRelationship;
use Waaseyaa\SiteContract\Blueprint\BlueprintStorage;
use Waaseyaa\SiteContract\SiteManifest;
use Waaseyaa\SiteContract\SiteManifestParser;

#[CoversClass(MakeContentTypeHandler::class)]
final class MakeContentTypeHandlerTest extends TestCase
{
    private string $root;

    protected function setUp(): void
    {
        $this->root = sys_get_temp_dir() . '/waaseyaa_mct_' . uniqid();
        mkdir($this->root, 0o755, true);
        file_put_contents(
            $this->root . '/composer.json',
            json_encode(['name' => 'app/app', 'autoload' => ['psr-4' => ['App\\' => 'src/']]], \JSON_PRETTY_PRINT),
        );
        self::initializeSite($this->root);
    }

    /**
     * #2789 phase 2: the scaffold publishes through the shared generation
     * custody, which records unit ownership in `.waaseyaa/generated.json`.
     * There is no roster to record it in before `site:init` has run, so a
     * scaffolding fixture now starts from an initialized site — the order the
     * canonical lifecycle already prescribes (`site:init` precedes everything
     * that owns generated bytes).
     */
    private static function initializeSite(string $root): void
    {
        $manifest = <<<'YAML'
            schema: waaseyaa.site
            version: 1
            generator_version: 1
            application: {id: example, name: Example, canonical_origin: {config_key: APP_ORIGIN}}
            framework: {revision_policy: exact-lock, observed_lock_sha256: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
            content_types: [{id: page, canonical_route: '/{slug}'}]
            capabilities:
              - id: publishing
                state: active
                package: waaseyaa/publishing
                provider: site.publishing
                configuration_authority: .waaseyaa/site.yaml#/capabilities/publishing
                public_routes: []
                data_classification: public
                lifecycle: [create, publish]
                verification: [tests/Acceptance/SiteGoldenPathTest.php]
            personal_data_stores: []
            recipes: []
            verification: {command: bin/maintenance/site-verify}
            YAML;
        new \Waaseyaa\CLI\Site\SiteInitializationService($root)->initialize(
            new \Waaseyaa\SiteContract\Generation\SiteArtifactRenderer()->render(
                new \Waaseyaa\SiteContract\SiteManifestParser()->parse($manifest),
            ),
        );
    }

    protected function tearDown(): void
    {
(new Filesystem())->remove($this->root);
    }

    private function command(?FieldScaffoldProjection $fieldProjection = null): HandlerCommand
    {
        $handler = $fieldProjection === null
            ? new MakeContentTypeHandler(projectRoot: $this->root, fieldProjection: new FieldScaffoldProjection(new FieldTypeManager()))
            : new MakeContentTypeHandler(projectRoot: $this->root, fieldProjection: $fieldProjection);

        return new HandlerCommand(
            name: 'make:content-type',
            description: 'Scaffold a content type',
            arguments: [new HandlerArgument(name: 'name', mode: HandlerArgumentMode::Required, description: 'name')],
            options: [
                new HandlerOption(name: 'fields', mode: HandlerOptionMode::Required, description: 'fields', default: 'title:string,body:text'),
                new HandlerOption(name: 'force', mode: HandlerOptionMode::None, description: 'force'),
            ],
            handler: \Closure::fromCallable([$handler, 'execute']),
        );
    }

    private function emptyContainer(): ContainerInterface
    {
        return new class implements ContainerInterface {
            public function get(string $id): mixed
            {
                throw new \RuntimeException('not used');
            }

            public function has(string $id): bool
            {
                return false;
            }
        };
    }

    private function runMake(array $argv, ?FieldScaffoldProjection $fieldProjection = null): CliTester
    {
        $tester = CliTester::for($this->command($fieldProjection), $this->emptyContainer());
        $tester->executeMap($argv);

        return $tester;
    }

    #[Test]
    public function realCommandProviderUsesTheManifestFieldRegistry(): void
    {
        $type = "scaffold'quoted\\kind";
        $manifest = new \Waaseyaa\Foundation\Discovery\PackageManifest(
            providers: [\Waaseyaa\CLI\Provider\MakeServiceProviderB::class],
            fieldTypes: [$type => CliQuotedScaffoldFieldType::class],
        );
        $fields = FieldTypeManager::fromManifest($manifest->fieldTypes);
        $dispatcher = new \Symfony\Component\EventDispatcher\EventDispatcher();
        $entityTypes = new \Waaseyaa\Entity\EntityTypeManager(
            eventDispatcher: $dispatcher,
            fieldRegistry: new \Waaseyaa\Field\FieldDefinitionRegistry($fields),
        );
        $registry = new \Waaseyaa\Foundation\Kernel\Bootstrap\ProviderRegistry(new \Waaseyaa\Foundation\Log\NullLogger());
        $providers = $registry->discoverAndRegister(
            manifest: $manifest,
            projectRoot: $this->root,
            config: [],
            entityTypeManager: $entityTypes,
            database: $this->createStub(\Waaseyaa\Database\DatabaseInterface::class),
            dispatcher: $dispatcher,
        );
        $registry->boot($providers);
        $commands = iterator_to_array($providers[0]->consoleCommands(), false);
        $command = array_values(array_filter($commands, static fn($command): bool => $command->getName() === 'make:content-type'))[0];
        $tester = CliTester::for($command, $this->emptyContainer());
        $tester->executeMap(['name' => 'manifestarticle', '--fields' => 'body:' . $type]);
        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());
        $source = (string) file_get_contents($this->root . '/src/Entity/Manifestarticle.php');
        self::assertStringContainsString('type: ' . var_export($type, true), $source);
    }

    #[Test]
    public function registryFieldIdsRemainLiteralInGeneratedPhp(): void
    {
        $type = "scaffold'quoted\\kind";
        $projection = new FieldScaffoldProjection(new FieldTypeManager(
            extensionClasses: [$type => CliQuotedScaffoldFieldType::class],
        ));
        $tester = $this->runMake(['name' => 'quoted', '--fields' => 'body:' . $type], $projection);
        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());
        $file = $this->root . '/src/Entity/Quoted.php';
        exec('php -l ' . escapeshellarg($file) . ' 2>&1', $output, $exit);
        self::assertSame(0, $exit, implode("\n", $output));
        require $file;
        $attribute = new \ReflectionProperty(\App\Entity\Quoted::class, 'body')
            ->getAttributes(\Waaseyaa\Entity\Attribute\Field::class)[0]->newInstance();
        self::assertSame($type, $attribute->type);
    }

    #[Test]
    public function scalarProjectionDoesNotChangeTheAuthoredLabelSelection(): void
    {
        $tester = $this->runMake(['name' => 'labelled', '--fields' => 'body:text,title:string']);
        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());
        $source = (string) file_get_contents($this->root . '/src/Entity/Labelled.php');
        self::assertStringContainsString("label: 'title'", $source);
    }

    #[Test]
    public function manualTextAndDatetimePropertiesMatchTheBlueprintProjection(): void
    {
        $constructorParameters = array_map(
            static fn(\ReflectionParameter $parameter): string => $parameter->getName(),
            new \ReflectionClass(MakeContentTypeHandler::class)->getConstructor()?->getParameters() ?? [],
        );
        self::assertContains('fieldProjection', $constructorParameters);

        $tester = $this->runMake([
            'name' => 'story',
            '--fields' => 'body:text,published_at:datetime',
        ]);
        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());

        $manual = (string) file_get_contents($this->root . '/src/Entity/Story.php');
        $blueprint = $this->blueprintEntitySource([
            'body' => new BlueprintField('body', BlueprintFieldType::Text, false, 1, false, false, false),
            'published_at' => new BlueprintField('published_at', BlueprintFieldType::DateTime, false, 1, false, false, false),
        ]);

        foreach (['body', 'published_at'] as $fieldName) {
            self::assertSame(
                self::propertyLine($blueprint, $fieldName),
                self::propertyLine($manual, $fieldName),
                "{$fieldName} must use the same PHP property projection in both authoring paths.",
            );
        }
    }

    #[Test]
    public function aRegisteredExtensionIsAdmittedWithoutEditingTheScaffoldCompiler(): void
    {
        $constructorParameters = array_map(
            static fn(\ReflectionParameter $parameter): string => $parameter->getName(),
            new \ReflectionClass(MakeContentTypeHandler::class)->getConstructor()?->getParameters() ?? [],
        );
        self::assertContains('fieldProjection', $constructorParameters);

        $projection = new FieldScaffoldProjection(new FieldTypeManager(
            extensionClasses: ['scaffold_markdown' => CliScaffoldMarkdownFieldType::class],
        ));
        $tester = $this->runMake(
            ['name' => 'story', '--fields' => 'body:scaffold_markdown'],
            $projection,
        );

        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());
        $entity = (string) file_get_contents($this->root . '/src/Entity/Story.php');
        self::assertStringContainsString("type: 'scaffold_markdown'", $entity);
        self::assertStringContainsString('public mixed $body = null;', $entity);
        self::assertFalse(new \ReflectionClass(ContentTypeScaffoldCompiler::class)->hasConstant('TYPE_MAP'));
    }

    #[Test]
    public function authoredReferencesKeepTargetMetadataWhileBlueprintRelationshipsKeepRelationshipSemantics(): void
    {
        $manualResult = $this->runMake([
            'name' => 'story',
            '--fields' => 'title:string,author:entity_reference:user',
        ]);
        self::assertSame(0, $manualResult->getExitCode(), $manualResult->getStderr());
        $manual = (string) file_get_contents($this->root . '/src/Entity/Story.php');
        self::assertStringContainsString("settings: ['target_entity_type_id' => 'user']", $manual);

        $manifest = $this->blueprintManifest();
        $blueprint = new ApplicationBlueprint(
            contractVersion: 1,
            entities: [
                'story' => new BlueprintEntity(
                    id: 'story',
                    label: 'Story',
                    storage: BlueprintStorage::SqlBlob,
                    revisionable: false,
                    translatable: false,
                    keys: new BlueprintEntityKeys(id: 'id', uuid: 'uuid', label: 'title'),
                    fields: [
                        'title' => new BlueprintField('title', BlueprintFieldType::String, false, 1, false, false, false),
                    ],
                ),
                'user' => new BlueprintEntity(
                    id: 'user',
                    label: 'User',
                    storage: BlueprintStorage::SqlBlob,
                    revisionable: false,
                    translatable: false,
                    keys: new BlueprintEntityKeys(id: 'id', uuid: 'uuid', label: 'name'),
                    fields: [
                        'name' => new BlueprintField('name', BlueprintFieldType::String, false, 1, false, false, false),
                    ],
                ),
            ],
            relationships: [
                'story_author' => new BlueprintRelationship(
                    id: 'story_author',
                    fromEntity: 'story',
                    fromField: 'author',
                    toEntity: 'user',
                    cardinality: 1,
                    required: true,
                    onDelete: BlueprintOnDelete::Restrict,
                ),
            ],
            permissions: [],
            roles: [],
            policies: [],
            workflows: [],
            fixtures: [],
            checks: [],
        );

        $entityEmission = new EntityClassEmitter()->emit($blueprint, $manifest);
        $story = array_values(array_filter(
            $entityEmission->artifacts,
            static fn(object $artifact): bool => $artifact->path === 'src/Entity/Story.php',
        ))[0]->content;
        self::assertStringContainsString("settings: ['target_entity_type_id' => 'user']", $story);

        $relationshipEmission = new RelationshipEmitter()->emit($blueprint, $manifest);
        self::assertStringContainsString("'cardinality' => 1", $relationshipEmission->artifacts[0]->content);
        self::assertStringContainsString("'required' => true", $relationshipEmission->artifacts[0]->content);
        self::assertStringContainsString("'on_delete' => 'restrict'", $relationshipEmission->artifacts[0]->content);
    }

    /** @param array<string, BlueprintField> $fields */
    private function blueprintEntitySource(array $fields): string
    {
        $blueprint = new ApplicationBlueprint(
            contractVersion: 1,
            entities: [
                'story' => new BlueprintEntity(
                    id: 'story',
                    label: 'Story',
                    storage: BlueprintStorage::SqlBlob,
                    revisionable: false,
                    translatable: false,
                    keys: new BlueprintEntityKeys(id: 'id', uuid: 'uuid', label: array_key_first($fields)),
                    fields: $fields,
                ),
            ],
            relationships: [],
            permissions: [],
            roles: [],
            policies: [],
            workflows: [],
            fixtures: [],
            checks: [],
        );

        return new EntityClassEmitter()->emit($blueprint, $this->blueprintManifest())->artifacts[0]->content;
    }

    private function blueprintManifest(): SiteManifest
    {
        $repoRoot = (string) realpath(__DIR__ . '/../../../../../');

        return new SiteManifestParser()->parse(
            (string) file_get_contents($repoRoot . '/packages/site-contract/tests/Fixtures/Blueprint/valid/minimal.yaml'),
        );
    }

    private static function propertyLine(string $source, string $fieldName): string
    {
        self::assertMatchesRegularExpression(
            '/^    public [^\n]+ \\$' . preg_quote($fieldName, '/') . ' = [^\n]+;$/m',
            $source,
        );
        preg_match(
            '/^    public [^\n]+ \\$' . preg_quote($fieldName, '/') . ' = [^\n]+;$/m',
            $source,
            $matches,
        );

        return $matches[0];
    }

    #[Test]
    public function generates_a_usable_content_type(): void
    {
        $tester = $this->runMake([
            'name' => 'story',
            '--fields' => 'title:string,body:text,source_url:string,author:entity_reference:user',
        ]);

        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());

        $entity = (string) file_get_contents($this->root . '/src/Entity/Story.php');
        self::assertStringContainsString('namespace App\\Entity;', $entity);
        self::assertStringContainsString("#[ContentEntityType(id: 'story', label: 'Story')]", $entity);
        // Label key uses the first string field.
        self::assertStringContainsString("#[ContentEntityKeys(label: 'title')]", $entity);
        self::assertStringContainsString('final class Story extends ContentEntityBase', $entity);
        // Published status field is added automatically.
        self::assertStringContainsString("#[Field(type: 'boolean', label: 'Published', default: true)]", $entity);
        self::assertStringContainsString('public bool $status = true;', $entity);
        // Requested fields with correct PHP types.
        self::assertStringContainsString('public string $title', $entity);
        self::assertStringContainsString("type: 'text'", $entity);
        self::assertStringContainsString("public string \$body = '';", $entity);
        // entity_reference carries target metadata — no constructor spelunking.
        self::assertStringContainsString("settings: ['target_entity_type_id' => 'user']", $entity);
        self::assertStringContainsString('public ?int $author', $entity);
    }

    #[Test]
    public function generates_and_registers_a_provider(): void
    {
        $this->runMake(['name' => 'story', '--fields' => 'title:string']);

        $provider = (string) file_get_contents($this->root . '/src/Provider/StoryServiceProvider.php');
        self::assertStringContainsString('final class StoryServiceProvider extends ServiceProvider', $provider);
        self::assertStringContainsString("EntityType::fromClass(Story::class, group: 'content')", $provider);

        $composer = json_decode((string) file_get_contents($this->root . '/composer.json'), true, 512, \JSON_THROW_ON_ERROR);
        self::assertContains('App\\Provider\\StoryServiceProvider', $composer['extra']['waaseyaa']['providers']);
    }

    #[Test]
    public function provider_registration_is_idempotent(): void
    {
        $this->runMake(['name' => 'story', '--fields' => 'title:string']);
        $second = $this->runMake(['name' => 'story', '--fields' => 'title:string', '--force' => true]);

        self::assertSame(0, $second->getExitCode(), $second->getStderr());
        $composer = json_decode((string) file_get_contents($this->root . '/composer.json'), true, 512, \JSON_THROW_ON_ERROR);
        $providers = $composer['extra']['waaseyaa']['providers'];
        self::assertSame(['App\\Provider\\StoryServiceProvider'], array_values($providers), 'provider listed exactly once');
    }

    #[Test]
    public function refuses_to_overwrite_without_force(): void
    {
        $this->runMake(['name' => 'story', '--fields' => 'title:string']);
        $again = $this->runMake(['name' => 'story', '--fields' => 'title:string']);

        self::assertSame(1, $again->getExitCode());
        self::assertStringContainsString('already exists', $again->getStderr());
    }

    #[Test]
    public function rejects_entity_reference_without_target(): void
    {
        $tester = $this->runMake(['name' => 'story', '--fields' => 'author:entity_reference']);

        self::assertSame(1, $tester->getExitCode());
        self::assertStringContainsString('needs a target', $tester->getStderr());
    }

    #[Test]
    public function rejects_unknown_field_type(): void
    {
        $tester = $this->runMake(['name' => 'story', '--fields' => 'title:wat']);

        self::assertSame(1, $tester->getExitCode());
        self::assertStringContainsString('Unknown field type', $tester->getStderr());
    }

    #[Test]
    public function rejects_a_quote_breakout_payload_in_name_and_writes_no_file(): void
    {
        $tester = $this->runMake([
            'name' => "foo', system('touch pwned'); //",
            '--fields' => 'title:string',
        ]);

        self::assertSame(1, $tester->getExitCode());
        self::assertStringContainsString('Invalid name', $tester->getStderr());
        self::assertDirectoryDoesNotExist($this->root . '/src/Entity');
        self::assertDirectoryDoesNotExist($this->root . '/src/Provider');
    }

    #[Test]
    public function rejects_a_path_traversal_name_and_writes_no_file(): void
    {
        $tester = $this->runMake([
            'name' => '../evil',
            '--fields' => 'title:string',
        ]);

        self::assertSame(1, $tester->getExitCode());
        // Would otherwise resolve to $root/src/evil.php (one ".." escaping
        // the intended src/Entity/ directory) — stays inside the test's own
        // tmp sandbox so tearDown() still cleans it up if this ever regresses.
        self::assertFileDoesNotExist($this->root . '/src/evil.php');
        self::assertDirectoryDoesNotExist($this->root . '/src/Entity');
    }

    #[Test]
    public function rejects_a_newline_injected_name(): void
    {
        $tester = $this->runMake([
            'name' => "story\n} class Evil {",
            '--fields' => 'title:string',
        ]);

        self::assertSame(1, $tester->getExitCode());
        self::assertDirectoryDoesNotExist($this->root . '/src/Entity');
    }

    #[Test]
    public function rejects_a_trailing_newline_name_and_writes_no_file(): void
    {
        // A valid identifier prefix followed by a TRAILING newline: PHP's `$`
        // (without the `D` modifier) matches before the final `\n`, so an
        // allowlist regex lacking `D` would ACCEPT this and generate
        // `final class Story\nServiceProvider` — a php -l parse error that also
        // corrupts the composer-registered provider FQCN. The `D` modifier
        // closes this bypass.
        $tester = $this->runMake([
            'name' => "Story\n",
            '--fields' => 'title:string',
        ]);

        self::assertSame(1, $tester->getExitCode());
        self::assertStringContainsString('Invalid name', $tester->getStderr());
        self::assertDirectoryDoesNotExist($this->root . '/src/Entity');
        self::assertDirectoryDoesNotExist($this->root . '/src/Provider');
    }

    #[Test]
    public function accepts_an_indigenous_orthography_name_and_generates_valid_php(): void
    {
        // Charter regression-guard: an Indigenous-language content-type name
        // with diacritics AND one with Canadian Aboriginal Syllabics are valid
        // PHP identifier byte sequences (PHP allows identifier bytes >= 0x80)
        // that worked pre-fix. The Unicode-aware allowlist MUST still accept
        // them, preserve the non-Latin characters verbatim in BOTH the class
        // name and the human-facing label literal, and generate valid PHP.
        // Diacritics: "Anishinaabemowin" with an accented "í".
        $this->assertOrthographyPreserved("An\u{00ED}shinaabemowin");
        // Canadian Aboriginal Syllabics: "ᐊᓂᔑᓈᐯ" (Anishinaabe).
        $this->assertOrthographyPreserved("\u{140A}\u{14C2}\u{1450}\u{1448}\u{1426}");
    }

    private function assertOrthographyPreserved(string $name): void
    {
        // Fresh sandbox per name so each generates into a clean tree.
        $root = sys_get_temp_dir() . '/waaseyaa_orth_' . uniqid('', true);
        mkdir($root, 0o755, true);
        file_put_contents(
            $root . '/composer.json',
            (string) json_encode(['name' => 'app/app', 'autoload' => ['psr-4' => ['App\\' => 'src/']]], \JSON_PRETTY_PRINT),
        );
        self::initializeSite($root);

        try {
            $command = new HandlerCommand(
                name: 'make:content-type',
                description: 'Scaffold a content type',
                arguments: [new HandlerArgument(name: 'name', mode: HandlerArgumentMode::Required, description: 'name')],
                options: [
                    new HandlerOption(name: 'fields', mode: HandlerOptionMode::Required, description: 'fields', default: 'title:string'),
                    new HandlerOption(name: 'force', mode: HandlerOptionMode::None, description: 'force'),
                ],
                handler: \Closure::fromCallable([new MakeContentTypeHandler(projectRoot: $root, fieldProjection: new \Waaseyaa\Field\FieldScaffoldProjection(new \Waaseyaa\Field\FieldTypeManager())), 'execute']),
            );
            $tester = CliTester::for($command, $this->emptyContainer());
            $tester->executeMap(['name' => $name, '--fields' => 'title:string']);

            self::assertSame(0, $tester->getExitCode(), $tester->getStderr());

            $expectedClass = str_replace('_', '', ucwords($name, '_'));
            $entityPath = $root . '/src/Entity/' . $expectedClass . '.php';
            self::assertFileExists($entityPath);

            $entity = (string) file_get_contents($entityPath);
            // Non-Latin characters preserved verbatim in the class name...
            self::assertStringContainsString('final class ' . $expectedClass . ' extends ContentEntityBase', $entity);
            // ...and in the human-facing label literal (derived from the name).
            self::assertStringContainsString($name, $entity);
            // Generated file is syntactically valid PHP.
            exec('php -l ' . escapeshellarg($entityPath) . ' 2>&1', $lintOutput, $exitCode);
            self::assertSame(0, $exitCode, sprintf('%s failed php -l: %s', $entityPath, implode("\n", $lintOutput)));
        } finally {
            (new Filesystem())->remove($root);
        }
    }

    #[Test]
    public function rejects_a_quote_breakout_payload_in_entity_reference_target(): void
    {
        $tester = $this->runMake([
            'name' => 'story',
            // Comma-free payload — the --fields spec itself is comma-delimited,
            // so a comma would just start a second (differently-broken) field
            // instead of exercising the target-specific breakout.
            '--fields' => "author:entity_reference:user'); system('touch pwned'); //",
        ]);

        self::assertSame(1, $tester->getExitCode());
        self::assertStringContainsString('Invalid entity_reference target', $tester->getStderr());
        self::assertDirectoryDoesNotExist($this->root . '/src/Entity');
    }

    #[Test]
    public function generated_entity_and_provider_are_syntactically_valid_php(): void
    {
        $tester = $this->runMake([
            'name' => 'story',
            '--fields' => 'title:string,body:text,source_url:string,author:entity_reference:user',
        ]);

        self::assertSame(0, $tester->getExitCode(), $tester->getStderr());

        foreach ([$this->root . '/src/Entity/Story.php', $this->root . '/src/Provider/StoryServiceProvider.php'] as $file) {
            self::assertFileExists($file);
            exec('php -l ' . escapeshellarg($file) . ' 2>&1', $lintOutput, $exitCode);
            self::assertSame(0, $exitCode, sprintf('%s failed php -l: %s', $file, implode("\n", $lintOutput)));
        }
    }

    /**
     * #2438 regression guard: the skeleton no longer ships an empty
     * `src/Entity/` (placeholder `.gitkeep`) directory for `make:content-type`
     * to write into — a freshly created project mirrors `skeleton/src/`, which
     * holds only `Http/` and `Provider/AppServiceProvider.php`. This proves
     * the generator creates its own target directory on write (its own
     * `is_dir() || mkdir(..., recursive: true)` guard in `writeFile()`), the
     * same deterministic, collision-checked machinery it already used when a
     * placeholder happened to pre-exist — no directory-creation behavior
     * changed, only the starting tree did.
     */
    #[Test]
    public function creates_its_target_directory_against_the_minimal_skeleton_with_no_preexisting_entity_directory(): void
    {
        $repoRoot = (string) realpath(__DIR__ . '/../../../../../');
        $root = sys_get_temp_dir() . '/waaseyaa_mct_skeleton_' . uniqid('', true);
        mkdir($root, 0o755, true);
        (new Filesystem())->mirror($repoRoot . '/skeleton/src', $root . '/src');

        try {
            file_put_contents(
                $root . '/composer.json',
                (string) json_encode(['name' => 'app/app', 'autoload' => ['psr-4' => ['App\\' => 'src/']]], \JSON_PRETTY_PRINT),
            );
            self::initializeSite($root);

            self::assertDirectoryDoesNotExist($root . '/src/Entity', 'The minimal skeleton must not pre-scaffold src/Entity/.');
            self::assertDirectoryExists($root . '/src/Provider', 'The skeleton still ships src/Provider/AppServiceProvider.php.');

            $command = new HandlerCommand(
                name: 'make:content-type',
                description: 'Scaffold a content type',
                arguments: [new HandlerArgument(name: 'name', mode: HandlerArgumentMode::Required, description: 'name')],
                options: [
                    new HandlerOption(name: 'fields', mode: HandlerOptionMode::Required, description: 'fields', default: 'title:string'),
                    new HandlerOption(name: 'force', mode: HandlerOptionMode::None, description: 'force'),
                ],
                handler: \Closure::fromCallable([new MakeContentTypeHandler(projectRoot: $root, fieldProjection: new \Waaseyaa\Field\FieldScaffoldProjection(new \Waaseyaa\Field\FieldTypeManager())), 'execute']),
            );
            $tester = CliTester::for($command, $this->emptyContainer());
            $tester->executeMap(['name' => 'story', '--fields' => 'title:string']);

            self::assertSame(0, $tester->getExitCode(), $tester->getStderr());
            self::assertFileExists($root . '/src/Entity/Story.php');
            self::assertFileExists($root . '/src/Provider/StoryServiceProvider.php');
            // The pre-existing AppServiceProvider.php survives the write.
            self::assertFileExists($root . '/src/Provider/AppServiceProvider.php');
        } finally {
            (new Filesystem())->remove($root);
        }
    }
}

#[FieldType(id: 'scaffold_markdown', label: 'Scaffold markdown')]
final class CliScaffoldMarkdownFieldType extends AbstractFieldType implements FieldValueKindProviderInterface
{
    public static function valueKind(): FieldValueKind
    {
        return FieldValueKind::FormattedText;
    }

    public static function schema(): array
    {
        return ['value' => ['type' => 'text']];
    }

    public static function jsonSchema(): array
    {
        return ['type' => 'string'];
    }

    public static function entityValueJsonSchemaFor(\Waaseyaa\Field\FieldDefinitionInterface $def): array
    {
        return ['type' => 'string'];
    }
}

#[FieldType(id: "scaffold'quoted\\kind", label: 'Quoted scaffold')]
final class CliQuotedScaffoldFieldType extends AbstractFieldType implements FieldValueKindProviderInterface
{
    public static function valueKind(): FieldValueKind
    {
        return FieldValueKind::FormattedText;
    }

    public static function schema(): array
    {
        return ['value' => ['type' => 'text']];
    }

    public static function jsonSchema(): array
    {
        return ['type' => 'string'];
    }

    public static function entityValueJsonSchemaFor(\Waaseyaa\Field\FieldDefinitionInterface $def): array
    {
        return ['type' => 'string'];
    }
}
