<?php

declare(strict_types=1);

namespace App\Provider;

use App\Access\ApplicationBlueprintPermissions;
use App\Workflow\EditorialWorkflowDefinition;
use Waaseyaa\Foundation\ServiceProvider\Capability\ProvidesPermissionsInterface;
use Waaseyaa\Foundation\ServiceProvider\Capability\ProvidesRolesInterface;
use Waaseyaa\Foundation\ServiceProvider\ServiceProvider;
use Waaseyaa\User\Role;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand.
 */
final class ApplicationBlueprintGovernanceServiceProvider extends ServiceProvider implements ProvidesRolesInterface, ProvidesPermissionsInterface
{
    public function register(): void
    {
    }

    public function roles(): iterable
    {
        yield new Role('editor', 'Editor', ['edit article', 'use editorial transition publish']);
        yield new Role('viewer', 'Viewer', ['view article']);
    }

    public function permissions(): array
    {
        return ApplicationBlueprintPermissions::seed();
    }

    public function boot(): void
    {
        $entityTypeManager = $this->resolveOptional(\Waaseyaa\Entity\EntityTypeManager::class);
        if (!$entityTypeManager instanceof \Waaseyaa\Entity\EntityTypeManagerInterface) {
            return;
        }
        $logger = $this->resolveOptional(\Waaseyaa\Foundation\Log\LoggerInterface::class);
        $logger = $logger instanceof \Waaseyaa\Foundation\Log\LoggerInterface ? $logger : new \Waaseyaa\Foundation\Log\NullLogger();

        $this->seedWorkflow('editorial', EditorialWorkflowDefinition::DEFINITION, $entityTypeManager, $logger);
    }

    private function seedWorkflow(
        string $id,
        array $definition,
        \Waaseyaa\Entity\EntityTypeManagerInterface $entityTypeManager,
        \Waaseyaa\Foundation\Log\LoggerInterface $logger,
    ): void {
        try {
            $repository = $entityTypeManager->getRepository('workflow');
        } catch (\RuntimeException $exception) {
            if (str_contains($exception->getMessage(), '[S1-DB106]')) {
                return;
            }
            throw $exception;
        }

        $existing = $repository->find($id);
        if ($existing instanceof \Waaseyaa\Workflows\Workflow) {
            $this->topUpWorkflow($existing, $definition, $repository, $logger);

            return;
        }

        $workflow = new \Waaseyaa\Workflows\Workflow($definition);
        $violations = new \Waaseyaa\Workflows\Validation\WorkflowValidator()->validate($workflow);
        if ($violations !== []) {
            $logger->warning('application_blueprint.governance.workflow_seed_invalid', ['workflow' => $id, 'violations' => $violations]);

            return;
        }

        $workflow->enforceIsNew();

        try {
            $repository->save($workflow);
        } catch (\Throwable $e) {
            $logger->warning('application_blueprint.governance.workflow_seed_failed', ['workflow' => $id, 'error' => $e->getMessage()]);
        }
    }

    private function topUpWorkflow(
        \Waaseyaa\Workflows\Workflow $existing,
        array $definition,
        \Waaseyaa\Entity\Repository\EntityRepositoryInterface $repository,
        \Waaseyaa\Foundation\Log\LoggerInterface $logger,
    ): void {
        $addedStates = [];
        foreach ($definition['states'] as $stateId => $stateData) {
            if ($existing->hasState($stateId) || !\is_array($stateData)) {
                continue;
            }
            $existing->addState(new \Waaseyaa\Workflows\WorkflowState(
                id: (string) $stateId,
                label: (string) ($stateData['label'] ?? $stateId),
                weight: (int) ($stateData['weight'] ?? 0),
                metadata: (array) ($stateData['metadata'] ?? []),
                published: (bool) ($stateData['published'] ?? false),
                defaultRevision: (bool) ($stateData['default_revision'] ?? false),
            ));
            $addedStates[] = $stateId;
        }

        $addedTransitions = [];
        foreach ($definition['transitions'] as $transitionId => $transitionData) {
            if ($existing->hasTransition($transitionId) || !\is_array($transitionData)) {
                continue;
            }
            $existing->addTransition(new \Waaseyaa\Workflows\WorkflowTransition(
                id: (string) $transitionId,
                label: (string) ($transitionData['label'] ?? $transitionId),
                from: (array) ($transitionData['from'] ?? []),
                to: (string) ($transitionData['to'] ?? ''),
                weight: (int) ($transitionData['weight'] ?? 0),
                permission: (string) ($transitionData['permission'] ?? ''),
            ));
            $addedTransitions[] = $transitionId;
        }

        if ($addedStates === [] && $addedTransitions === []) {
            return;
        }

        $violations = new \Waaseyaa\Workflows\Validation\WorkflowValidator()->validate($existing);
        if ($violations !== []) {
            $logger->warning('application_blueprint.governance.workflow_topup_invalid', ['violations' => $violations]);

            return;
        }

        try {
            $repository->save($existing);
        } catch (\Throwable $e) {
            $logger->warning('application_blueprint.governance.workflow_topup_failed', ['error' => $e->getMessage()]);
        }
    }
}
