/**
 * Read a bundle scope from a route query (#2418).
 *
 * The destination is generated by `Waaseyaa\AdminSurface\AdminDestinationPaths`
 * (#2420), whose `QUERY_BUNDLE` constant names this parameter. Both halves
 * change together.
 *
 * Degrades rather than errors. A repeated parameter arrives as an array and a
 * blank one as an empty string; both mean "no usable scope", so the caller
 * falls back to the unscoped view. A stale or hand-edited link therefore lands
 * on a working page instead of dead-ending — whether the bundle is *permitted*
 * is decided later, against the schema the server actually returns.
 */
export const BUNDLE_QUERY_PARAM = 'bundle'

export function readBundleScope(query: Record<string, unknown> | undefined): string | undefined {
  const raw = query?.[BUNDLE_QUERY_PARAM]

  return typeof raw === 'string' && raw !== '' ? raw : undefined
}
