<?php

declare(strict_types=1);

namespace Waaseyaa\Foundation\Tests\Unit\Ingestion;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Waaseyaa\Foundation\Ingestion\Envelope;
use Waaseyaa\Foundation\Ingestion\EnvelopeValidator;
use Waaseyaa\Foundation\Ingestion\IngestionError;
use Waaseyaa\Foundation\Ingestion\IngestionErrorCode;
use Waaseyaa\Foundation\Ingestion\InvalidEnvelopeException;

#[CoversClass(EnvelopeValidator::class)]
#[CoversClass(Envelope::class)]
#[CoversClass(InvalidEnvelopeException::class)]
#[CoversClass(IngestionError::class)]
#[CoversClass(IngestionErrorCode::class)]
final class EnvelopeValidatorTest extends TestCase
{
    private EnvelopeValidator $validator;

    protected function setUp(): void
    {
        $this->validator = new EnvelopeValidator();
    }

    // ------------------------------------------------------------------
    // Happy path
    // ------------------------------------------------------------------

    #[Test]
    public function validEnvelopeReturnsDto(): void
    {
        $envelope = $this->validator->validate($this->validEnvelope());

        $this->assertInstanceOf(Envelope::class, $envelope);
        $this->assertSame('manual', $envelope->source);
        $this->assertSame('core.note', $envelope->type);
        $this->assertSame(['title' => 'Hello'], $envelope->payload);
        $this->assertSame('2026-03-08T17:00:00+00:00', $envelope->timestamp);
        $this->assertSame('tenant-1', $envelope->tenantId);
        $this->assertSame(['priority' => 'high'], $envelope->metadata);
    }

    #[Test]
    public function validEnvelopeWithExplicitTraceIdPreservesIt(): void
    {
        $raw = $this->validEnvelope();
        $raw['trace_id'] = '550e8400-e29b-41d4-a716-446655440000';

        $envelope = $this->validator->validate($raw);

        $this->assertSame('550e8400-e29b-41d4-a716-446655440000', $envelope->traceId);
    }

    #[Test]
    public function missingTraceIdIsAutoGenerated(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['trace_id']);

        $envelope = $this->validator->validate($raw);

        $this->assertMatchesRegularExpression(
            '/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/',
            $envelope->traceId,
        );
    }

    #[Test]
    public function missingOptionalFieldsDefaultCorrectly(): void
    {
        $raw = [
            'source'    => 'manual',
            'type'      => 'core.note',
            'payload'   => ['title' => 'Test'],
            'timestamp' => '2026-03-08T17:00:00+00:00',
        ];

        $envelope = $this->validator->validate($raw);

        $this->assertNull($envelope->tenantId);
        $this->assertSame([], $envelope->metadata);
        $this->assertNotEmpty($envelope->traceId);
    }

    #[Test]
    public function timestampWithoutOffsetIsAccepted(): void
    {
        $raw = $this->validEnvelope();
        $raw['timestamp'] = '2026-03-08T17:00:00';

        $envelope = $this->validator->validate($raw);

        $this->assertSame('2026-03-08T17:00:00', $envelope->timestamp);
    }

    #[Test]
    public function toArrayReturnsExpectedShape(): void
    {
        $raw = $this->validEnvelope();
        $raw['trace_id'] = '550e8400-e29b-41d4-a716-446655440000';

        $envelope = $this->validator->validate($raw);
        $arr = $envelope->toArray();

        $this->assertSame('manual', $arr['source']);
        $this->assertSame('core.note', $arr['type']);
        $this->assertSame(['title' => 'Hello'], $arr['payload']);
        $this->assertSame('2026-03-08T17:00:00+00:00', $arr['timestamp']);
        $this->assertSame('550e8400-e29b-41d4-a716-446655440000', $arr['trace_id']);
        $this->assertSame('tenant-1', $arr['tenant_id']);
        $this->assertSame(['priority' => 'high'], $arr['metadata']);
    }

    // ------------------------------------------------------------------
    // Missing required fields
    // ------------------------------------------------------------------

    #[Test]
    public function missingSourceThrows(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['source']);

        $this->assertValidationError($raw, 'source', 'missing');
    }

    #[Test]
    public function missingTypeThrows(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['type']);

        $this->assertValidationError($raw, 'type', 'missing');
    }

    #[Test]
    public function missingPayloadThrows(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['payload']);

        $this->assertValidationError($raw, 'payload', 'missing');
    }

    #[Test]
    public function missingTimestampThrows(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['timestamp']);

        $this->assertValidationError($raw, 'timestamp', 'missing');
    }

    // ------------------------------------------------------------------
    // Invalid field types
    // ------------------------------------------------------------------

    #[Test]
    public function nonStringSourceThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['source'] = 42;

        $this->assertValidationError($raw, 'source', 'must be a string');
    }

    #[Test]
    public function emptySourceThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['source'] = '';

        $this->assertValidationError($raw, 'source', 'non-empty');
    }

    #[Test]
    public function nonStringTypeThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['type'] = [];

        $this->assertValidationError($raw, 'type', 'must be a string');
    }

    #[Test]
    public function nonArrayPayloadThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['payload'] = 'not-an-object';

        $this->assertValidationError($raw, 'payload', 'must be an object');
    }

    #[Test]
    public function nonStringTimestampThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['timestamp'] = 1234567890;

        $this->assertValidationError($raw, 'timestamp', 'ISO 8601');
    }

    #[Test]
    public function invalidTimestampFormatThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['timestamp'] = 'not-a-date';

        $this->assertValidationError($raw, 'timestamp', 'not a valid ISO 8601');
    }

    #[Test]
    public function invalidTraceIdFormatThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['trace_id'] = 'not-a-uuid';

        $this->assertValidationError($raw, 'trace_id', 'valid lowercase UUID');
    }

    #[Test]
    public function uppercaseTraceIdThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['trace_id'] = '550E8400-E29B-41D4-A716-446655440000';

        $this->assertValidationError($raw, 'trace_id', 'valid lowercase UUID');
    }

    #[Test]
    public function nonArrayMetadataThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['metadata'] = 'not-an-object';

        $this->assertValidationError($raw, 'metadata', 'must be an object');
    }

    #[Test]
    public function emptyTenantIdThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['tenant_id'] = '';

        $this->assertValidationError($raw, 'tenant_id', 'non-empty');
    }

    // ------------------------------------------------------------------
    // Unknown fields (strict schema)
    // ------------------------------------------------------------------

    #[Test]
    public function unknownFieldThrows(): void
    {
        $raw = $this->validEnvelope();
        $raw['extra_field'] = 'unexpected';

        $this->assertValidationError($raw, 'extra_field', 'Unknown field');
    }

    #[Test]
    public function multipleUnknownFieldsReportAll(): void
    {
        $raw = $this->validEnvelope();
        $raw['foo'] = 1;
        $raw['bar'] = 2;

        try {
            $this->validator->validate($raw);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $fields = array_map(static fn(IngestionError $err) => $err->field, $e->errors);
            $this->assertContains('foo', $fields);
            $this->assertContains('bar', $fields);
        }
    }

    // ------------------------------------------------------------------
    // Exception structure
    // ------------------------------------------------------------------

    #[Test]
    public function exceptionContainsTraceIdWhenProvided(): void
    {
        $raw = $this->validEnvelope();
        $raw['trace_id'] = '550e8400-e29b-41d4-a716-446655440000';
        $raw['extra'] = 'bad';

        try {
            $this->validator->validate($raw);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $this->assertSame('550e8400-e29b-41d4-a716-446655440000', $e->traceId);
        }
    }

    #[Test]
    public function exceptionContainsNullTraceIdWhenMissing(): void
    {
        try {
            $this->validator->validate([]);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $this->assertNull($e->traceId);
            $this->assertNotEmpty($e->errors);
        }
    }

    #[Test]
    public function multipleErrorsReportedAtOnce(): void
    {
        try {
            $this->validator->validate([]);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            // Should report all 4 missing required fields.
            $this->assertGreaterThanOrEqual(4, count($e->errors));
        }
    }

    #[Test]
    public function errorsCarryCanonicalErrorCodes(): void
    {
        $raw = $this->validEnvelope();
        unset($raw['source']);

        try {
            $this->validator->validate($raw);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $this->assertInstanceOf(IngestionError::class, $e->errors[0]);
            $this->assertSame(IngestionErrorCode::ENVELOPE_FIELD_MISSING, $e->errors[0]->code);
            $this->assertSame('source', $e->errors[0]->field);
        }
    }

    #[Test]
    public function exceptionToArraySerializesErrors(): void
    {
        $raw = $this->validEnvelope();
        $raw['extra'] = 'bad';

        try {
            $this->validator->validate($raw);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $arr = $e->toArray();
            $this->assertArrayHasKey('code', $arr[0]);
            $this->assertArrayHasKey('message', $arr[0]);
            $this->assertArrayHasKey('field', $arr[0]);
            $this->assertArrayHasKey('trace_id', $arr[0]);
            $this->assertArrayHasKey('details', $arr[0]);
            $this->assertSame('ENVELOPE_FIELD_UNKNOWN', $arr[0]['code']);
        }
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /** @return array<string, mixed> */
    private function validEnvelope(): array
    {
        return [
            'source'    => 'manual',
            'type'      => 'core.note',
            'payload'   => ['title' => 'Hello'],
            'timestamp' => '2026-03-08T17:00:00+00:00',
            'trace_id'  => '550e8400-e29b-41d4-a716-446655440000',
            'tenant_id' => 'tenant-1',
            'metadata'  => ['priority' => 'high'],
        ];
    }

    private function assertValidationError(array $raw, string $field, string $messageContains): void
    {
        try {
            $this->validator->validate($raw);
            $this->fail('Expected InvalidEnvelopeException');
        } catch (InvalidEnvelopeException $e) {
            $matchingErrors = array_filter(
                $e->errors,
                static fn(IngestionError $err) => $err->field === $field
                    && str_contains(strtolower($err->message), strtolower($messageContains)),
            );
            $this->assertNotEmpty(
                $matchingErrors,
                "Expected error on field '{$field}' containing '{$messageContains}'. Got: "
                . json_encode(array_map(fn(IngestionError $e) => $e->toArray(), $e->errors)),
            );
        }
    }
}
