<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install;

/**
 * Deterministic warnings when a requested install feature cannot be represented
 * by a client's shipped convention (#2660 open question (b)).
 *
 * @api
 */
final class ClientCapabilityDiagnostics
{
    /**
     * @param list<string> $requestedFeatures normalized feature ids from `--features`
     * @return list<string> structured warning lines, empty when fully supported
     */
    public static function warnings(ClientCapabilities $capabilities, array $requestedFeatures): array
    {
        $requested = self::normalizeFeatures($requestedFeatures);
        $warnings = [];

        if (in_array(ClientCapabilitySurface::Skills->value, $requested, true)
            && $capabilities->skillDelivery === SkillDeliveryMode::SingleConsolidatedFile) {
            $warnings[] = sprintf(
                'skills for client "%s" are folded into %s — per-skill delivery not supported by this client\'s shipped convention.',
                $capabilities->clientId,
                $capabilities->guidancePath,
            );
        }

        if (in_array(ClientCapabilitySurface::McpConfiguration->value, $requested, true)) {
            $warnings[] = sprintf(
                'Client %s: MCP configuration is not generated by bimaaji:install (see #2663).',
                $capabilities->clientId,
            );
        }

        return $warnings;
    }

    /**
     * @param list<string> $requestedFeatures
     * @return list<string>
     */
    private static function normalizeFeatures(array $requestedFeatures): array
    {
        $normalized = [];
        foreach ($requestedFeatures as $feature) {
            $piece = strtolower(trim($feature));
            if ($piece === 'mcp' || $piece === 'mcp-configuration' || $piece === 'mcp_configuration') {
                $piece = ClientCapabilitySurface::McpConfiguration->value;
            }
            if ($piece !== '') {
                $normalized[] = $piece;
            }
        }

        return array_values(array_unique($normalized));
    }
}
