<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install;

/**
 * The three adapter surfaces `bimaaji:install` can materialize for a client.
 *
 * Guidelines are concise, always-loaded project guidance. Skills are detailed,
 * on-demand bodies installed as separate files where the client's convention
 * supports that. MCP configuration is declared here for #2663 but is not
 * generated by this command.
 *
 * @api
 */
enum ClientCapabilitySurface: string
{
    case Guidelines = 'guidelines';
    case Skills = 'skills';
    case McpConfiguration = 'mcp_configuration';
}
