<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install;

/**
 * Deterministic warnings when a requested `bimaaji:install` feature cannot
 * be represented by a client's shipped convention (#2660 open question
 * (b)).
 *
 * Warning severity, not a hard error: a `SingleConsolidatedFile` client's
 * inability to hold per-skill delivery is the shape its vendor supports,
 * not a bug — a default hard error would make `--client=cursor` (and five
 * of the other six shipped clients) fail out of the box. See
 * `docs/adr/026-client-guidance-and-skill-conventions.md` (b) for the full
 * tradeoff record; this class implements that recorded recommendation.
 *
 * @api
 */
final class ClientCapabilityDiagnostics
{
    /**
     * @param list<string> $requestedFeatures normalized feature ids from `--features` (case-insensitive)
     * @return list<string> structured warning lines, empty when everything requested is representable
     */
    public static function warnings(ClientCapabilities $capabilities, array $requestedFeatures): array
    {
        $requested = self::normalizeFeatures($requestedFeatures);
        $warnings = [];

        if (
            in_array(ClientCapabilitySurface::Skills->value, $requested, true)
            && $capabilities->skillDelivery === SkillDeliveryMode::SingleConsolidatedFile
        ) {
            $warnings[] = sprintf(
                'skills for client "%s" are folded into %s — per-skill delivery not supported by this client\'s shipped convention.',
                $capabilities->clientId,
                $capabilities->guidancePath,
            );
        }

        if (in_array(ClientCapabilitySurface::McpConfiguration->value, $requested, true)) {
            $warnings[] = sprintf(
                'MCP configuration for client "%s" is not generated by bimaaji:install (see #2663).',
                $capabilities->clientId,
            );
        }

        return $warnings;
    }

    /**
     * @param list<string> $requestedFeatures
     * @return list<string>
     */
    private static function normalizeFeatures(array $requestedFeatures): array
    {
        $normalized = [];
        foreach ($requestedFeatures as $feature) {
            $piece = strtolower(trim($feature));
            if ($piece === 'mcp' || $piece === 'mcp-configuration') {
                $piece = ClientCapabilitySurface::McpConfiguration->value;
            }
            if ($piece !== '') {
                $normalized[] = $piece;
            }
        }

        return array_values(array_unique($normalized));
    }
}
