<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install;

/**
 * The adapter surfaces `bimaaji:install` can materialize for a client
 * (#2660).
 *
 * `Guidelines` is concise, always-loaded project guidance — every client
 * gets this. `Skills` is detailed, on-demand skill bodies installed as
 * separate files, available only to a {@see SkillDeliveryMode::PerSkillFile}
 * client. `McpConfiguration` names the surface #2663 owns; declared here so
 * `ClientCapabilityDiagnostics` has one vocabulary for "not generated by
 * this command" rather than a bespoke string per caller.
 *
 * @api
 */
enum ClientCapabilitySurface: string
{
    case Guidelines = 'guidelines';
    case Skills = 'skills';
    case McpConfiguration = 'mcp_configuration';
}
