<?php

declare(strict_types=1);

// Migrated by bin/migrate-surface-map from docs/public-surface-map.php
// and docs/public-surface-map.md (FW-DELIVERY-SURFACE-01 / #2901). This
// file, not the generated docs/public-surface-map.*, is the editable
// authority — see docs/specs/public-surface-declarations.md.
return [
    'entries' => [
        ['fqcn' => 'Waaseyaa\\Foundation\\Asset\\AssetManagerInterface', 'disposition' => 'public', 'purpose' => 'Resolves source asset paths to versioned/hashed production URLs via build manifests'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Audit\\Approval\\ApprovalStatus', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Audit\\Approval\\OperationApprovalStoreInterface', 'disposition' => 'public', 'ref' => '#2177'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Audit\\AuditStage', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Audit\\StrictAuditLedgerInterface', 'disposition' => 'public', 'ref' => '#2177'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Community\\CommunityContextInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Diagnostic\\DiagnosticCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Diagnostic\\HealthCheckerInterface', 'disposition' => 'public', 'purpose' => 'Runs boot, runtime, and ingestion health checks across subsystems'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Event\\DomainEvent', 'disposition' => 'public', 'purpose' => 'Base class for all domain events carrying aggregate identity and actor context'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Event\\EventDispatcherInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Exception\\WaaseyaaException', 'disposition' => 'public', 'purpose' => 'Base exception for all framework errors, with HTTP status code and problem type'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\BindingAwareHttpServiceResolverInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\HttpServiceResolverInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\Inbound\\InboundHttpRequestInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\Inertia\\InertiaFullPageRendererInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\Inertia\\InertiaPageResultInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\JsonApiResponseTrait', 'disposition' => 'public', 'purpose' => 'Builds JSON:API responses with correct content type and encoding options'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\LanguagePathStripperInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\RequestContext', 'disposition' => 'public', 'purpose' => 'Exposes the active request\'s roles, user id, languages, and query params to `ContextResolver` (charter §5.9)'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Http\\Router\\DomainRouterInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Ingestion\\IngestionErrorCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Ingestion\\TraceIdGeneratorInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Kernel\\AbstractKernel', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Kernel\\Bootstrap\\PolicyDependencyResolverInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\Formatter\\FormatterInterface', 'disposition' => 'public', 'purpose' => 'Formats a log record into its final string or array representation'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\Handler\\HandlerInterface', 'disposition' => 'public', 'purpose' => 'Log handler that receives and writes formatted log records'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\LogLevel', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\LoggerInterface', 'disposition' => 'public', 'purpose' => 'Structured logger with PSR-3-style severity levels (framework-internal, not psr/log)'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\LoggerTrait', 'disposition' => 'public', 'purpose' => 'Default implementations of all log-level methods delegating to `log()`'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Log\\Processor\\ProcessorInterface', 'disposition' => 'public', 'purpose' => 'Enriches log records with additional context before handling'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Middleware\\HttpHandlerInterface', 'disposition' => 'public', 'purpose' => 'Terminal HTTP request handler (innermost layer of the middleware onion)'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Middleware\\HttpMiddlewareInterface', 'disposition' => 'public', 'purpose' => 'Wraps an HTTP handler to add cross-cutting behavior'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Middleware\\JobHandlerInterface', 'disposition' => 'public', 'purpose' => 'Terminal queue job handler'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Middleware\\JobMiddlewareInterface', 'disposition' => 'public', 'purpose' => 'Wraps a job handler to add cross-cutting behavior'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\Dag\\MigrationKind', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\EntityTableMaterializerInterface', 'disposition' => 'public', 'ref' => '#2701'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\Executor\\ApplyMode', 'disposition' => 'public', 'ref' => '#2701'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\Executor\\OpPrecondition', 'disposition' => 'internal', 'ref' => '#2701'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\Migration', 'disposition' => 'public', 'purpose' => 'Base class for database migrations with optional rollback and ordering'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\SchemaAuthorityManifest', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Migration\\VerifyResult', 'disposition' => 'public', 'ref' => '#529'],
        ['fqcn' => 'Waaseyaa\\Foundation\\RateLimit\\RateLimiterInterface', 'disposition' => 'public', 'purpose' => 'Checks and records attempt counts for rate limiting'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Runtime\\RuntimeEpochInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Compiler\\CompiledStep', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Compiler\\Sqlite\\SqliteDiagnosticCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Compiler\\Validation\\ValidationDiagnosticCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Compiler\\Validation\\ValidationException', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Diff\\OpKind', 'disposition' => 'public', 'ref' => '#529'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Diff\\SchemaDiffOp', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\Migration\\MigrationInterfaceV2', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Schema\\SchemaRegistryInterface', 'disposition' => 'public', 'purpose' => 'Stores and retrieves JSON Schema entries by entity type ID'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\ApplicationMasterPurposeStrategy', 'disposition' => 'public', 'purpose' => 'Closed transition strategies for versioned application-master purposes'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\ApplicationMasterSymmetricOperation', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\Rekey\\ApplicationMasterRekeyAdapterInterface', 'disposition' => 'public', 'purpose' => 'Same-database joint-owner inventory, transition, verification, and rollback seam'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\Rekey\\ApplicationMasterRekeyGate', 'disposition' => 'public', 'purpose' => 'Closed fleet, cache, rollback, and retained-backup revocation gates'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\Rekey\\ApplicationMasterRekeyState', 'disposition' => 'public', 'purpose' => 'Closed persisted prepare-through-revocation and forward-rollback states'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\SecretClass', 'disposition' => 'public', 'purpose' => 'Closed secret classifications used by typed references, policies, and guarded consumers'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\SecretConsumerInterface', 'disposition' => 'public', 'purpose' => 'Purpose-specific guarded endpoint for resolved secret bytes'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\SecretConsumptionCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\SecretProviderInterface', 'disposition' => 'public', 'purpose' => 'External secret-provider resolution seam'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Security\\SecretResolutionCode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\AcceptsAgentToolProvidersInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\AcceptsAiCatalogEntryProvidersInterface', 'disposition' => 'public', 'purpose' => 'Receives the deterministic installed-provider set used to assemble experimental AI Catalog discovery'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\AcceptsApiCatalogEntryProvidersInterface', 'disposition' => 'public', 'purpose' => 'Receives the deterministic installed-provider set used to assemble RFC 9727 discovery'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\AcceptsContentModelProvidersInterface', 'disposition' => 'public', 'ref' => '#1940'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\AcceptsMigrationProvidersInterface', 'disposition' => 'public', 'ref' => '#1614'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ConfiguresHttpKernelInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\FinalizesProviderBootInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\HasGraphqlMutationOverridesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\HasHttpDomainRoutersInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\HasMiddlewareInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\HasRenderCacheListenersInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesAiCatalogEntriesInterface', 'disposition' => 'public', 'purpose' => 'Contributes same-origin, intentionally public AI artifact references without deployment-specific language'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesApiCatalogEntriesInterface', 'disposition' => 'public', 'purpose' => 'Contributes same-origin, intentionally public API endpoints and bounded description links'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesApplicationMasterRekeyContributionsInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesCapabilitiesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesConsoleCommandsInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesPermissionsInterface', 'disposition' => 'public', 'purpose' => 'Contributes permission definitions to the one kernel-composed permission catalogue that role grants are validated against at boot', 'ref' => '#2788'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\ProvidesRolesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\RequiresCapabilitiesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\Capability\\RequiresOptionalPackagesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\KernelServicesInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\ServiceProvider', 'disposition' => 'public', 'purpose' => 'Base class for service providers with DI binding and resolution helpers'],
        ['fqcn' => 'Waaseyaa\\Foundation\\ServiceProvider\\ServiceProviderInterface', 'disposition' => 'public', 'purpose' => 'Contract for packages to register and boot their services'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Sovereignty\\SovereigntyConfigInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Sovereignty\\SovereigntyProfile', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Tenant\\TenantResolverInterface', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Upgrade\\UpgradePreflightContract', 'disposition' => 'public', 'ref' => '#2336'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Upgrade\\UpgradePreflightDecision', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Upgrade\\UpgradePreflightEvaluator', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Foundation\\Upgrade\\UpgradePreflightResult', 'disposition' => 'public'],
    ],
    'notes' => [
        '`Security\\ApplicationMasterPurposePolicy` (final readonly class): Immutable owner, retention, adapter, strategy, and rollback metadata for one derived purpose',
        '`Security\\ApplicationMasterPurposeRegistry` (final class): Deterministic boot-time frozen registry of application-master purposes',
        '`Security\\ApplicationMasterEnvelope` (final readonly class): Strict XChaCha20-Poly1305 envelope binding master version, purpose, record, and schema identity',
        '`Security\\ApplicationMasterKeyring` (final class): Active-write and bounded legacy-read custody over externally resolved versioned masters',
        '`Security\\Rekey\\ApplicationMasterRekeyRequest` (final readonly class): Immutable non-secret request, authorization digest, versions, and rollback/retention horizons',
        '`Security\\Rekey\\ApplicationMasterRekeyStore` (final class): Migration-backed CAS projections and append-only hash-chained rekey evidence',
        '`Security\\Rekey\\ApplicationMasterRekeyCoordinator` (final class): Restart-safe same-transaction executor for composed owner adapters',
        '`Security\\Rekey\\ApplicationMasterRekeyContext` (final readonly class): Exact immutable request, guarded keyring, and store transaction authority passed to adapters',
        '`Security\\Rekey\\ApplicationMasterInventorySnapshot` (final readonly class): Immutable inventory count and SHA-256 commitment',
        '`Security\\Rekey\\ApplicationMasterBatchResult` (final readonly class): Next cursor, transitioned count, per-purpose deltas, and batch commitment',
        '`Security\\Rekey\\ApplicationMasterPurposeVerification` (final readonly class): Per-purpose verified count and commitment',
        '`Security\\Rekey\\ApplicationMasterAdapterProgress` (final readonly class): Restart-safe joint-owner snapshot, cursor, counts, and commitment projection',
        '`Security\\Rekey\\ApplicationMasterRekeyEvent` (final readonly class): Verifiable immutable non-secret ledger event',
    ],
];
