// Bundle-scoped deep links into the Admin SPA (#2418).
//
// A consumer must be able to address "create a post" and "list only
// job_posting" rather than only "create a node" and "list nodes". The
// destinations are generated by Waaseyaa\AdminSurface\AdminDestinationPaths
// (#2420); these tests pin the SPA half of that contract, including the
// requirement that a stale or unauthorized link degrades to the unscoped view
// rather than dead-ending.
import { flushPromises } from '@vue/test-utils'
import { mockNuxtImport, mountSuspended } from '@nuxt/test-utils/runtime'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { EntitySchema } from '~/contracts/schema'

const { routeQuery, schemaRef, fetchSchemaMock } = vi.hoisted(() => {
  const { ref } = require('vue') as typeof import('vue')
  return {
    routeQuery: ref<Record<string, unknown>>({}),
    schemaRef: ref<EntitySchema | null>(null),
    fetchSchemaMock: vi.fn(),
  }
})

mockNuxtImport('useRoute', () => () => ({ params: { entityType: 'node' }, query: routeQuery.value }))
mockNuxtImport('useAdminConfig', () => () => ({ appName: 'Test admin', enableRealtime: false }))

vi.mock('~/composables/useLanguage', () => ({
  useLanguage: () => ({
    t: (key: string) => key,
    entityLabel: (_type: string, fallback: string) => fallback,
  }),
}))

vi.mock('~/composables/useSchema', () => ({
  useSchema: () => ({
    schema: schemaRef,
    loading: { value: false },
    error: { value: null },
    fetch: fetchSchemaMock,
  }),
}))

vi.mock('~/composables/useAdmin', () => ({
  useAdmin: () => ({
    catalog: [],
    getEntity: () => null,
    hasCapability: () => true,
  }),
}))

vi.mock('~/composables/useApi', () => ({
  useApi: () => ({ apiFetch: vi.fn() }),
}))

const schemaFormStub = {
  name: 'SchemaForm',
  props: ['entityType', 'entityId', 'initialBundle', 'initialValues'],
  template: '<div data-testid="schema-form" />',
}

const schemaListStub = {
  name: 'SchemaList',
  props: ['entityType', 'initialBundle'],
  template: '<div data-testid="schema-list" />',
}

async function mountCreatePage() {
  const { default: CreatePage } = await import('~/pages/[entityType]/create.vue')
  const wrapper = await mountSuspended(CreatePage, {
    global: { stubs: { SchemaForm: schemaFormStub, NuxtLink: true } },
  })
  await flushPromises()
  return wrapper
}

async function mountListPage() {
  const { default: ListPage } = await import('~/pages/[entityType]/index.vue')
  const wrapper = await mountSuspended(ListPage, {
    global: { stubs: { SchemaList: schemaListStub, NuxtLink: true } },
  })
  await flushPromises()
  return wrapper
}

describe('bundle-scoped deep links', () => {
  beforeEach(() => {
    routeQuery.value = {}
    schemaRef.value = {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      title: 'Content',
      description: '',
      type: 'object',
      'x-entity-type': 'node',
      'x-translatable': false,
      'x-revisionable': true,
      properties: {},
    } as EntitySchema
    fetchSchemaMock.mockReset()
  })

  it('scopes the create form to a bundle from the query string', async () => {
    routeQuery.value = { bundle: 'post' }

    const form = (await mountCreatePage()).findComponent(schemaFormStub)

    expect(form.props('initialBundle')).toBe('post')
  })

  it('leaves the create form unscoped when no bundle is requested', async () => {
    const form = (await mountCreatePage()).findComponent(schemaFormStub)

    expect(form.props('initialBundle')).toBeUndefined()
  })

  it('degrades to the unscoped create form for a malformed bundle', async () => {
    routeQuery.value = { bundle: ['post', 'page'] }

    const form = (await mountCreatePage()).findComponent(schemaFormStub)

    expect(form.props('initialBundle')).toBeUndefined()
  })

  it('degrades to the unscoped create form for an empty bundle', async () => {
    routeQuery.value = { bundle: '' }

    const form = (await mountCreatePage()).findComponent(schemaFormStub)

    expect(form.props('initialBundle')).toBeUndefined()
  })

  it('scopes the listing to a bundle from the query string', async () => {
    routeQuery.value = { bundle: 'job_posting' }

    const list = (await mountListPage()).findComponent(schemaListStub)

    expect(list.props('initialBundle')).toBe('job_posting')
  })

  it('leaves the listing unscoped when no bundle is requested', async () => {
    const list = (await mountListPage()).findComponent(schemaListStub)

    expect(list.props('initialBundle')).toBeUndefined()
  })

  it('degrades to the unscoped listing for a malformed bundle', async () => {
    routeQuery.value = { bundle: ['a', 'b'] }

    const list = (await mountListPage()).findComponent(schemaListStub)

    expect(list.props('initialBundle')).toBeUndefined()
  })
})
