<?php

declare(strict_types=1);

namespace Waaseyaa\Entity\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Waaseyaa\Entity\Cast\Exception\CastException;
use Waaseyaa\Entity\ContentEntityBase;
use Waaseyaa\Entity\EntityBase;
use Waaseyaa\Entity\EntityInterface;
use Waaseyaa\Entity\Tests\Unit\Cast\Fixture\SampleStringEnum;

/**
 * @covers \Waaseyaa\Entity\EntityBase
 */
class EntityBaseTest extends TestCase
{
    public function testImplementsInterface(): void
    {
        $entity = new TestEntity();

        $this->assertInstanceOf(EntityInterface::class, $entity);
        $this->assertInstanceOf(EntityBase::class, $entity);
    }

    public function testDefaultEntityTypeId(): void
    {
        $entity = new TestEntity();

        $this->assertSame('test_entity', $entity->getEntityTypeId());
    }

    public function testEntityTypeIdFromConstructor(): void
    {
        $entity = new TestEntity(entityTypeId: 'custom_type');

        $this->assertSame('custom_type', $entity->getEntityTypeId());
    }

    public function testIdReturnsNullWhenNotSet(): void
    {
        $entity = new TestEntity();

        $this->assertNull($entity->id());
    }

    public function testIdReturnsValueFromDefaultKey(): void
    {
        $entity = new TestEntity(['id' => 42]);

        $this->assertSame(42, $entity->id());
    }

    public function testIdReturnsValueFromCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['nid' => 7],
            entityKeys: ['id' => 'nid'],
        );

        $this->assertSame(7, $entity->id());
    }

    public function testUuidAutoGenerated(): void
    {
        $entity = new TestEntity(
            entityKeys: ['id' => 'id', 'uuid' => 'uuid'],
        );
        $uuid = $entity->uuid();

        $this->assertNotEmpty($uuid);
        // UUID v4 format: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx
        $this->assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',
            $uuid,
        );
    }

    public function testUuidPreservedWhenProvided(): void
    {
        $providedUuid = 'a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5';
        $entity = new TestEntity(
            values: ['uuid' => $providedUuid],
            entityKeys: ['id' => 'id', 'uuid' => 'uuid'],
        );

        $this->assertSame($providedUuid, $entity->uuid());
    }

    public function testUuidUsesCustomKey(): void
    {
        $providedUuid = 'a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5';
        $entity = new TestEntity(
            values: ['my_uuid' => $providedUuid],
            entityKeys: ['uuid' => 'my_uuid'],
        );

        $this->assertSame($providedUuid, $entity->uuid());
    }

    public function testLabel(): void
    {
        $entity = new TestEntity(['label' => 'My Entity']);

        $this->assertSame('My Entity', $entity->label());
    }

    public function testLabelDefaultsToEmptyString(): void
    {
        $entity = new TestEntity();

        $this->assertSame('', $entity->label());
    }

    public function testLabelCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['title' => 'Custom Title'],
            entityKeys: ['label' => 'title'],
        );

        $this->assertSame('Custom Title', $entity->label());
    }

    public function testBundleDefaultsToEntityTypeId(): void
    {
        $entity = new TestEntity();

        $this->assertSame('test_entity', $entity->bundle());
    }

    public function testBundleFromValues(): void
    {
        $entity = new TestEntity(
            values: ['bundle' => 'article'],
        );

        $this->assertSame('article', $entity->bundle());
    }

    public function testBundleCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['type' => 'page'],
            entityKeys: ['bundle' => 'type'],
        );

        $this->assertSame('page', $entity->bundle());
    }

    public function testIsNewWhenNoId(): void
    {
        $entity = new TestEntity();

        $this->assertTrue($entity->isNew());
    }

    public function testIsNotNewWhenHasId(): void
    {
        $entity = new TestEntity(['id' => 1]);

        $this->assertFalse($entity->isNew());
    }

    public function testEnforceIsNew(): void
    {
        $entity = new TestEntity(['id' => 1]);
        $this->assertFalse($entity->isNew());

        $entity->enforceIsNew(true);
        $this->assertTrue($entity->isNew());

        $entity->enforceIsNew(false);
        $this->assertFalse($entity->isNew());
    }

    public function testEnforceIsNewReturnsSelf(): void
    {
        $entity = new TestEntity();
        $result = $entity->enforceIsNew(true);

        $this->assertSame($entity, $result);
    }

    public function testToArray(): void
    {
        $values = ['id' => 1, 'label' => 'Test'];
        $entity = new TestEntity(
            values: $values,
            entityKeys: ['id' => 'id', 'uuid' => 'uuid', 'label' => 'label'],
        );

        $array = $entity->toArray();

        $this->assertSame(1, $array['id']);
        $this->assertSame('Test', $array['label']);
        // UUID is auto-generated.
        $this->assertArrayHasKey('uuid', $array);
    }

    public function testLanguageDefault(): void
    {
        $entity = new TestEntity();

        $this->assertSame('en', $entity->language());
    }

    public function testLanguageFromValues(): void
    {
        $entity = new TestEntity(['langcode' => 'fr']);

        $this->assertSame('fr', $entity->language());
    }

    public function testLanguageCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['lang' => 'de'],
            entityKeys: ['langcode' => 'lang'],
        );

        $this->assertSame('de', $entity->language());
    }

    public function testStringId(): void
    {
        $entity = new TestEntity(['id' => 'my_string_id']);

        $this->assertSame('my_string_id', $entity->id());
        $this->assertFalse($entity->isNew());
    }

    public function testConfigEntityNoUuidGenerated(): void
    {
        // Config entities have no 'uuid' key — UUID should not be auto-generated.
        $entity = new TestEntity(
            values: ['id' => 'article'],
            entityKeys: ['id' => 'id', 'label' => 'label'],
        );

        $this->assertSame('', $entity->uuid());
        $this->assertArrayNotHasKey('uuid', $entity->toArray());
    }

    public function testContentEntityUuidStillGenerated(): void
    {
        // Content entities with 'uuid' key should still get auto-generated UUID.
        $entity = new TestEntity(
            values: ['id' => 1],
            entityKeys: ['id' => 'id', 'uuid' => 'uuid', 'label' => 'label'],
        );

        $this->assertNotEmpty($entity->uuid());
        $this->assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',
            $entity->uuid(),
        );
    }

    public function testDuplicatePreservesIdentityAndEntityKeys(): void
    {
        $entity = new TestEntity(
            values: ['id' => 9, 'label' => 'Orig'],
            entityTypeId: 'custom_type',
            entityKeys: ['id' => 'id', 'uuid' => 'uuid', 'label' => 'label'],
        );
        $dup = $entity->duplicate();

        $this->assertNotSame($entity, $dup);
        $this->assertSame(9, $dup->id());
        $this->assertSame($entity->uuid(), $dup->uuid());
        $this->assertSame('Orig', $dup->label());
        $this->assertSame('custom_type', $dup->getEntityTypeId());
    }

    public function testDuplicatePreservesEnforceIsNew(): void
    {
        $entity = new TestEntity(['id' => 1]);
        $entity->enforceIsNew(true);
        $dup = $entity->duplicate();

        $this->assertTrue($dup->isNew());
    }

    public function testDuplicateShallowCopySharesNestedArrayByReference(): void
    {
        $entity = new TestEntity(['id' => 1, 'meta' => ['x' => 1]]);
        $dup = $entity->duplicate();

        $this->assertSame(
            $entity->get('meta'),
            $dup->get('meta'),
            'Nested array must remain a shallow copy without inspecting the private authoritative container.',
        );
    }

    public function testWithReturnsNewInstanceAndDoesNotMutateOriginal(): void
    {
        $entity = new TestEntity(['id' => 1, 'label' => 'A']);
        $next = $entity->with('label', 'B');

        $this->assertNotSame($entity, $next);
        $this->assertSame('A', $entity->label());
        $this->assertSame('B', $next->label());
    }

    public function testWithValuesRejectsStructuralRetargeting(): void
    {
        $entity = new TestEntity(['id' => 1, 'label' => 'A', 'bundle' => 'b']);

        $this->expectException(\LogicException::class);
        $this->expectExceptionMessage('Structural field test_entity.bundle is immutable after construction.');

        $entity->withValues(['label' => 'B', 'bundle' => 'page']);
    }

    public function testWithThrowsSameAsSetOnCastFailure(): void
    {
        $entity = new class (['id' => 1, 'n' => '1']) extends ContentEntityBase {
            protected array $casts = ['n' => 'int'];

            public function __construct(
                array $values = [],
                string $entityTypeId = 't',
                array $entityKeys = ['id' => 'id', 'uuid' => 'uuid', 'label' => 'label', 'bundle' => 'bundle'],
                array $fieldDefinitions = [],
            ) {
                parent::__construct($values, $entityTypeId, $entityKeys, $fieldDefinitions);
            }
        };

        $this->expectException(CastException::class);
        $entity->with('n', 'not-int');
    }

    public function testWithAcceptsBackedEnumDomainValueP2ForwardCompatible(): void
    {
        $entity = new class (['id' => 1, 'flag' => 'a']) extends ContentEntityBase {
            protected array $casts = ['flag' => SampleStringEnum::class];

            public function __construct(
                array $values = [],
                string $entityTypeId = 't',
                array $entityKeys = ['id' => 'id', 'uuid' => 'uuid', 'label' => 'label', 'bundle' => 'bundle'],
                array $fieldDefinitions = [],
            ) {
                parent::__construct($values, $entityTypeId, $entityKeys, $fieldDefinitions);
            }
        };

        $next = $entity->with('flag', SampleStringEnum::Beta);

        $this->assertSame(SampleStringEnum::Beta, $next->get('flag'));
        $this->assertSame('b', $next->toArray()['flag']);
    }

    public function testConfigEntityDuplicateReentersConstructorForStatus(): void
    {
        $entity = new TestConfigEntity(
            values: [
                'id' => 'my_config',
                'label' => 'L',
                'status' => false,
                'dependencies' => ['package' => ['core']],
            ],
            entityTypeId: 'test_config',
            entityKeys: ['id' => 'id', 'label' => 'label'],
        );

        $dup = $entity->duplicate();

        $this->assertFalse($dup->status());
        $this->assertSame(['package' => ['core']], $dup->getDependencies());
    }
}
