<?php

declare(strict_types=1);

namespace App\Access;

use Waaseyaa\Access\PermissionHandler;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand.
 */
final class ApplicationBlueprintPermissions
{
    public const string PERMISSION_EDIT_ARTICLE = 'edit article';
    public const string PERMISSION_USE_EDITORIAL_TRANSITION_PUBLISH = 'use editorial transition publish';
    public const string PERMISSION_VIEW_ARTICLE = 'view article';

    /**
     * @return array<string, array{title: string, description: string}>
     */
    public static function seed(): array
    {
        return [
            'edit article' => ['title' => 'Edit articles', 'description' => 'Edit articles'],
            'use editorial transition publish' => ['title' => 'Publish articles', 'description' => 'Publish articles'],
            'view article' => ['title' => 'View articles', 'description' => 'View articles'],
        ];
    }

    public static function register(PermissionHandler $handler): void
    {
        foreach (self::seed() as $id => $descriptor) {
            $handler->registerPermission($id, $descriptor['title'], $descriptor['description']);
        }
    }
}
