<?php

declare(strict_types=1);

namespace App\Access;

use Waaseyaa\Access\AccessPolicyInterface;
use Waaseyaa\Access\AccessResult;
use Waaseyaa\Access\AccountInterface;
use Waaseyaa\Access\Read\AuthorizationInputReader;
use Waaseyaa\Entity\EntityInterface;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Open-by-default: every branch below either grants
 * AccessResult::allowed() or defers with AccessResult::neutral(); this policy
 * never returns Forbidden and never inspects roles directly.
 */
final class ArticlePolicy implements AccessPolicyInterface
{
    public function appliesTo(string $entityTypeId): bool
    {
        return $entityTypeId === 'article';
    }

    public function access(EntityInterface $entity, string $operation, AccountInterface $account): AccessResult
    {
        assert($entity instanceof \App\Entity\Article);

        return match ($operation) {
            'view' => self::checkViewAccess($entity, $account),
            'update' => self::checkUpdateAccess($entity, $account),
            default => AccessResult::neutral("No policy opinion on '{$operation}'."),
        };
    }

    public function createAccess(string $entityTypeId, string $bundle, AccountInterface $account): AccessResult
    {
        return AccessResult::neutral('No create policy declared for this entity.');
    }

    private static function checkViewAccess(EntityInterface $entity, AccountInterface $account): AccessResult
    {
        if ($account->hasPermission('view article')) {
            return AccessResult::allowed('Policy \'article_view\' granted access.');
        }
        return AccessResult::neutral('No policy condition granted access.');
    }

    private static function checkUpdateAccess(EntityInterface $entity, AccountInterface $account): AccessResult
    {
        $inputs = new AuthorizationInputReader()->read($entity);

        if (\in_array($inputs['workflow_state'] ?? null, ['draft'], true)
            && $account->hasPermission('use editorial transition publish')) {
            return AccessResult::allowed('Policy \'article_publish_state\' granted access.');
        }
        if ($account->isAuthenticated()
            && ($inputs['author'] ?? null) !== null
            && (string) $account->id() === (string) $inputs['author']
            && $account->hasPermission('edit article')) {
            return AccessResult::allowed('Policy \'article_update_own\' granted access.');
        }
        return AccessResult::neutral('No policy condition granted access.');
    }
}
