<?php

declare(strict_types=1);

namespace App\Access;

use Waaseyaa\Access\AccessPolicyInterface;
use Waaseyaa\Access\AccessResult;
use Waaseyaa\Access\AccountInterface;
use Waaseyaa\Access\FieldAccessPolicyInterface;
use Waaseyaa\Access\Gate\PolicyAttribute;
use Waaseyaa\Access\Read\AuthorizationInputReader;
use Waaseyaa\Entity\EntityInterface;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Open-by-default: every entity-level branch below either
 * grants AccessResult::allowed() or defers with AccessResult::neutral(); this
 * policy never returns an entity-level Forbidden and never inspects roles
 * directly. Field-level: the entity's authorization inputs are edit-sealed so an
 * entity-level grant cannot rewrite the inputs it was decided on.
 */
#[PolicyAttribute(entityType: 'article')]
final class ArticlePolicy implements AccessPolicyInterface, FieldAccessPolicyInterface
{
    public function appliesTo(string $entityTypeId): bool
    {
        return $entityTypeId === 'article';
    }

    public function access(EntityInterface $entity, string $operation, AccountInterface $account): AccessResult
    {
        assert($entity instanceof \App\Entity\Article);

        return match ($operation) {
            'view' => self::checkViewAccess($entity, $account),
            'update' => self::checkUpdateAccess($entity, $account),
            'delete' => self::checkDeleteAccess($entity, $account),
            default => AccessResult::neutral("No policy opinion on '{$operation}'."),
        };
    }

    public function createAccess(string $entityTypeId, string $bundle, AccountInterface $account): AccessResult
    {
        if ($account->hasPermission('edit article')) {
            return AccessResult::allowed('Policy \'article_create\' granted create access.');
        }

        return AccessResult::neutral('No create policy condition granted access.');
    }

    public function fieldAccess(EntityInterface $entity, string $fieldName, string $operation, AccountInterface $account): AccessResult
    {
        if ($operation !== 'edit') {
            return AccessResult::neutral('Authorization inputs are sealed against edit only.');
        }
        if ($fieldName === 'author' && !$entity->isNew()) {
            return AccessResult::forbidden('Ownership of a persisted entity is not reassignable through an update grant.');
        }
        if ($fieldName === 'workflow_state') {
            return AccessResult::forbidden('workflow_state is engine-owned; move it through a workflow transition.');
        }

        return AccessResult::neutral("No field-edit opinion on '{$fieldName}'.");
    }

    private static function checkViewAccess(EntityInterface $entity, AccountInterface $account): AccessResult
    {
        if ($account->hasPermission('view article')) {
            return AccessResult::allowed('Policy \'article_view\' granted access.');
        }
        return AccessResult::neutral('No policy condition granted access.');
    }

    private static function checkUpdateAccess(EntityInterface $entity, AccountInterface $account): AccessResult
    {
        $inputs = new AuthorizationInputReader()->read($entity);

        if (\in_array($inputs['workflow_state'] ?? null, ['draft'], true)
            && $account->hasPermission('use editorial transition publish')) {
            return AccessResult::allowed('Policy \'article_publish_state\' granted access.');
        }
        if ($account->isAuthenticated()
            && ($inputs['author'] ?? null) !== null
            && (string) $account->id() === (string) $inputs['author']
            && $account->hasPermission('edit article')) {
            return AccessResult::allowed('Policy \'article_update_own\' granted access.');
        }
        return AccessResult::neutral('No policy condition granted access.');
    }

    private static function checkDeleteAccess(EntityInterface $entity, AccountInterface $account): AccessResult
    {
        $inputs = new AuthorizationInputReader()->read($entity);

        if ($account->isAuthenticated()
            && ($inputs['author'] ?? null) !== null
            && (string) $account->id() === (string) $inputs['author']
            && $account->hasPermission('edit article')) {
            return AccessResult::allowed('Policy \'article_delete_own\' granted access.');
        }
        return AccessResult::neutral('No policy condition granted access.');
    }
}
