<?php

declare(strict_types=1);

// Migrated by bin/migrate-surface-map from docs/public-surface-map.php
// and docs/public-surface-map.md (FW-DELIVERY-SURFACE-01 / #2901). This
// file, not the generated docs/public-surface-map.*, is the editable
// authority — see docs/specs/public-surface-declarations.md.
return [
    'entries' => [
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationActivationAuthorizerInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationActivatorInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationCandidateMaintenanceInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationCandidateSweepAuthorizerInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationGenesisActivatorInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Activation\\ConfigurationRollbackValidatorInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Audit\\ConfigAuditChannel', 'disposition' => 'public', 'purpose' => '`CHANNEL` constant = `\'config.audit\'` (charter §4.4 amendment) (M-003, WP07)'],
        ['fqcn' => 'Waaseyaa\\Config\\Audit\\ConfigAuditEvent', 'disposition' => 'public', 'purpose' => 'Entity-type, id, operation, actor, before-after diff summary (M-003, WP07)'],
        ['fqcn' => 'Waaseyaa\\Config\\Authority\\ActiveConfigurationBridgeInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Authority\\ConfigurationGenerationResolverInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Backend\\BackendRestrictionEnforcer', 'disposition' => 'public', 'purpose' => 'Boot-time enforcement: config entities must declare `sql-blob` or `sql-column`; `ALLOWED_BACKEND_IDS` constant (M-003, WP08)'],
        ['fqcn' => 'Waaseyaa\\Config\\ConfigFactoryInterface', 'disposition' => 'public', 'purpose' => 'Creates and caches `ConfigInterface` instances by name'],
        ['fqcn' => 'Waaseyaa\\Config\\ConfigInterface', 'disposition' => 'public', 'purpose' => 'Read/write access to a named configuration object with key-path addressing'],
        ['fqcn' => 'Waaseyaa\\Config\\ConfigManagerInterface', 'disposition' => 'public', 'purpose' => 'Manages config storage backends and export/import lifecycle'],
        ['fqcn' => 'Waaseyaa\\Config\\Dependency\\ConfigDependencyInterface', 'disposition' => 'public', 'purpose' => 'Config-entity contract: `configDependencies(): string[]` returns `<entity_type>.<entity_id>` ids consumed by the DAG (M-003, WP01)'],
        ['fqcn' => 'Waaseyaa\\Config\\Dependency\\DependencyGraph', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Dependency\\DependencyResolver', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Dependency\\Exception\\ConfigDependencyCycleException', 'disposition' => 'public', 'purpose' => 'Raised when the sync-store DAG contains a cycle; carries the full cycle path (M-003)'],
        ['fqcn' => 'Waaseyaa\\Config\\Dependency\\Exception\\ConfigDependencyMissingException', 'disposition' => 'public', 'purpose' => 'Raised when a `_meta.dependencies` entry references a config id absent from both stores (M-003)'],
        ['fqcn' => 'Waaseyaa\\Config\\Drift\\ConfigDriftSnapshotReaderInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Event\\ConfigEvents', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Exception\\ConfigCommandCollisionException', 'disposition' => 'public', 'purpose' => 'Raised at boot when an app/extension command claims a reserved `config:*` sub-verb (M-003, WP09)'],
        ['fqcn' => 'Waaseyaa\\Config\\Exception\\ConfigImportFailedException', 'disposition' => 'public', 'purpose' => 'Raised per-entity during `config:import`; carries entity id + cause (M-003, WP04)'],
        ['fqcn' => 'Waaseyaa\\Config\\Exception\\ConfigSerializationException', 'disposition' => 'public', 'purpose' => 'Raised on `_meta.entity_type` mismatch or other YAML format errors (M-003, WP02)'],
        ['fqcn' => 'Waaseyaa\\Config\\Exception\\ImmutableConfigException', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Exception\\InvalidConfigBackendException', 'disposition' => 'public', 'purpose' => 'Raised when a config entity declares `vector` / `remote` / other disallowed backend (M-003, WP08)'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestBundleSigner', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestEd25519Signer', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestEd25519Verifier', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestEnvelopeFile', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestSignatureVerifierInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestSignerInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestSigningResult', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigManifestTrustPolicy', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Manifest\\ConfigReplayStateReaderInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Schema\\Ai\\McpAuthMode', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Schema\\Ai\\McpAvailability', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Schema\\ConfigSemanticValidatorInterface', 'disposition' => 'public', 'ref' => '#2458'],
        ['fqcn' => 'Waaseyaa\\Config\\StorageInterface', 'disposition' => 'public', 'purpose' => 'Reads and writes raw configuration data arrays by name'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigDiffer', 'disposition' => 'public', 'purpose' => 'Unified-diff renderer with UUID-tracked rename detection; backs `config:diff` (M-003, WP05)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigExportFileResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigExportResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigExporter', 'disposition' => 'public', 'purpose' => 'Active → sync; backs `config:export`; honours `--diff` and `--dry-run` (M-003, WP03)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigImportApplyHookInterface', 'disposition' => 'public', 'purpose' => 'Cross-cutting hook fired per applied entity during `config:import` (extension point) (M-003, WP04)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigImportEntryResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigImportPreflightInterface', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigImportResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigImporter', 'disposition' => 'public', 'purpose' => 'Sync → active in topological order; per-entity transaction; orphan-warn default (M-003, WP04)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigManifestEntry', 'disposition' => 'public', 'purpose' => 'Per-entity manifest row consumed by exporter/importer dashboards (M-003)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigResetter', 'disposition' => 'public', 'purpose' => 'Single-entity rollback from sync store; logs to `config.audit`; backs `config:reset` (M-003, WP07)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigStatusReporter', 'disposition' => 'public', 'purpose' => 'Computes in-sync / drift / sync-only / active-only counts; backs `config:status` (M-003, WP05)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncDeserializer', 'disposition' => 'public', 'purpose' => 'YAML → `ConfigSyncFile`; validates `_meta.entity_type` matches filename prefix (M-003, WP02)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncFile', 'disposition' => 'public', 'purpose' => 'In-memory parsed sync file: `_meta` block + field values (M-003, WP02)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncFileSourceInterface', 'disposition' => 'public', 'purpose' => 'Extension point: alternative sync-file sources (e.g. in-memory test sources) (M-003)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncRepository', 'disposition' => 'public', 'purpose' => 'Filesystem read/write under `config.sync_path` (default `storage/config-sync/`) (M-003, WP02)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncSerializer', 'disposition' => 'public', 'purpose' => 'Entity → YAML; sorts keys alphabetically; emits leading `_meta` block (M-003, WP02)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigSyncValidator', 'disposition' => 'public', 'purpose' => 'Runs `FieldDefinition::validators()` over each sync file; powers `config:validate` (M-003, WP06)'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigValidateEntry', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\ConfigValidateResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\DiffResult', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\FieldValueMapper', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\FieldViolation', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\SignedEnvelopeConfigImportPreflight', 'disposition' => 'public'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\StatusEntry', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\Sync\\StatusReport', 'disposition' => 'internal'],
        ['fqcn' => 'Waaseyaa\\Config\\TranslatableConfigFactoryInterface', 'disposition' => 'public', 'purpose' => 'Creates language-specific overrides of configuration objects'],
    ],
    'notes' => [
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigCommand` (abstract class): Base for the seven `config:*` commands; exposes `RESERVED_VERBS`, `RESERVED_FULL_VERBS`, `RESERVED_FQCNS` constants for collision checks (M-003, WP09)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigExportCommand` (command): `bin/waaseyaa config:export [--diff] [--dry-run]` (M-003, WP03)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigImportCommand` (command): `bin/waaseyaa config:import [--dry-run] [--delete-orphans] [--halt-on-error] [--no-dependency-check]` (M-003, WP04)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigDiffCommand` (command): `bin/waaseyaa config:diff [<entity-type>.<id>]` (M-003, WP05)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigStatusCommand` (command): `bin/waaseyaa config:status [--format=plain|json]` (M-003, WP05)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigValidateCommand` (command): `bin/waaseyaa config:validate` (M-003, WP06)',
        '`Waaseyaa\\CLI\\Command\\Config\\ConfigResetCommand` (command): `bin/waaseyaa config:reset <entity-type>.<id> [--yes]` (M-003, WP07)',
    ],
];
