<?php

// Authoritative disposition map for all public API elements.
// Format: 'Fully\Qualified\ClassName' => 'public|internal|extract|remove'
// This file is verified by PublicSurfaceVerificationTest.
//
// Scope (audit C-16): tracks contract shapes only — interfaces, abstract classes,
// traits, enums (the public extension surface). Concrete final/plain classes are
// implementations, not extension points, and are intentionally NOT listed. The
// vocabulary is binary public|internal, not the charter's aborted 3-tier model
// (audit C-15). See docs/specs/stability-charter.md §2.

declare(strict_types=1);

return [
    // Layer 0: Foundation — public
    'Waaseyaa\Foundation\Asset\AssetManagerInterface' => 'public',
    'Waaseyaa\Foundation\Diagnostic\HealthCheckerInterface' => 'public',
    'Waaseyaa\Foundation\Diagnostic\DiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Log\LoggerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Handler\HandlerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Formatter\FormatterInterface' => 'public',
    'Waaseyaa\Foundation\Log\Processor\ProcessorInterface' => 'public',
    'Waaseyaa\Foundation\Log\LoggerTrait' => 'public',
    'Waaseyaa\Foundation\Log\LogLevel' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\RateLimit\RateLimiterInterface' => 'public',
    'Waaseyaa\Foundation\Schema\SchemaRegistryInterface' => 'public',
    // Schema-evolution v2 (mission #529): diff algebra, compiler output,
    // platform-neutral validation codes, v2 migration authoring contract.
    'Waaseyaa\Foundation\Schema\Diff\OpKind' => 'public',
    'Waaseyaa\Foundation\Schema\Diff\SchemaDiffOp' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\CompiledStep' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Sqlite\SqliteDiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Validation\ValidationDiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Validation\ValidationException' => 'public',
    'Waaseyaa\Foundation\Schema\Migration\MigrationInterfaceV2' => 'public',
    'Waaseyaa\Foundation\Migration\Dag\MigrationKind' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProviderInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProvider' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\KernelServicesInterface' => 'public',
    // Access policy bootstrap extension point (M-B / WP02): implementors supply
    // constructor-parameter resolution for policies that need kernel services.
    'Waaseyaa\Foundation\Kernel\Bootstrap\PolicyDependencyResolverInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\ConfiguresHttpKernelInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\ProvidesConsoleCommandsInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\ProvidesRolesInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasGraphqlMutationOverridesInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasHttpDomainRoutersInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasRenderCacheListenersInterface' => 'public',
    // Migration-provider injection capability (PR #1614): kernel guards provider
    // wiring via this named interface instead of a Layer-3 concrete edge.
    'Waaseyaa\Foundation\ServiceProvider\Capability\AcceptsMigrationProvidersInterface' => 'public',
    'Waaseyaa\Foundation\Event\DomainEvent' => 'public',
    'Waaseyaa\Foundation\Event\EventDispatcherInterface' => 'public',
    'Waaseyaa\Foundation\Ingestion\IngestionErrorCode' => 'public',
    'Waaseyaa\Foundation\Exception\WaaseyaaException' => 'public',
    'Waaseyaa\Foundation\Http\HttpServiceResolverInterface' => 'public',
    'Waaseyaa\Foundation\Http\JsonApiResponseTrait' => 'public',
    'Waaseyaa\Foundation\Http\Inbound\InboundHttpRequestInterface' => 'public',
    'Waaseyaa\Foundation\Http\Router\DomainRouterInterface' => 'public',
    'Waaseyaa\Foundation\Http\LanguagePathStripperInterface' => 'public',
    'Waaseyaa\Foundation\Http\Inertia\InertiaFullPageRendererInterface' => 'public',
    'Waaseyaa\Foundation\Http\Inertia\InertiaPageResultInterface' => 'public',
    // Listing pipeline request-context bridge (mission listing-pipeline-v1-01KRMN0B, charter §5.9).
    'Waaseyaa\Foundation\Http\RequestContext' => 'public',
    'Waaseyaa\Foundation\Migration\Migration' => 'public',
    // Schema-evolution v2 ledger verify surface (mission #529 / WP09).
    'Waaseyaa\Foundation\Migration\VerifyResult' => 'public',
    'Waaseyaa\Foundation\Community\CommunityContextInterface' => 'public',
    'Waaseyaa\Foundation\Sovereignty\SovereigntyConfigInterface' => 'public',
    'Waaseyaa\Foundation\Sovereignty\SovereigntyProfile' => 'public',
    'Waaseyaa\Cache\CacheBackendInterface' => 'public',
    'Waaseyaa\Cache\CacheFactoryInterface' => 'public',
    'Waaseyaa\Cache\CacheTagsInvalidatorInterface' => 'public',
    'Waaseyaa\Cache\TagAwareCacheInterface' => 'public',
    // Listing pipeline cache tag/context surface (mission listing-pipeline-v1-01KRMN0B, charter §5.9).
    'Waaseyaa\Cache\TaggedCacheInterface' => 'public',
    'Waaseyaa\Cache\ContextRegistry' => 'public',
    'Waaseyaa\Cache\ContextResolver' => 'public',
    'Waaseyaa\Cache\ContextNames' => 'public',
    'Waaseyaa\Cache\Exception\InvalidCacheTagException' => 'public',
    'Waaseyaa\Database\DatabaseInterface' => 'public',
    'Waaseyaa\Database\SelectInterface' => 'public',
    'Waaseyaa\Database\InsertInterface' => 'public',
    'Waaseyaa\Database\UpdateInterface' => 'public',
    'Waaseyaa\Database\DeleteInterface' => 'public',
    'Waaseyaa\Database\SchemaInterface' => 'public',
    'Waaseyaa\Database\TransactionInterface' => 'public',
    'Waaseyaa\Plugin\PluginInspectionInterface' => 'public',
    'Waaseyaa\Plugin\PluginManagerInterface' => 'public',
    'Waaseyaa\Plugin\PluginBase' => 'public',
    'Waaseyaa\TypedData\TypedDataInterface' => 'public',
    'Waaseyaa\TypedData\DataDefinitionInterface' => 'public',
    'Waaseyaa\TypedData\ComplexDataInterface' => 'public',
    'Waaseyaa\TypedData\ListInterface' => 'public',
    'Waaseyaa\TypedData\PrimitiveInterface' => 'public',
    'Waaseyaa\TypedData\TypedDataManagerInterface' => 'public',
    'Waaseyaa\TypedData\CastTokenMapper' => 'public',
    'Waaseyaa\TypedData\Coercion\CoercionException' => 'public',
    'Waaseyaa\TypedData\Coercion\EntityCastCoercion' => 'public',
    'Waaseyaa\I18n\LanguageManagerInterface' => 'public',
    'Waaseyaa\I18n\TranslatorInterface' => 'public',
    'Waaseyaa\Queue\QueueInterface' => 'public',
    'Waaseyaa\Testing\Traits\CreatesApplication' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithApi' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithAuth' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithEvents' => 'public',
    'Waaseyaa\Testing\Traits\RefreshDatabase' => 'public',
    'Waaseyaa\ErrorHandler\SolutionInterface' => 'public',
    'Waaseyaa\ErrorHandler\SolutionProviderInterface' => 'public',

    // Layer 0: Foundation — internal
    'Waaseyaa\Foundation\Kernel\AbstractKernel' => 'internal',
    'Waaseyaa\Foundation\Tenant\TenantResolverInterface' => 'internal',
    'Waaseyaa\Plugin\Discovery\PluginDiscoveryInterface' => 'internal',
    'Waaseyaa\Plugin\Extension\KnowledgeToolingExtensionInterface' => 'internal',
    'Waaseyaa\Plugin\Factory\PluginFactoryInterface' => 'internal',
    'Waaseyaa\Queue\Handler\HandlerInterface' => 'internal',
    'Waaseyaa\Queue\Transport\TransportInterface' => 'internal',
    'Waaseyaa\Queue\FailedJobRepositoryInterface' => 'internal',
    'Waaseyaa\Queue\Job' => 'internal',
    'Waaseyaa\Scheduler\Lock\LockInterface' => 'internal',
    'Waaseyaa\Scheduler\ScheduleEntriesInterface' => 'public',
    'Waaseyaa\AI\Agent\Provider\ProviderException' => 'public',
    'Waaseyaa\HttpClient\SseLineStreamInterface' => 'public',
    'Waaseyaa\Scheduler\ScheduleInterface' => 'internal',
    'Waaseyaa\State\StateInterface' => 'internal',
    'Waaseyaa\Mail\MailerInterface' => 'internal',
    'Waaseyaa\Mail\Transport\TransportInterface' => 'internal',
    'Waaseyaa\HttpClient\HttpClientInterface' => 'internal',
    'Waaseyaa\Ingestion\PayloadValidatorInterface' => 'internal',
    'Waaseyaa\Ingestion\EnvelopeValidator' => 'internal',
    'Waaseyaa\Testing\WaaseyaaTestCase' => 'internal',

    // Layer 1: Core Data — public
    'Waaseyaa\Entity\EntityInterface' => 'public',
    'Waaseyaa\Entity\EntityBase' => 'public',
    'Waaseyaa\Entity\ContentEntityBase' => 'public',
    'Waaseyaa\Entity\ContentEntityInterface' => 'public',
    'Waaseyaa\Entity\ConfigEntityBase' => 'public',
    'Waaseyaa\Entity\ConfigEntityInterface' => 'public',
    'Waaseyaa\Entity\EntityTypeInterface' => 'public',
    'Waaseyaa\Entity\EntityTypeManagerInterface' => 'public',
    'Waaseyaa\Entity\DefinesEntityType' => 'public',
    'Waaseyaa\Entity\FieldableInterface' => 'public',
    'Waaseyaa\Entity\RevisionableInterface' => 'public',
    'Waaseyaa\Entity\TranslatableInterface' => 'public',
    'Waaseyaa\Entity\TranslatableEntityTrait' => 'public',
    'Waaseyaa\Entity\RevisionableEntityTrait' => 'public',
    'Waaseyaa\Entity\Community\HasCommunityInterface' => 'public',
    'Waaseyaa\Entity\Community\HasCommunityTrait' => 'public',
    'Waaseyaa\Entity\Repository\EntityRepositoryInterface' => 'public',
    'Waaseyaa\Entity\Event\EntityEventFactoryInterface' => 'public',
    'Waaseyaa\Entity\Field\FieldDefinitionRegistryInterface' => 'public',
    'Waaseyaa\Entity\Storage\EntityStorageInterface' => 'public',
    'Waaseyaa\Entity\Storage\RevisionableStorageInterface' => 'public',
    'Waaseyaa\Entity\Storage\EntityQueryInterface' => 'public',
    'Waaseyaa\Entity\Audit\EntityAuditKey' => 'public',
    'Waaseyaa\Entity\Audit\LifecycleAuditKey' => 'public',
    'Waaseyaa\Entity\Event\EntityEvents' => 'public',
    'Waaseyaa\Entity\Hydration\HydratableFromStorageInterface' => 'public',
    'Waaseyaa\Entity\Hydration\HydrationContext' => 'public',
    'Waaseyaa\Entity\Cast\FromArrayEntityValueInterface' => 'public',
    'Waaseyaa\Entity\EntityValues' => 'public',
    'Waaseyaa\Entity\Snapshot\EntityValuesSnapshot' => 'public',
    'Waaseyaa\Entity\DateTime\EntityClockInterface' => 'public',
    'Waaseyaa\Entity\DateTime\UtcEntityClock' => 'public',
    'Waaseyaa\Entity\DateTime\FixedEntityClock' => 'public',
    'Waaseyaa\Entity\DateTime\TimestampFieldConvention' => 'public',
    'Waaseyaa\EntityStorage\Driver\EntityStorageDriverInterface' => 'public',
    'Waaseyaa\EntityStorage\Connection\ConnectionResolverInterface' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnknownFieldException' => 'public',
    'Waaseyaa\EntityStorage\Exception\BundleAmbiguousFieldException' => 'public',
    // entity-storage-v2 mission public surface (WP01–WP12, M-001)
    // WP01 — backend registration
    'Waaseyaa\EntityStorage\Backend\FieldStorageBackendInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\HasFieldStorageBackendsInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\IsFrameworkBackendProviderInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\ReservedBackendIds' => 'public',
    'Waaseyaa\EntityStorage\Backend\BackendRegistrar' => 'public',
    'Waaseyaa\EntityStorage\Backend\BackendRegistrarFactory' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnsupportedQueryException' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnsupportedListingException' => 'public',
    // WP02 — coordinator
    'Waaseyaa\EntityStorage\EntityStorageCoordinator' => 'public',
    'Waaseyaa\EntityStorage\BackendResolver' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnknownBackendException' => 'public',
    // WP03 — sql-blob backend
    'Waaseyaa\EntityStorage\Backend\SqlBlobBackend' => 'public',
    // WP04 — lifecycle events
    'Waaseyaa\EntityStorage\Event\EntityLifecycleEventInterface' => 'public',
    'Waaseyaa\EntityStorage\Event\BeforeSaveEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AfterSaveEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\BeforeDeleteEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AfterDeleteEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AbortOperationException' => 'public',
    'Waaseyaa\EntityStorage\Exception\PartialSaveException' => 'public',
    'Waaseyaa\EntityStorage\SaveContext' => 'public',
    'Waaseyaa\EntityStorage\CoordinatorLifecycleDispatcher' => 'public',
    // WP05 — sql-column backend
    'Waaseyaa\EntityStorage\Backend\SqlColumnBackend' => 'public',
    'Waaseyaa\EntityStorage\Backend\SqlColumnSchemaBuilder' => 'public',
    'Waaseyaa\EntityStorage\Backend\SqlColumnQueryTranslator' => 'public',
    'Waaseyaa\EntityStorage\Backend\TypeMapping' => 'public',
    // WP06 — definition validator
    'Waaseyaa\EntityStorage\Query\DefinitionValidator' => 'public',
    // WP07 — revisionable entities (entity package)
    // ('Waaseyaa\Entity\RevisionableEntityTrait' is listed once in the Layer-1 public block above.)
    'Waaseyaa\Entity\RevisionableEntityInterface' => 'public',
    'Waaseyaa\Entity\RevisionMetadata' => 'public',
    'Waaseyaa\EntityStorage\Schema\RevisionTableBuilder' => 'public',
    // WP08 — revisionable storage
    'Waaseyaa\EntityStorage\RevisionPruningPolicy' => 'public',
    'Waaseyaa\EntityStorage\RevisionPruningReport' => 'public',
    // WP09 — revision access (access package)
    'Waaseyaa\Access\Gate\RevisionAccessRouter' => 'public',
    // WP10 — migration CLI (cli package)
    'Waaseyaa\CLI\Handler\MakeStorageMigrationHandler' => 'public',
    'Waaseyaa\CLI\Provider\MakeStorageMigrationServiceProvider' => 'public',
    'Waaseyaa\CLI\Command\Migration\StorageMigrationEmitter' => 'public',
    'Waaseyaa\CLI\Command\Migration\StorageMigrationTemplate' => 'public',
    'Waaseyaa\CLI\Command\Migration\BackfillHelper' => 'public',
    'Waaseyaa\CLI\Command\Migration\UnmappedFieldTypeException' => 'public',
    'Waaseyaa\CLI\Command\Migration\BackfillRowCountMismatchException' => 'public',
    // WP12 — conformance test harness (autoload-dev only; still part of stable surface for extenders)
    'Waaseyaa\EntityStorage\Testing\Contract\FieldStorageBackendContractTestCase' => 'public',
    // EntityQuery marker interface
    'Waaseyaa\EntityStorage\Query\EntityQuery' => 'public',
    // entity-storage-translations-v1 mission public surface (M-006, ADR 017)
    // `TranslatableInterface` (already listed above) is the stable contract; `language()` retained as deprecated alias for `activeLangcode()`.
    'Waaseyaa\Entity\Exception\EntityTranslationException' => 'public',
    'Waaseyaa\Entity\Event\EntityEvent' => 'public',
    'Waaseyaa\Entity\Event\TranslationEvent' => 'public',
    'Waaseyaa\Entity\Hydration\FallbackChainResolver' => 'public',
    // Conformance test harness for `TranslatableInterface` implementations.
    'Waaseyaa\Entity\Testing\Translation\TranslatableEntityContractTest' => 'public',
    // M-004 (entity-storage-translatable-revisions) — two-axis storage stable surface.
    // Charter §5.3 amendment; spec docs/specs/entity-storage-two-axis.md.
    'Waaseyaa\EntityStorage\Exception\StorageMigrationException' => 'public',
    'Waaseyaa\EntityStorage\Driver\RevisionableStorageDriver' => 'public',
    'Waaseyaa\EntityStorage\Schema\TranslationSchemaHandler' => 'public',
    'Waaseyaa\EntityStorage\Listing\TwoAxisFilterResolver' => 'public',
    'Waaseyaa\EntityStorage\Revision\RevisionPruningPolicy' => 'public',
    'Waaseyaa\Access\Policy\RevisionPolicyComposition' => 'public',
    'Waaseyaa\Access\AccountInterface' => 'public',
    // Acting-account context (mission #1644/#1645): request-scoped holder read
    // by entity-storage (revision author) and audit (actor attribution).
    'Waaseyaa\Access\Context\AccountContextInterface' => 'public',
    'Waaseyaa\Access\AccessPolicyInterface' => 'public',
    'Waaseyaa\Access\ContextAwareAccessPolicyInterface' => 'public',
    'Waaseyaa\Access\FieldAccessPolicyInterface' => 'public',
    'Waaseyaa\Access\PermissionHandlerInterface' => 'public',
    'Waaseyaa\Access\Gate\GateInterface' => 'public',
    'Waaseyaa\Access\Gate\ListingFastPathProbeInterface' => 'public',
    'Waaseyaa\Access\AccessStatus' => 'public',
    'Waaseyaa\Auth\Config\MailMissingPolicy' => 'public',
    'Waaseyaa\Config\ConfigInterface' => 'public',
    'Waaseyaa\Config\ConfigFactoryInterface' => 'public',
    'Waaseyaa\Config\ConfigManagerInterface' => 'public',
    'Waaseyaa\Config\StorageInterface' => 'public',
    'Waaseyaa\Config\TranslatableConfigFactoryInterface' => 'public',
    'Waaseyaa\Config\Event\ConfigEvents' => 'public',
    // M-003 (config-management-v1) — CMI sync substrate. Charter §5.5; spec docs/specs/config-management.md.
    'Waaseyaa\Config\Dependency\ConfigDependencyInterface' => 'public',
    'Waaseyaa\Config\Dependency\Exception\ConfigDependencyCycleException' => 'public',
    'Waaseyaa\Config\Dependency\Exception\ConfigDependencyMissingException' => 'public',
    'Waaseyaa\Config\Dependency\DependencyGraph' => 'internal',
    'Waaseyaa\Config\Dependency\DependencyResolver' => 'internal',
    'Waaseyaa\Config\Sync\ConfigSyncFile' => 'public',
    'Waaseyaa\Config\Sync\ConfigSyncSerializer' => 'public',
    'Waaseyaa\Config\Sync\ConfigSyncDeserializer' => 'public',
    'Waaseyaa\Config\Sync\ConfigSyncRepository' => 'public',
    'Waaseyaa\Config\Sync\ConfigSyncFileSourceInterface' => 'public',
    'Waaseyaa\Config\Sync\ConfigSyncValidator' => 'public',
    'Waaseyaa\Config\Sync\ConfigExporter' => 'public',
    'Waaseyaa\Config\Sync\ConfigImporter' => 'public',
    'Waaseyaa\Config\Sync\ConfigImportApplyHookInterface' => 'public',
    'Waaseyaa\Config\Sync\ConfigDiffer' => 'public',
    'Waaseyaa\Config\Sync\ConfigStatusReporter' => 'public',
    'Waaseyaa\Config\Sync\ConfigResetter' => 'public',
    'Waaseyaa\Config\Sync\ConfigManifestEntry' => 'public',
    'Waaseyaa\Config\Sync\FieldValueMapper' => 'internal',
    'Waaseyaa\Config\Sync\DiffResult' => 'internal',
    'Waaseyaa\Config\Sync\StatusEntry' => 'internal',
    'Waaseyaa\Config\Sync\StatusReport' => 'internal',
    'Waaseyaa\Config\Sync\FieldViolation' => 'internal',
    'Waaseyaa\Config\Sync\ConfigExportFileResult' => 'internal',
    'Waaseyaa\Config\Sync\ConfigExportResult' => 'internal',
    'Waaseyaa\Config\Sync\ConfigImportEntryResult' => 'internal',
    'Waaseyaa\Config\Sync\ConfigImportResult' => 'internal',
    'Waaseyaa\Config\Sync\ConfigValidateEntry' => 'internal',
    'Waaseyaa\Config\Sync\ConfigValidateResult' => 'internal',
    'Waaseyaa\Config\Audit\ConfigAuditChannel' => 'public',
    'Waaseyaa\Config\Audit\ConfigAuditEvent' => 'public',
    'Waaseyaa\Config\Backend\BackendRestrictionEnforcer' => 'public',
    'Waaseyaa\Config\Exception\InvalidConfigBackendException' => 'public',
    'Waaseyaa\Config\Exception\ConfigSerializationException' => 'public',
    'Waaseyaa\Config\Exception\ConfigImportFailedException' => 'public',
    'Waaseyaa\Config\Exception\ConfigCommandCollisionException' => 'public',
    'Waaseyaa\Config\Exception\ImmutableConfigException' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigExportCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigImportCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigDiffCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigStatusCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigValidateCommand' => 'public',
    'Waaseyaa\CLI\Command\Config\ConfigResetCommand' => 'public',
    'Waaseyaa\Field\FieldItemInterface' => 'public',
    'Waaseyaa\Field\FieldItemListInterface' => 'public',
    'Waaseyaa\Field\FieldDefinitionInterface' => 'public',
    'Waaseyaa\Field\FieldStorage' => 'public',
    'Waaseyaa\Field\FieldTypeInterface' => 'public',
    'Waaseyaa\Field\FieldFormatterInterface' => 'public',
    'Waaseyaa\Field\FieldTypeManagerInterface' => 'public',
    'Waaseyaa\Field\FieldItemBase' => 'public',
    // Transitional static-seam base (audit C-24 train 1). Internal for now —
    // field-type plugins still extend FieldItemBase; train 2 reparents them onto
    // this and removes FieldItemBase, at which point it becomes the public base.
    'Waaseyaa\Field\AbstractFieldType' => 'internal',
    'Waaseyaa\Field\Item\LabeledCase' => 'public',
    'Waaseyaa\Field\ViewModeConfigInterface' => 'public',
    // Classification labels: clearance/hold access, label registry, parent resolution.
    'Waaseyaa\Field\Classification\ClassificationClearanceCheckerInterface' => 'public',
    'Waaseyaa\Field\Classification\ClassificationLabelRegistryInterface' => 'public',
    'Waaseyaa\Field\Classification\ClassificationParentResolverInterface' => 'public',

    // Layer 1: Core Data — internal
    'Waaseyaa\EntityStorage\Hydration\EntityInstantiator' => 'internal',
    'Waaseyaa\Access\ErrorPageRendererInterface' => 'internal',
    'Waaseyaa\Field\ComputedFieldInterface' => 'internal',
    'Waaseyaa\Auth\Token\AuthTokenRepositoryInterface' => 'internal',
    'Waaseyaa\Auth\RateLimiterInterface' => 'internal',

    // Layer 2: Content Types — public
    'Waaseyaa\Media\FileRepositoryInterface' => 'public',
    'Waaseyaa\Path\PathAliasManagerInterface' => 'public',
    'Waaseyaa\Relationship\VisibilityFilterInterface' => 'public',
    'Waaseyaa\NorthCloud\Sync\NcHitToEntityMapperInterface' => 'public',
    'Waaseyaa\NorthCloud\Sync\NcHitSupportDiagnosticsInterface' => 'public',

    // Layer 3: Services — public
    'Waaseyaa\Search\SearchProviderInterface' => 'public',
    'Waaseyaa\Search\SearchIndexerInterface' => 'public',
    'Waaseyaa\Search\BatchSearchIndexerInterface' => 'public',
    'Waaseyaa\Search\SearchIndexableInterface' => 'public',
    'Waaseyaa\Search\Access\SearchAccessChecker' => 'public',
    'Waaseyaa\Notification\NotificationInterface' => 'public',
    'Waaseyaa\Notification\NotifiableInterface' => 'public',
    'Waaseyaa\Notification\NotifiableTrait' => 'public',
    'Waaseyaa\Notification\ChannelInterface' => 'public',
    'Waaseyaa\Billing\PlanTier' => 'public',
    // Migration platform plugin contracts (mission migration-platform-v1-01KRCDE9 WP01).
    'Waaseyaa\Migration\Plugin\SourcePluginInterface' => 'public',
    'Waaseyaa\Migration\Plugin\ProcessPluginInterface' => 'public',
    'Waaseyaa\Migration\Plugin\DestinationPluginInterface' => 'public',
    'Waaseyaa\Migration\Discovery\HasMigrationPluginsInterface' => 'public',
    // Migration platform discovery / dependency graph (mission migration-platform-v1-01KRCDE9 WP02).
    'Waaseyaa\Migration\Discovery\HasMigrationsInterface' => 'public',
    // Migration content-model derivation contract. UNWIRED scaffolding (audit C-5):
    // the ContentModelRegistrar is bound by no ServiceProvider and deriveContentModel()
    // has no callers; the kernel capability bus dispatches HasMigrationsInterface only.
    // Demoted to 'internal' (shipped but unsupported) until wired; see
    // docs/specs/migration-platform.md "Unwired scaffolding".
    'Waaseyaa\Migration\ContentModel\DerivesContentModelInterface' => 'internal',
    // Migration platform DTOs / value objects (mission migration-platform-v1-01KRCDE9 WP01..WP04).
    'Waaseyaa\Migration\MigrationDefinition' => 'public',
    'Waaseyaa\Migration\SourceId' => 'public',
    'Waaseyaa\Migration\Plugin\SourceRecord' => 'public',
    'Waaseyaa\Migration\Plugin\DestinationRecord' => 'public',
    'Waaseyaa\Migration\Plugin\WriteResult' => 'public',
    'Waaseyaa\Migration\Plugin\ProcessContext' => 'public',
    // Migration platform destination (WP05).
    'Waaseyaa\Migration\Plugin\Destination\EntityDestination' => 'public',
    'Waaseyaa\Migration\Plugin\Destination\EntityDestinationFactory' => 'public',
    // Migration platform reference processors (WP03).
    'Waaseyaa\Migration\Plugin\Process\PassThroughProcessor' => 'public',
    'Waaseyaa\Migration\Plugin\Process\HtmlSanitizeProcessor' => 'public',
    'Waaseyaa\Migration\Plugin\Process\LookupProcessor' => 'public',
    'Waaseyaa\Migration\Plugin\Process\ConcatProcessor' => 'public',
    'Waaseyaa\Migration\Plugin\Process\TypeCoerceProcessor' => 'public',
    'Waaseyaa\Migration\Plugin\Process\DefaultValueProcessor' => 'public',
    // Migration platform plugin meta (WP01).
    'Waaseyaa\Migration\Plugin\ReservedPluginIds' => 'public',
    // Migration platform exceptions (WP01..WP09).
    'Waaseyaa\Migration\Exception\SourceReadException' => 'public',
    'Waaseyaa\Migration\Exception\ProcessException' => 'public',
    'Waaseyaa\Migration\Exception\DestinationWriteException' => 'public',
    'Waaseyaa\Migration\Exception\MigrationAbortedException' => 'public',
    'Waaseyaa\Migration\Exception\MigrationConcurrencyException' => 'public',
    'Waaseyaa\Migration\Exception\MigrationCycleException' => 'public',
    'Waaseyaa\Migration\Exception\MigrationDependencyMissingException' => 'public',
    'Waaseyaa\Migration\Exception\MigrationPluginCollisionException' => 'public',
    // Migration platform schema + logging (WP04, WP10).
    'Waaseyaa\Migration\Schema\MigrationIdMapSchema' => 'public',
    'Waaseyaa\Migration\Log\Channels' => 'public',
    // Migration platform conformance bases (WP10, autoload-dev — stable surface for extenders).
    'Waaseyaa\Migration\Testing\SourceConformanceTestCase' => 'public',
    'Waaseyaa\Migration\Testing\DestinationConformanceTestCase' => 'public',
    // Listing pipeline value objects (mission listing-pipeline-v1-01KRMN0B WP01; charter §5.6).
    'Waaseyaa\Listing\ListingDefinition' => 'public',
    'Waaseyaa\Listing\FilterDefinition' => 'public',
    'Waaseyaa\Listing\SortDefinition' => 'public',
    'Waaseyaa\Listing\Pagination' => 'public',
    'Waaseyaa\Listing\ListingResult' => 'public',
    'Waaseyaa\Listing\ExposedFilterValues' => 'public',
    // Listing pipeline factories + enums (WP01).
    'Waaseyaa\Listing\Filter' => 'public',
    'Waaseyaa\Listing\Sort' => 'public',
    'Waaseyaa\Listing\Operator' => 'public',
    'Waaseyaa\Listing\SortDirection' => 'public',
    // Listing pipeline capability + services (WP02, WP05, WP09).
    'Waaseyaa\Listing\HasListingsInterface' => 'public',
    'Waaseyaa\Listing\ListingResolver' => 'public',
    'Waaseyaa\Listing\ListingDefinitionRegistry' => 'public',
    'Waaseyaa\Listing\ExposedFilterParser' => 'public',
    // Listing pipeline exceptions (WP11, WP02).
    'Waaseyaa\Listing\Exception\UnsupportedListingException' => 'public',
    'Waaseyaa\Listing\Exception\UnknownListingException' => 'public',

    // Layer 3: Services — internal
    'Waaseyaa\Billing\StripeClientInterface' => 'internal',
    // Listing pipeline internals (mission listing-pipeline-v1-01KRMN0B; NOT stable surface).
    'Waaseyaa\Listing\ListingCacheKeyBuilder' => 'internal',
    'Waaseyaa\Listing\ListingCacheInvalidator' => 'internal',
    'Waaseyaa\Listing\ListingDiscoverer' => 'internal',
    'Waaseyaa\Listing\ListingDefinitionValidator' => 'internal',
    'Waaseyaa\Listing\ExposedFilterCoercer' => 'internal',
    'Waaseyaa\Listing\Exception\ListingCoercionException' => 'internal',
    'Waaseyaa\Listing\EntityRepositoryRegistry' => 'internal',

    // Layer 4: API — public
    'Waaseyaa\Api\CodifiedContext\CodifiedContextSessionStoreInterface' => 'public',
    'Waaseyaa\Api\MutableTranslatableInterface' => 'public',
    // Admin read-model contracts: audit, MCP admin, media versions, Mercure monitor.
    'Waaseyaa\Api\Audit\AuditQueryReadModelInterface' => 'public',
    'Waaseyaa\Api\McpAdmin\ServerConfigReadModelInterface' => 'public',
    'Waaseyaa\Api\McpAdmin\ToolRegistryReadModelInterface' => 'public',
    'Waaseyaa\Api\Media\MediaVersionReadModelInterface' => 'public',
    'Waaseyaa\Api\MercureMonitor\ChannelInspectorInterface' => 'public',
    'Waaseyaa\Api\MercureMonitor\EventStreamReadModelInterface' => 'public',
    'Waaseyaa\Api\MercureMonitor\SubscriberObserverInterface' => 'public',
    'Waaseyaa\Routing\Language\LanguageNegotiatorInterface' => 'public',

    // Layer 5: AI — public
    'Waaseyaa\AI\Agent\Account\InitiatorAccountLoaderInterface' => 'public',
    'Waaseyaa\AI\Agent\AgentDefinition' => 'public',
    'Waaseyaa\AI\Agent\AgentDefinitionRegistry' => 'public',
    'Waaseyaa\AI\Agent\Attribute\AsAgentDefinition' => 'public',
    'Waaseyaa\AI\Agent\Broadcast\AgentRunBroadcasterInterface' => 'public',
    'Waaseyaa\AI\Agent\Provider\ProviderInterface' => 'public',
    'Waaseyaa\AI\Agent\Provider\StreamingProviderInterface' => 'public',
    'Waaseyaa\AI\Tools\AbstractAgentTool' => 'public',
    'Waaseyaa\AI\Tools\AgentTool' => 'public',
    'Waaseyaa\AI\Tools\AgentToolInterface' => 'public',
    'Waaseyaa\AI\Tools\AgentToolResult' => 'public',
    'Waaseyaa\AI\Tools\ToolRegistryInterface' => 'public',
    'Waaseyaa\AI\Tools\Attribute\AsAgentTool' => 'public',
    'Waaseyaa\AI\Pipeline\PipelineStepInterface' => 'public',
    'Waaseyaa\AI\Vector\VectorStoreInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingProviderInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingStorageInterface' => 'public',
    'Waaseyaa\AI\Vector\DistanceMetric' => 'public',
    'Waaseyaa\AI\Observability\Recorder\AgentRunMetricsRecorderInterface' => 'public',
    'Waaseyaa\AI\Observability\Recorder\AgentTelescopeRecorderInterface' => 'public',
    'Waaseyaa\AI\Observability\Recorder\TraceRecorderInterface' => 'public',
    'Waaseyaa\AI\Observability\Value\BudgetDecision' => 'public',
    'Waaseyaa\Bimaaji\Graph\GraphSectionProviderInterface' => 'public',
    'Waaseyaa\Bimaaji\Install\ClientTransformerInterface' => 'public',
    'Waaseyaa\Bimaaji\Install\Client\AbstractSingleFileClientTransformer' => 'public',

    // Layer 6: Interfaces — public
    'Waaseyaa\CLI\Ingestion\SourceConnectorInterface' => 'public',
    'Waaseyaa\AdminSurface\Action\SurfaceActionHandlerInterface' => 'public',
    'Waaseyaa\AdminSurface\Query\SurfaceFilterOperator' => 'public',
    'Waaseyaa\AdminSurface\Host\AbstractAdminSurfaceHost' => 'public',
    // ('Waaseyaa\Bimaaji\Graph\GraphSectionProviderInterface' is listed once in the Layer-5 public block above.)
    'Waaseyaa\Mcp\Bridge\ToolExecutorInterface' => 'public',
    'Waaseyaa\Mcp\Bridge\ToolRegistryInterface' => 'public',
    'Waaseyaa\Mcp\Auth\McpAuthInterface' => 'public',
    'Waaseyaa\Mcp\Admin\RecentInvocationsQueryInterface' => 'public',
    // Wayfinding Phase 5 (wayfinding-01KVGH5X): authenticated MCP write tier.
    // WriteTierAuthInterface is the app override point for write-tier credentials;
    // AbstractTrailTool is the internal shared base for the wayfinding trail tools.
    'Waaseyaa\Mcp\Auth\WriteTierAuthInterface' => 'public',
    'Waaseyaa\AI\Agent\Tool\Wayfinding\AbstractTrailTool' => 'internal',
    'Waaseyaa\Oidc\Keys\OidcKeyLoaderInterface' => 'public',
    'Waaseyaa\Oidc\Repository\AuthorizationCodeRepositoryInterface' => 'public',
    'Waaseyaa\Oidc\Token\KeyMaterialProviderInterface' => 'public',
    'Waaseyaa\SSR\ThemeInterface' => 'public',

    // Layer 1: Core Data — public (discovered during L5-L6 scan)
    'Waaseyaa\OAuthProvider\OAuthProviderInterface' => 'public',
    'Waaseyaa\OAuthProvider\SessionInterface' => 'public',
    // Audit log: query/write contracts and event-kind enum.
    'Waaseyaa\Audit\Contract\AuditQueryInterface' => 'public',
    'Waaseyaa\Audit\Contract\AuditWriterInterface' => 'public',
    'Waaseyaa\Audit\Enum\AuditEventKind' => 'public',

    // Layer 3: Services — public (single-entity-work-surface-01KQ7M1P)
    'Waaseyaa\StructuredImport\StructuredImporterInterface' => 'public',

    'Waaseyaa\CLI\Io\StdinSource' => 'public',

    // Layer 6: Interfaces — internal
    'Waaseyaa\Telescope\Storage\TelescopeStoreInterface' => 'internal',
    'Waaseyaa\Telescope\CodifiedContext\Validator\EmbeddingProviderInterface' => 'internal',
    'Waaseyaa\Telescope\CodifiedContext\Storage\CodifiedContextStoreInterface' => 'internal',
    'Waaseyaa\CLI\Command\Make\AbstractMakeCommand' => 'internal',
    'Waaseyaa\CLI\Command\Make\AbstractMakeHandler' => 'internal',
    'Waaseyaa\CLI\Command\HandlerArgumentMode' => 'public',
    'Waaseyaa\CLI\Command\HandlerOptionMode' => 'public',
    'Waaseyaa\SSR\Http\AppController\AppControllerArgumentResolver' => 'public',
    'Waaseyaa\SSR\Http\AppController\AppParameterKind' => 'public',

    // Layer 5: AI — agent-executor v1 (agent-executor-01KRWPK7, WP-02)
    'Waaseyaa\AI\Agent\Enum\EventType' => 'public',
    'Waaseyaa\AI\Agent\Enum\HitlMode' => 'public',
    'Waaseyaa\AI\Agent\Enum\RunStatus' => 'public',
];
