<?php

// Authoritative disposition map for all public API elements.
// Format: 'Fully\Qualified\ClassName' => 'public|internal|extract|remove'
// This file is verified by PublicSurfaceVerificationTest.

declare(strict_types=1);

return [
    // Layer 0: Foundation — public
    'Waaseyaa\Foundation\Asset\AssetManagerInterface' => 'public',
    'Waaseyaa\Foundation\Broadcasting\BroadcasterInterface' => 'public',
    'Waaseyaa\Foundation\Diagnostic\HealthCheckerInterface' => 'public',
    'Waaseyaa\Foundation\Log\LoggerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Handler\HandlerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Formatter\FormatterInterface' => 'public',
    'Waaseyaa\Foundation\Log\Processor\ProcessorInterface' => 'public',
    'Waaseyaa\Foundation\Log\LoggerTrait' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\RateLimit\RateLimiterInterface' => 'public',
    'Waaseyaa\Foundation\Schema\SchemaRegistryInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProviderInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProvider' => 'public',
    'Waaseyaa\Foundation\Event\DomainEvent' => 'public',
    'Waaseyaa\Foundation\Exception\WaaseyaaException' => 'public',
    'Waaseyaa\Foundation\Http\JsonApiResponseTrait' => 'public',
    'Waaseyaa\Foundation\Migration\Migration' => 'public',
    'Waaseyaa\Cache\CacheBackendInterface' => 'public',
    'Waaseyaa\Cache\CacheFactoryInterface' => 'public',
    'Waaseyaa\Cache\CacheTagsInvalidatorInterface' => 'public',
    'Waaseyaa\Cache\TagAwareCacheInterface' => 'public',
    'Waaseyaa\Database\DatabaseInterface' => 'public',
    'Waaseyaa\Database\SelectInterface' => 'public',
    'Waaseyaa\Database\InsertInterface' => 'public',
    'Waaseyaa\Database\UpdateInterface' => 'public',
    'Waaseyaa\Database\DeleteInterface' => 'public',
    'Waaseyaa\Database\SchemaInterface' => 'public',
    'Waaseyaa\Database\TransactionInterface' => 'public',
    'Waaseyaa\Plugin\PluginInspectionInterface' => 'public',
    'Waaseyaa\Plugin\PluginManagerInterface' => 'public',
    'Waaseyaa\Plugin\PluginBase' => 'public',
    'Waaseyaa\TypedData\TypedDataInterface' => 'public',
    'Waaseyaa\TypedData\DataDefinitionInterface' => 'public',
    'Waaseyaa\TypedData\ComplexDataInterface' => 'public',
    'Waaseyaa\TypedData\ListInterface' => 'public',
    'Waaseyaa\TypedData\PrimitiveInterface' => 'public',
    'Waaseyaa\TypedData\TypedDataManagerInterface' => 'public',
    'Waaseyaa\I18n\LanguageManagerInterface' => 'public',
    'Waaseyaa\I18n\TranslatorInterface' => 'public',
    'Waaseyaa\Queue\QueueInterface' => 'public',
    'Waaseyaa\Testing\Traits\CreatesApplication' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithApi' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithAuth' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithEvents' => 'public',
    'Waaseyaa\Testing\Traits\RefreshDatabase' => 'public',

    // Layer 0: Foundation — internal
    'Waaseyaa\Foundation\Kernel\AbstractKernel' => 'internal',
    'Waaseyaa\Foundation\Tenant\TenantResolverInterface' => 'internal',
    'Waaseyaa\Plugin\Discovery\PluginDiscoveryInterface' => 'internal',
    'Waaseyaa\Plugin\Extension\KnowledgeToolingExtensionInterface' => 'internal',
    'Waaseyaa\Plugin\Factory\PluginFactoryInterface' => 'internal',
    'Waaseyaa\Queue\Handler\HandlerInterface' => 'internal',
    'Waaseyaa\Queue\Transport\TransportInterface' => 'internal',
    'Waaseyaa\Queue\FailedJobRepositoryInterface' => 'internal',
    'Waaseyaa\Queue\Job' => 'internal',
    'Waaseyaa\Scheduler\Lock\LockInterface' => 'internal',
    'Waaseyaa\Scheduler\ScheduleInterface' => 'internal',
    'Waaseyaa\State\StateInterface' => 'internal',
    'Waaseyaa\Mail\MailerInterface' => 'internal',
    'Waaseyaa\Mail\MailDriverInterface' => 'internal',
    'Waaseyaa\Mail\Transport\TransportInterface' => 'internal',
    'Waaseyaa\HttpClient\HttpClientInterface' => 'internal',
    'Waaseyaa\Ingestion\PayloadValidatorInterface' => 'internal',
    'Waaseyaa\Ingestion\EnvelopeValidator' => 'internal',
    'Waaseyaa\Testing\WaaseyaaTestCase' => 'internal',
    'Waaseyaa\Testing\GraphQL\AbstractGraphQlSchemaContractTestCase' => 'internal',
];
