<?php

declare(strict_types=1);

namespace App\Provider;

use Waaseyaa\Entity\EntityType;
use Waaseyaa\Foundation\ServiceProvider\ServiceProvider;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Registers every governed application blueprint entity type; do not edit by
 * hand. The relationship registry consumed for referential integrity lives at
 * config/waaseyaa-blueprint/relationships.php.
 */
final class ApplicationBlueprintServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->entityType(EntityType::fromClass(
            \App\Entity\Article::class,
            revisionable: false,
            translatable: false,
        ));

    }
}
