<?php

declare(strict_types=1);

// Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
// One row per blueprint relationship. Consumed by the generated application
// blueprint provider for referential integrity; do not edit by hand.
return [];
