<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install\Client;

use Waaseyaa\Bimaaji\Install\ClientCapabilities;
use Waaseyaa\Bimaaji\Install\ClientCapabilityRegistry;
use Waaseyaa\Bimaaji\Install\ClientTransformerInterface;
use Waaseyaa\Bimaaji\Install\ManagedRegion;
use Waaseyaa\Bimaaji\Install\ParsedSkill;
use Waaseyaa\Bimaaji\Install\SkillInventory;
use Waaseyaa\Bimaaji\Install\SkillSourceProvenance;
use Waaseyaa\Bimaaji\Install\TargetFile;

/**
 * Shared base for clients that receive concise guidance plus one on-demand
 * skill file per canonical inventory entry (#2660).
 *
 * @api
 */
abstract class AbstractPerSkillClientTransformer implements ClientTransformerInterface
{
    /**
     * @param ClientCapabilities|null $capabilities Overrides the registered
     *     entry. Null — the production path — resolves
     *     {@see ClientCapabilityRegistry::default()}. A non-null value must
     *     declare this client id; anything else is a programming error.
     */
    public function __construct(private readonly ?ClientCapabilities $capabilities = null) {}

    /**
     * @param list<ParsedSkill> $skills
     * @return list<TargetFile>
     */
    public function targetFiles(array $skills): array
    {
        $capabilities = $this->resolveCapabilities();
        $provenance = SkillSourceProvenance::fromInventory(SkillInventory::fromSkills($skills));
        $files = [];

        foreach ($skills as $skill) {
            $files[] = new TargetFile(
                path: $capabilities->skillFilePath($skill->id),
                content: $this->renderSkillFile($skill, $capabilities, $provenance),
                sourceSkill: $skill->id,
            );
        }

        $files[] = new TargetFile(
            path: $capabilities->guidancePath,
            content: $this->renderGuidance($skills, $capabilities, $provenance),
            sourceSkill: null,
        );

        return $files;
    }

    private function resolveCapabilities(): ClientCapabilities
    {
        if ($this->capabilities !== null) {
            if ($this->capabilities->clientId !== $this->clientId()) {
                throw new \LogicException(sprintf(
                    '%s was given capabilities that declare client "%s", not "%s".',
                    static::class,
                    $this->capabilities->clientId,
                    $this->clientId(),
                ));
            }

            return $this->capabilities;
        }

        $capabilities = ClientCapabilityRegistry::default()->for($this->clientId());
        if ($capabilities === null) {
            throw new \LogicException(sprintf(
                'No registered ClientCapabilityRegistry entry for client "%s".',
                $this->clientId(),
            ));
        }

        return $capabilities;
    }

    private function renderSkillFile(
        ParsedSkill $skill,
        ClientCapabilities $capabilities,
        SkillSourceProvenance $provenance,
    ): string {
        $body = ManagedRegion::wrap(
            trim($skill->body) . "\n\n" . $provenance->managedRegionFooter(),
        );

        if (!$capabilities->requiresFrontmatterAtByteZero) {
            return $body;
        }

        return sprintf(
            "---\nname: %s\ndescription: %s\n---\n\n%s",
            $capabilities->skillDirectoryName($skill->id),
            $this->escapeYamlScalar($skill->description),
            $body,
        );
    }

    /**
     * @param list<ParsedSkill> $skills
     */
    private function renderGuidance(
        array $skills,
        ClientCapabilities $capabilities,
        SkillSourceProvenance $provenance,
    ): string {
        $lines = [
            $this->guidanceTitle(),
            '',
            'Auto-generated by `bin/waaseyaa bimaaji:install`. Re-run the install command to refresh.',
            'Edits outside the markers below are preserved across re-runs.',
            '',
            'Always-loaded guidance stays concise. Detailed framework knowledge lives in the per-skill files listed below and loads on demand.',
            '',
            '## Available skills',
            '',
        ];

        if ($skills === []) {
            $lines[] = '_No skills installed._';
        } else {
            foreach ($skills as $skill) {
                $lines[] = sprintf(
                    '- **%s** — %s — `%s` (source sha256 `%s`)',
                    $skill->name,
                    $skill->description,
                    $capabilities->skillFilePath($skill->id),
                    $skill->sourceSha256,
                );
            }
        }

        $lines[] = '';
        $lines[] = '## Source provenance';
        $lines[] = '';
        $lines[] = sprintf('- inventory sha256: `%s`', $provenance->inventorySha256);
        $lines[] = $provenance->managedRegionFooter();

        return ManagedRegion::wrap(implode("\n", $lines));
    }

    abstract protected function guidanceTitle(): string;

    private function escapeYamlScalar(string $value): string
    {
        if (str_contains($value, ':') || str_contains($value, '#') || str_contains($value, '"')) {
            return "'" . str_replace("'", "''", $value) . "'";
        }

        return $value;
    }
}
