<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install\Client;

use Waaseyaa\Bimaaji\Install\ClientTransformerInterface;
use Waaseyaa\Bimaaji\Install\ParsedSkill;
use Waaseyaa\Bimaaji\Install\TargetFile;

/**
 * Shared base for client transformers that emit one consolidated config
 * file per project (Cursor / Codex / Copilot / Gemini / Windsurf / Junie).
 *
 * The body layout is a standardised prelude line, followed by each skill's
 * body separated by `\n\n---\n\n` with the skill name as an H2, framed by
 * begin/end markers so the WP03 `--merge` mode can splice the block into
 * an existing user file without clobbering hand-written content above or
 * below it.
 *
 * Subclasses provide only the client identifier and target file path; all
 * formatting lives here so single-file conventions stay symmetric across
 * the seven supported clients.
 *
 * @api
 */
abstract class AbstractSingleFileClientTransformer implements ClientTransformerInterface
{
    private const string MARKER_BEGIN = '<!-- waaseyaa:bimaaji:install BEGIN -->';
    private const string MARKER_END = '<!-- waaseyaa:bimaaji:install END -->';
    private const string PRELUDE = 'Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.';

    /**
     * Relative path to the consolidated config file (e.g. `.cursorrules`).
     */
    abstract protected function targetPath(): string;

    /**
     * @param list<ParsedSkill> $skills
     * @return list<TargetFile>
     */
    public function targetFiles(array $skills): array
    {
        $body = self::MARKER_BEGIN . "\n\n"
            . self::PRELUDE . "\n\n"
            . $this->renderSkills($skills) . "\n\n"
            . self::MARKER_END . "\n";

        return [new TargetFile(path: $this->targetPath(), content: $body, sourceSkill: null)];
    }

    /**
     * @param list<ParsedSkill> $skills
     */
    private function renderSkills(array $skills): string
    {
        if ($skills === []) {
            return '_No skills to install._';
        }

        $blocks = [];
        foreach ($skills as $skill) {
            $blocks[] = sprintf("## %s\n\n%s", $skill->name, trim($skill->body));
        }

        return implode("\n\n---\n\n", $blocks);
    }
}
