<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install\Client;

use Waaseyaa\Bimaaji\Install\ClientCapabilities;
use Waaseyaa\Bimaaji\Install\ClientCapabilityRegistry;
use Waaseyaa\Bimaaji\Install\ClientTransformerInterface;
use Waaseyaa\Bimaaji\Install\ManagedRegion;
use Waaseyaa\Bimaaji\Install\ParsedSkill;
use Waaseyaa\Bimaaji\Install\TargetFile;

/**
 * Shared base for client transformers that emit one consolidated config
 * file per project (Cursor / Codex / Copilot / Gemini / Windsurf / Junie).
 *
 * The body layout is a standardised prelude line, followed by each skill's
 * body separated by `\n\n---\n\n` with the skill name as an H2, framed by
 * the {@see ManagedRegion} begin/end markers. The install command splices
 * the block into an existing user file, so hand-written content above or
 * below the markers survives a re-run (#2656).
 *
 * Subclasses provide only the client identifier; the target path is data,
 * not code — it is read from {@see ClientCapabilityRegistry} by
 * `clientId()`, so the mapping from client to path lives in exactly one
 * place instead of one `targetPath()` override per subclass (#2660 Part A).
 * All formatting lives here so single-file conventions stay symmetric
 * across the seven supported clients.
 *
 * @api
 */
abstract class AbstractSingleFileClientTransformer implements ClientTransformerInterface
{
    private const string PRELUDE = 'Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.';

    /**
     * @param list<ParsedSkill> $skills
     * @return list<TargetFile>
     */
    public function targetFiles(array $skills): array
    {
        $body = ManagedRegion::wrap(self::PRELUDE . "\n\n" . $this->renderSkills($skills));

        return [new TargetFile(path: $this->capabilities()->guidancePath, content: $body, sourceSkill: null)];
    }

    /**
     * This client's registered capabilities.
     *
     * @throws \LogicException When `clientId()` has no registry entry — a
     *     programming error (a new client class added without a matching
     *     {@see ClientCapabilityRegistry::default()} entry), never a
     *     reachable runtime state for the seven shipped clients.
     */
    private function capabilities(): ClientCapabilities
    {
        $capabilities = ClientCapabilityRegistry::default()->for($this->clientId());
        if ($capabilities === null) {
            throw new \LogicException(sprintf(
                'No registered ClientCapabilityRegistry entry for client "%s".',
                $this->clientId(),
            ));
        }

        return $capabilities;
    }

    /**
     * @param list<ParsedSkill> $skills
     */
    private function renderSkills(array $skills): string
    {
        if ($skills === []) {
            return '_No skills to install._';
        }

        $blocks = [];
        foreach ($skills as $skill) {
            $blocks[] = sprintf("## %s\n\n%s", $skill->name, trim($skill->body));
        }

        return implode("\n\n---\n\n", $blocks);
    }
}
