<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Install\Client;

use Waaseyaa\Bimaaji\Install\ClientTransformerInterface;
use Waaseyaa\Bimaaji\Install\ManagedRegion;
use Waaseyaa\Bimaaji\Install\ParsedSkill;
use Waaseyaa\Bimaaji\Install\TargetFile;

/**
 * Multi-file transformer for Claude Code.
 *
 * Claude Code reads `.claude/skills/<id>.md` files individually so a user can
 * load just the skill they need with `/skill <id>` rather than carrying the
 * whole guidelines blob in every conversation. We emit one file per skill
 * (`waaseyaa-<id>.md`) plus one consolidated guidelines page
 * (`.claude/CLAUDE-WAASEYAA.md`) that links to each skill — symmetric with
 * the other clients' single-file output for users who prefer the full set.
 *
 * Both outputs are marker-bounded (see {@see ManagedRegion}). For a
 * per-skill file the markers open *after* the YAML frontmatter, because
 * Claude Code requires the frontmatter to start at byte 0 — so the skill
 * body refreshes on every run while a consumer's own `name`/`description`
 * edits, and any notes they append below the closing marker, survive.
 *
 * Upstream convention: https://docs.claude.com/en/docs/claude-code/skills
 * (verified 2026-05-22).
 *
 * @api
 */
final class ClaudeClientTransformer implements ClientTransformerInterface
{
    public function clientId(): string
    {
        return 'claude';
    }

    public function targetFiles(array $skills): array
    {
        $files = [];

        foreach ($skills as $skill) {
            $files[] = new TargetFile(
                path: sprintf('.claude/skills/waaseyaa-%s.md', $skill->id),
                content: $this->renderSkillFile($skill),
                sourceSkill: $skill->id,
            );
        }

        $files[] = new TargetFile(
            path: '.claude/CLAUDE-WAASEYAA.md',
            content: $this->renderIndex($skills),
            sourceSkill: null,
        );

        return $files;
    }

    private function renderSkillFile(ParsedSkill $skill): string
    {
        return sprintf(
            "---\nname: waaseyaa-%s\ndescription: %s\n---\n\n%s",
            $skill->id,
            $this->escapeYamlScalar($skill->description),
            ManagedRegion::wrap($skill->body),
        );
    }

    /** @param list<ParsedSkill> $skills */
    private function renderIndex(array $skills): string
    {
        $lines = [
            '# Waaseyaa framework — Claude Code guidelines',
            '',
            'Auto-generated by `bin/waaseyaa bimaaji:install`. Re-run the install command to refresh.',
            'Edits outside the markers below are preserved across re-runs.',
            '',
            '## Available skills',
            '',
        ];

        if ($skills === []) {
            $lines[] = '_No skills installed._';
        } else {
            foreach ($skills as $skill) {
                $lines[] = sprintf('- **%s** — %s', $skill->name, $skill->description);
            }
        }

        return ManagedRegion::wrap(implode("\n", $lines));
    }

    private function escapeYamlScalar(string $value): string
    {
        if (str_contains($value, ':') || str_contains($value, '#') || str_contains($value, '"')) {
            return "'" . str_replace("'", "''", $value) . "'";
        }

        return $value;
    }
}
