<?php

declare(strict_types=1);

namespace Waaseyaa\Bimaaji\Tests\Fixture;

/**
 * Golden snapshot of every client transformer's `targetFiles()` output for
 * `InstallSkillFixtures::all()` (and, per client, the empty-skill-set case),
 * captured from the pre-#2660-Part-A implementation before the client
 * capability registry / skill inventory refactor landed.
 *
 * `Waaseyaa\Bimaaji\Tests\Unit\Install\TransformerOutputRegressionTest`
 * diffs the refactored transformers against this literal snapshot so the
 * capability-registry seam can be proven behaviour-preserving: not one byte
 * of any client's on-disk output may change as a result of that refactor.
 *
 * Regenerate only when a transformer's output is INTENTIONALLY changed by a
 * later issue (e.g. #2660's own gated follow-up once open questions (a)-(c)
 * are decided) — never as a reflex to make a failing regression test pass.
 *
 * @return array<string, list<array{path: string, content: string, sourceSkill: string|null}>>
 */
return [
    'claude' =>
     [
         0 =>
          [
              'path' => '.claude/skills/waaseyaa-skill-alpha/SKILL.md',
              'content' => '---
name: waaseyaa-skill-alpha
description: First fixture skill used by the client-transformer contract tests.
---

<!-- waaseyaa:bimaaji:install BEGIN -->

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => 'skill-alpha',
          ],
         1 =>
          [
              'path' => '.claude/skills/waaseyaa-skill-beta/SKILL.md',
              'content' => '---
name: waaseyaa-skill-beta
description: Second fixture skill — single-paragraph body for size assertions.
---

<!-- waaseyaa:bimaaji:install BEGIN -->

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => 'skill-beta',
          ],
         2 =>
          [
              'path' => '.claude/skills/waaseyaa-skill-gamma/SKILL.md',
              'content' => '---
name: waaseyaa-skill-gamma
description: Third fixture skill — H2 sub-headings inside the body.
---

<!-- waaseyaa:bimaaji:install BEGIN -->

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => 'skill-gamma',
          ],
         3 =>
          [
              'path' => '.claude/CLAUDE-WAASEYAA.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

# Waaseyaa framework — Claude Code guidelines

Auto-generated by `bin/waaseyaa bimaaji:install`. Re-run the install command to refresh.
Edits outside the markers below are preserved across re-runs.

## Available skills

- `/waaseyaa-skill-alpha` — **skill-alpha** — First fixture skill used by the client-transformer contract tests.
- `/waaseyaa-skill-beta` — **skill-beta** — Second fixture skill — single-paragraph body for size assertions.
- `/waaseyaa-skill-gamma` — **skill-gamma** — Third fixture skill — H2 sub-headings inside the body.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'claude__empty' =>
     [
         0 =>
          [
              'path' => '.claude/CLAUDE-WAASEYAA.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

# Waaseyaa framework — Claude Code guidelines

Auto-generated by `bin/waaseyaa bimaaji:install`. Re-run the install command to refresh.
Edits outside the markers below are preserved across re-runs.

## Available skills

_No skills installed._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'codex' =>
     [
         0 =>
          [
              'path' => 'AGENTS.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'codex__empty' =>
     [
         0 =>
          [
              'path' => 'AGENTS.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'copilot' =>
     [
         0 =>
          [
              'path' => '.github/copilot-instructions.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'copilot__empty' =>
     [
         0 =>
          [
              'path' => '.github/copilot-instructions.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'cursor' =>
     [
         0 =>
          [
              'path' => '.cursorrules',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'cursor__empty' =>
     [
         0 =>
          [
              'path' => '.cursorrules',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'gemini' =>
     [
         0 =>
          [
              'path' => 'GEMINI.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'gemini__empty' =>
     [
         0 =>
          [
              'path' => 'GEMINI.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'junie' =>
     [
         0 =>
          [
              'path' => '.junie/guidelines.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'junie__empty' =>
     [
         0 =>
          [
              'path' => '.junie/guidelines.md',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'windsurf' =>
     [
         0 =>
          [
              'path' => '.windsurfrules',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

## skill-alpha

# Skill Alpha

Use this skill when the framework asks for a basic fixture.

It has three short paragraphs of body content. The frontmatter above MUST
be stripped by the transformer — only this body section is emitted into
the per-client target file.

Closing paragraph confirms multi-paragraph bodies survive the transform.

---

## skill-beta

Single-paragraph body. Used by the size-budget assertions in the
single-file transformer tests.

---

## skill-gamma

## Subsection one

Body text under the subsection.

## Subsection two

More body text. The transformer must preserve the inner H2s exactly;
only the leading frontmatter block is stripped.

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
    'windsurf__empty' =>
     [
         0 =>
          [
              'path' => '.windsurfrules',
              'content' => '<!-- waaseyaa:bimaaji:install BEGIN -->

Waaseyaa framework conventions — auto-generated by `bin/waaseyaa bimaaji:install`. Do not edit between the markers below; re-run the install command to refresh.

_No skills to install._

<!-- waaseyaa:bimaaji:install END -->
',
              'sourceSkill' => null,
          ],
     ],
];
