<?php

declare(strict_types=1);

namespace App\Workflow;

/**
 * Generated by Waaseyaa\CLI\Site\Blueprint\ApplicationBlueprintCompiler.
 * Do not edit by hand. Pass DEFINITION to `new Waaseyaa\Workflows\Workflow(...)`.
 */
final class EditorialWorkflowDefinition
{
    /** @var array<string, mixed> */
    public const array DEFINITION = [
        'id' => 'editorial',
        'label' => 'Editorial',
        'initial_state' => 'draft',
        'states' => [
            'draft' => ['label' => 'Draft', 'published' => false, 'default_revision' => false],
            'published' => ['label' => 'Published', 'published' => true, 'default_revision' => true],
        ],
        'transitions' => [
            'publish' => [
                'label' => 'Publish',
                'from' => ['draft'],
                'to' => 'published',
                'permission' => 'use editorial transition publish',
            ],
        ],
    ];
}
